package root:component;

world root {
  include kontor:built-in/built-in;
  use kontor:built-in/context.{view-context, proc-context, signer, contract};
  use kontor:built-in/error.{error};
  use kontor:built-in/foreign.{contract-address};
  use kontor:built-in/numbers.{decimal};

  record token-pair {
    a: contract-address,
    b: contract-address,
  }

  record deposit-result {
    lp-shares: decimal,
    deposit-a: decimal,
    deposit-b: decimal,
  }

  record withdraw-result {
    amount-a: decimal,
    amount-b: decimal,
  }

  export init: async func(ctx: borrow<proc-context>) -> contract;

  export create: async func(ctx: borrow<proc-context>, pair: token-pair, amount-a: decimal, amount-b: decimal, fee-bps: decimal) -> result<decimal, error>;

  export fee: async func(ctx: borrow<view-context>, pair: token-pair) -> result<decimal, error>;

  export balance: async func(ctx: borrow<view-context>, pair: token-pair, acc: string) -> option<decimal>;
  export token-balance: async func(ctx: borrow<view-context>, pair: token-pair, token: contract-address) -> result<decimal, error>;
  export quote-deposit: async func(ctx: borrow<view-context>, pair: token-pair, amount-a: decimal, amount-b: decimal) -> result<deposit-result, error>;
  export deposit: async func(ctx: borrow<proc-context>, pair: token-pair, amount-a: decimal, amount-b: decimal) -> result<deposit-result, error>;
  export quote-withdraw: async func(ctx: borrow<view-context>, pair: token-pair, shares: decimal) -> result<withdraw-result, error>;
  export withdraw: async func(ctx: borrow<proc-context>, pair: token-pair, shares: decimal) -> result<withdraw-result, error>;


  export swap: async func(ctx: borrow<proc-context>, pair: token-pair, token-in: contract-address, amount-in: decimal, min-out: decimal) -> result<decimal, error>;
  export quote-swap: async func(ctx: borrow<view-context>, pair: token-pair, token-in: contract-address, amount-in: decimal) -> result<decimal, error>;
}
