/**
 * End-to-end test of the codegen pipeline against the session / Inst
 * model. The token contract's TS bindings are pre-generated by
 * `vitest.globalSetup.ts` into `__generated__/token.ts`, so this runs
 * identically in Node and browser environments.
 *
 * Two surfaces, both exercising the round-trip
 *   canonical class → .toRaw() → WAVE encode → WAVE decode → fromRaw:
 *
 *   - view methods → full round trip through a mock `transport.view`.
 *   - proc methods → return an `Inst`; assert the encoded WAVE call
 *     (`inst.kind.expr`) and the decoder (`inst._decode`). Real
 *     broadcast (`submit()`/`wait()`) is exercised by the live regtest
 *     suite, not here.
 */
import { test, expect, afterEach } from "vitest";
import {
  type Signing,
  type KontorTransport,
  Decimal,
  HolderRef,
  KontorSession,
  Result,
  signet,
} from "@kontor/sdk";
import { Contract } from "./__generated__/token";

/**
 * Render a Decimal as its WAVE literal. The on-chain encoding is
 * `value * 10^18` packed into four little-endian u64 limbs, so writing
 * raw r0..r3 literals in tests is impractical — build them from a real
 * Decimal instead.
 */
function decimalWave(value: string): string {
  const raw = Decimal.from(value).toRaw();
  return `{r0: ${raw.r0}, r1: ${raw.r1}, r2: ${raw.r2}, r3: ${raw.r3}, sign: ${raw.sign}}`;
}

/** Throwaway Signing — the mock-transport e2e never signs or broadcasts. */
const stubSigning: Signing = {
  identity: {
    xOnlyPubKey: "00".repeat(32),
    address: "tb1pstub",
    holderRef: HolderRef.xOnlyPubkey("00".repeat(32)),
  },
  psbt: () => Promise.reject(new Error("stub signing: psbt")),
};

/** Sessions created by `mockSession`, closed after each test so the
 *  background poller loops don't outlive the test. */
const openSessions: KontorSession[] = [];
afterEach(() => {
  for (const s of openSessions) s.close();
  openSessions.length = 0;
});

/**
 * Feed the always-on results poller an idle indexer: it bootstraps,
 * then quietly long-polls with nothing to report.
 */
const pollerFetch = (async (url: string) => {
  const body = url.includes("/results")
    ? {
        results: [],
        pagination: { has_more: false, next_offset: null, total_count: 0 },
      }
    : { last_result_id: 0, recent_blocks: [], signature: "idle" };
  if (url.includes("?wait=")) await new Promise((r) => setTimeout(r, 5));
  return new Response(JSON.stringify({ result: body }), {
    status: 200,
    headers: { "content-type": "application/json" },
  });
}) as typeof fetch;

/**
 * A `KontorSession` whose `view` calls return canned WAVE responses
 * keyed by function name. `calls` records every WAVE expression seen.
 * `inspect` / `simulate` / `submit` are unused here — the live regtest
 * suite covers real broadcast.
 */
function mockSession(viewResponses: Record<string, string>): {
  session: KontorSession;
  calls: string[];
} {
  const calls: string[] = [];
  const notUsed = () =>
    Promise.reject(new Error("e2e mock: only `view` is exercised"));
  const transport: KontorTransport = {
    view: async (_contract, wave) => {
      calls.push(wave);
      const name = wave.match(/^([a-z][a-z0-9-]*)\(/)?.[1];
      if (name == null) {
        throw new Error(`could not parse function name from: ${wave}`);
      }
      const resp = viewResponses[name];
      if (resp == null) {
        throw new Error(`no canned response for ${name}`);
      }
      return resp;
    },
    inspect: notUsed,
    simulate: notUsed,
    submit: notUsed,
    compose: notUsed,
    composeReveal: notUsed,
    broadcast: notUsed,
  };
  const session = new KontorSession({
    chain: signet,
    signing: stubSigning,
    transport: () => transport,
    fetch: pollerFetch,
  });
  openSessions.push(session);
  return { session, calls };
}

test("e2e: view balance() encodes HolderRef arg, decodes some(Decimal)", async () => {
  const { session, calls } = mockSession({
    balance: `some(${decimalWave("100")})`,
  });
  const c = session.bind(Contract, "token@0.0");
  const result = await c.balance(HolderRef.xOnlyPubkey("abc"));
  expect(result).toBeInstanceOf(Decimal);
  expect(result!.toString()).toBe("100");
  expect(calls[0]).toBe('balance(x-only-pubkey("abc"))');
});

test("e2e: view balance() decodes none → null", async () => {
  const { session } = mockSession({ balance: "none" });
  const c = session.bind(Contract, "token@0.0");
  expect(await c.balance(HolderRef.core())).toBeNull();
});

test("e2e: view balance() round-trips HolderRef.utxo", async () => {
  const { session, calls } = mockSession({
    balance: `some(${decimalWave("0")})`,
  });
  const c = session.bind(Contract, "token@0.0");
  await c.balance(HolderRef.utxo({ txid: "deadbeef", vout: 7 }));
  expect(calls[0]).toBe('balance(utxo({txid: "deadbeef", vout: 7}))');
});

test("e2e: proc transfer() builds a Call Inst carrying the encoded WAVE", () => {
  const { session } = mockSession({});
  const c = session.bind(Contract, "token@0.0");
  const inst = c.transfer(HolderRef.xOnlyPubkey("bb"), Decimal.from("42"));

  expect(inst.kind.kind).toBe("Call");
  if (inst.kind.kind !== "Call") throw new Error("expected a Call inst");
  expect(inst.kind.fnName).toBe("transfer");
  // The encoded WAVE: x-only-pubkey for dst, {r0..r3, sign} for the Decimal.
  expect(inst.kind.expr).toBe(
    `transfer(x-only-pubkey("bb"), ${decimalWave("42")})`,
  );
});

test("e2e: proc transfer() decoder round-trips the ok arm of Result<Transfer, Error>", () => {
  const { session } = mockSession({});
  const c = session.bind(Contract, "token@0.0");
  const inst = c.transfer(HolderRef.core(), Decimal.from("0"));

  const r = inst._decode(
    `ok({src: x-only-pubkey("aa"), dst: x-only-pubkey("bb"), amt: ${decimalWave("42")}})`,
  );
  const ok = Result.unwrap(r);
  expect(ok.amt).toBeInstanceOf(Decimal);
  expect(ok.amt.toString()).toBe("42");
  expect(ok.src.kind).toBe("x-only-pubkey");
});

test("e2e: proc transfer() decoder round-trips the err arm", () => {
  const { session } = mockSession({});
  const c = session.bind(Contract, "token@0.0");
  const inst = c.transfer(HolderRef.core(), Decimal.from("0"));

  const r = inst._decode('err(message("not enough funds"))');
  const err = Result.unwrapErr(r);
  expect(err.kind).toBe("message");
  if (err.kind === "message") {
    expect(err.value).toBe("not enough funds");
  }
});
