// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Inst =
  | { "Publish": { gas_limit: number; name: string; bytes: Array<number> } }
  | {
    "Call": {
      gas_limit: number;
      contract: string;
      nonce: number | null;
      expr: string;
    };
  }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  };

export type OpMetadata = {
  previous_output: string;
  input_index: number;
  signer: Signer;
};

export type Signer = { "Core": Signer } | { "XOnlyPubKey": string } | {
  "ContractId": { id: number; id_str: string };
} | "Nobody";
