// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregateInfo = {
  signer_ids: Array<bigint>;
  signature: Array<number>;
  /**
   * Publisher's gas-sponsorship commitment for this bulk.
   * - `None`: no sponsorship offered. Any op signing `PaymentIntent::Sponsored`
   *   is rejected.
   * - `Some(n)`: publisher commits up to `n` per sponsored op. Validated
   *   `n > 0` in `validate_aggregate_shape`.
   */
  publisher_sponsorship: number | null;
};

export type Block = {
  height: number;
  hash: string;
  prev_hash: string;
  transactions: Array<Transaction>;
};

export type BlockRow = { height: number; hash: string; relevant: boolean };

export type CommitOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_inputs: RevealInputs;
};

export type ComposeOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_transaction: string;
  reveal_transaction_hex: string;
  reveal_psbt_hex: string;
  per_participant: Array<ParticipantScripts>;
};

export type ComposeQuery = {
  instructions: Array<InstructionQuery>;
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  envelope: number | null;
};

/**
 * Whether this node participates in consensus voting.
 *
 * Surfaced in the `Info` response so operators monitoring the cluster
 * externally can confirm a pod's actual mode rather than just trusting
 * the config they passed in.
 */
export type ConsensusMode = "validator" | "follower";

export type ContractListRow = {
  id: number;
  name: string;
  height: number;
  tx_index: number;
  size: number;
  signer_id: number | null;
};

export type ContractResponse = { wit: string };

export type ErrorResponse = { error: string };

export type Event =
  | { "type": "Processed"; block: BlockRow; txids: Array<string> }
  | { "type": "BatchProcessed"; txids: Array<string> }
  | { "type": "Rolledback"; height: number };

export type Fees = {
  /**
   * Recommended fee rate (sat/vB) to land in the next ~1 block.
   */
  fastest: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 3 blocks.
   */
  half_hour: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 6 blocks.
   */
  hour: number;
};

export type HolderRef =
  | { "XOnlyPubkey": string }
  | { "SignerId": bigint }
  | "Core"
  | "Burner"
  | { "Utxo": OutPoint };

export type Info = {
  version: string;
  target: string;
  network: string;
  available: boolean;
  consensus_mode: ConsensusMode;
  height: number;
  checkpoint: string | null;
  consensus_height: number | null;
};

export type Input = {
  previous_output: string;
  input_index: number;
  x_only_pubkey: string;
  insts: Insts;
};

export type Inst =
  | {
    "Publish": { payment: PaymentIntent; name: string; bytes: Array<number> };
  }
  | {
    "Call": {
      payment: PaymentIntent;
      contract: string;
      nonce: number | null;
      expr: string;
    };
  }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  };

export type InstructionQuery = {
  address: string;
  x_only_public_key: string;
  funding_utxo_ids: string;
  insts: Insts;
  chained_insts: Insts | null;
};

export type Insts = { ops: Array<Inst>; aggregate: AggregateInfo | null };

export type Op =
  | {
    "Publish": {
      metadata: OpMetadata;
      payment: Payment;
      name: string;
      bytes: Array<number>;
    };
  }
  | {
    "Call": {
      metadata: OpMetadata;
      payment: Payment;
      contract: string;
      nonce: number | null;
      expr: string;
    };
  }
  | { "Issuance": { metadata: OpMetadata } }
  | {
    "RegisterBlsKey": {
      metadata: OpMetadata;
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  };

export type OpMetadata = {
  previous_output: string;
  input_index: number;
  signer_id: number;
};

export type OpWithResult = { op: Op; result: ResultRow | null };

export type OutPoint = { txid: string; vout: bigint };

export type PaginatedResponse<T> = {
  results: Array<T>;
  pagination: PaginationMeta;
};

export type PaginationMeta = {
  next_cursor?: string;
  next_offset: number | null;
  has_more: boolean;
  total_count: number;
};

export type ParticipantScripts = {
  address: string;
  x_only_public_key: string;
  commit_tap_leaf_script: TapLeafScript;
  chained_tap_leaf_script: TapLeafScript | null;
};

/**
 * Resolved per-op execution payment for `Op::Publish` and `Op::Call`.
 *
 * Built from the co-signer's `PaymentIntent` plus any aggregate-level
 * `publisher_sponsorship` offer. `signer_id` identifies who funds the
 * op's gas (the applicative signer for SelfPay, the publisher for
 * Sponsored). `gas_limit` is the effective fuel cap for execution.
 *
 * System-paid ops (`Issuance`, `RegisterBlsKey`) don't carry a `Payment`
 * — their gas is set by the runtime at the call site.
 */
export type Payment = { signer_id: number; gas_limit: number };

/**
 * Co-signer's payment commitment, signed as part of the Inst.
 *
 * - `SelfPay { limit }`: the co-signer commits up to `limit` from their own
 *   token balance for this op's gas.
 * - `Sponsored`: the co-signer accepts publisher-paid gas. Only meaningful
 *   in BLS aggregate inputs that also carry `AggregateInfo.publisher_sponsorship`;
 *   rejected at validation in any other context.
 */
export type PaymentIntent = { "SelfPay": { limit: number } } | "Sponsored";

export type ResultResponse<T> = { result: T };

export type ResultRow = {
  id: number;
  height: number;
  tx_index: number | null;
  input_index: number | null;
  op_index: number | null;
  result_index: number;
  func: string;
  gas: number;
  value: string | null;
  contract: string;
  txid: string | null;
  signer_id: number;
  /**
   * Who funded gas for this op. Equals `signer_id` for self-pay ops;
   * for BLS-aggregate sponsored ops it's the publisher's signer_id.
   * `null` for ops that don't go through user-side gas accounting.
   */
  payer_signer_id: number | null;
};

export type RevealInputs = {
  commit_tx: string;
  fee_rate: number;
  participants: Array<RevealParticipantInputs>;
  op_return_data: Array<number> | null;
  envelope: number;
};

export type RevealOutputs = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  participants: Array<ParticipantScripts>;
};

export type RevealParticipantInputs = {
  address: string;
  x_only_public_key: string;
  commit_outpoint: string;
  commit_prevout: TxOutSchema;
  commit_tap_leaf_script: TapLeafScript;
  chained_instruction: Array<number> | null;
};

export type RevealParticipantQuery = {
  address: string;
  x_only_public_key: string;
  commit_vout: number;
  commit_script_data: Array<number>;
  chained_instruction: Array<number> | null;
};

export type RevealQuery = {
  commit_tx_hex: string;
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  participants: Array<RevealParticipantQuery>;
  op_return_data: Array<number> | null;
  envelope: number | null;
};

export type SignerResponse = {
  signer_id: number;
  x_only_pubkey: string | null;
  bls_pubkey: Array<number> | null;
  next_nonce: number | null;
};

export type TapLeafScript = {
  leafVersion: number;
  script: string;
  controlBlock: string;
};

export type Transaction = {
  txid: string;
  index: number;
  inputs: Array<Input>;
  op_return_data: Record<number, OpReturnData>;
};

export type TransactionHex = { hex: string };

export type TransactionRow = {
  id: number;
  txid: string;
  height: number;
  confirmed_height: number | null;
  tx_index: number | null;
  batch_height: number | null;
};

export type TxOutSchema = { value: number; script_pubkey: string };

export type ViewExpr = { expr: string };

export type ViewResult = { "type": "Ok"; value: string } | {
  "type": "Err";
  message: string;
};

export type WsRequest = never;

export type WsResponse = { "type": "Event"; event: Event } | {
  "type": "Error";
  error: string;
};
