// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregateInfo = {
  signer_ids: Array<bigint>;
  signature: Array<number>;
};

export type Block = {
  height: number;
  hash: string;
  prev_hash: string;
  transactions: Array<Transaction>;
};

export type BlockRow = { height: number; hash: string; relevant: boolean };

export type CommitOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_inputs: RevealInputs;
};

export type ComposeOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_transaction: string;
  reveal_transaction_hex: string;
  reveal_psbt_hex: string;
  per_participant: Array<ParticipantScripts>;
};

export type ComposeQuery = {
  instructions: Array<InstructionQuery>;
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  envelope: number | null;
};

export type ContractListRow = {
  id: number;
  name: string;
  height: number;
  tx_index: number;
  size: number;
};

export type ContractResponse = { wit: string };

export type ErrorResponse = { error: string };

export type Event =
  | { "type": "Processed"; block: BlockRow; txids: Array<string> }
  | { "type": "BatchProcessed"; txids: Array<string> }
  | { "type": "Rolledback"; height: number };

export type Fees = {
  /**
   * Recommended fee rate (sat/vB) to land in the next ~1 block.
   */
  fastest: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 3 blocks.
   */
  half_hour: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 6 blocks.
   */
  hour: number;
};

export type HolderRef =
  | { "XOnlyPubkey": string }
  | { "SignerId": bigint }
  | "Core"
  | "Burner"
  | { "Utxo": OutPoint };

export type Info = {
  version: string;
  target: string;
  network: string;
  available: boolean;
  height: number;
  checkpoint: string | null;
  consensus_height: number | null;
};

export type Input = {
  previous_output: string;
  input_index: number;
  x_only_pubkey: string;
  insts: Insts;
};

export type Inst =
  | { "Publish": { gas_limit: number; name: string; bytes: Array<number> } }
  | {
    "Call": {
      gas_limit: number;
      contract: string;
      nonce: number | null;
      expr: string;
    };
  }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  };

export type InstructionQuery = {
  address: string;
  x_only_public_key: string;
  funding_utxo_ids: string;
  insts: Insts;
  chained_insts: Insts | null;
};

export type Insts = { ops: Array<Inst>; aggregate: AggregateInfo | null };

export type Op =
  | {
    "Publish": {
      metadata: OpMetadata;
      gas_limit: number;
      name: string;
      bytes: Array<number>;
    };
  }
  | {
    "Call": {
      metadata: OpMetadata;
      gas_limit: number;
      contract: string;
      nonce: number | null;
      expr: string;
    };
  }
  | { "Issuance": { metadata: OpMetadata } }
  | {
    "RegisterBlsKey": {
      metadata: OpMetadata;
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  };

export type OpMetadata = {
  previous_output: string;
  input_index: number;
  signer_id: number;
};

export type OpWithResult = { op: Op; result: ResultRow | null };

export type OutPoint = { txid: string; vout: bigint };

export type PaginatedResponse<T> = {
  results: Array<T>;
  pagination: PaginationMeta;
};

export type PaginationMeta = {
  next_cursor?: string;
  next_offset: number | null;
  has_more: boolean;
  total_count: number;
};

export type ParticipantScripts = {
  address: string;
  x_only_public_key: string;
  commit_tap_leaf_script: TapLeafScript;
  chained_tap_leaf_script: TapLeafScript | null;
};

export type ResultResponse<T> = { result: T };

export type ResultRow = {
  id: number;
  height: number;
  tx_index: number | null;
  input_index: number | null;
  op_index: number | null;
  result_index: number;
  func: string;
  gas: number;
  value: string | null;
  contract: string;
  txid: string | null;
  signer_id: number;
};

export type RevealInputs = {
  commit_tx: string;
  fee_rate: number;
  participants: Array<RevealParticipantInputs>;
  op_return_data: Array<number> | null;
  envelope: number;
};

export type RevealOutputs = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  participants: Array<ParticipantScripts>;
};

export type RevealParticipantInputs = {
  address: string;
  x_only_public_key: string;
  commit_outpoint: string;
  commit_prevout: TxOutSchema;
  commit_tap_leaf_script: TapLeafScript;
  chained_instruction: Array<number> | null;
};

export type RevealParticipantQuery = {
  address: string;
  x_only_public_key: string;
  commit_vout: number;
  commit_script_data: Array<number>;
  chained_instruction: Array<number> | null;
};

export type RevealQuery = {
  commit_tx_hex: string;
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  participants: Array<RevealParticipantQuery>;
  op_return_data: Array<number> | null;
  envelope: number | null;
};

export type SignerResponse = {
  signer_id: number;
  x_only_pubkey: string | null;
  bls_pubkey: Array<number> | null;
  next_nonce: number | null;
};

export type TapLeafScript = {
  leafVersion: number;
  script: string;
  controlBlock: string;
};

export type Transaction = {
  txid: string;
  index: number;
  inputs: Array<Input>;
  op_return_data: Record<number, OpReturnData>;
};

export type TransactionHex = { hex: string };

export type TransactionRow = {
  id: number;
  txid: string;
  height: number;
  confirmed_height: number | null;
  tx_index: number | null;
  batch_height: number | null;
};

export type TxOutSchema = { value: number; script_pubkey: string };

export type ViewExpr = { expr: string };

export type ViewResult = { "type": "Ok"; value: string } | {
  "type": "Err";
  message: string;
};

export type WsRequest = never;

export type WsResponse = { "type": "Event"; event: Event } | {
  "type": "Error";
  error: string;
};
