//! uniffi wrapper over `kontor-sdk`, producing the native (iOS/Android)
//! backend for `@kontor/sdk-native`. Every exported symbol delegates to
//! `kontor_sdk::*` so the on-device bytes are identical to the WASM path.
//!
//! Bindings are generated by `uniffi-bindgen-react-native` from this crate
//! (a synchronous JSI Turbo Module). That toolchain is not run here — this
//! crate is only `cargo check`ed natively; the iOS/Android/uniffi-bindgen
//! toolchains are absent in this environment.

use std::sync::Arc;

use kontor_sdk::numerics as core_numerics;

uniffi::setup_scaffolding!();

// ─── error types ─────────────────────────────────────────────────────

/// Wraps the plain `String` errors the core returns so they cross the
/// uniffi FFI as a proper error type. `flat_error` sends the `Display`
/// output across the FFI, so the JS error `.message` carries the
/// descriptive text — same surface the WASM backend exposes.
#[derive(Debug, uniffi::Error)]
#[uniffi(flat_error)]
pub enum CoreError {
    Message(String),
}

impl std::fmt::Display for CoreError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CoreError::Message(s) => write!(f, "{s}"),
        }
    }
}

impl std::error::Error for CoreError {}

/// Mirror of `kontor_sdk::numerics::Error` as a uniffi error. Also
/// `flat_error`: JS still gets one class per variant to branch on, but
/// `.message` is the underlying description instead of "NumericsError.X".
#[derive(Debug, uniffi::Error)]
#[uniffi(flat_error)]
pub enum NumericsError {
    Message(String),
    Overflow(String),
    DivByZero(String),
    Syntax(String),
    Validation(String),
}

impl std::fmt::Display for NumericsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NumericsError::Message(s)
            | NumericsError::Overflow(s)
            | NumericsError::DivByZero(s)
            | NumericsError::Syntax(s)
            | NumericsError::Validation(s) => write!(f, "{s}"),
        }
    }
}

impl std::error::Error for NumericsError {}

impl From<core_numerics::Error> for NumericsError {
    fn from(e: core_numerics::Error) -> Self {
        match e {
            core_numerics::Error::Message(s) => NumericsError::Message(s),
            core_numerics::Error::Overflow(s) => NumericsError::Overflow(s),
            core_numerics::Error::DivByZero(s) => NumericsError::DivByZero(s),
            core_numerics::Error::Syntax(s) => NumericsError::Syntax(s),
            core_numerics::Error::Validation(s) => NumericsError::Validation(s),
        }
    }
}

fn map_err(s: String) -> CoreError {
    CoreError::Message(s)
}

// ─── runtime free functions (delegate to kontor_sdk) ────────────────

#[uniffi::export]
pub fn serialize_inst(json_str: String) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::serialize_inst(json_str).map_err(map_err)
}

#[uniffi::export]
pub fn deserialize_inst(bytes: Vec<u8>) -> Result<String, CoreError> {
    kontor_sdk::deserialize_inst(bytes).map_err(map_err)
}

#[uniffi::export]
pub fn bls_secret_key_gen(ikm: Vec<u8>) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::bls_secret_key_gen(ikm).map_err(map_err)
}

#[uniffi::export]
pub fn bls_secret_from_seed_eip2333(seed: Vec<u8>, path: Vec<u32>) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::bls_secret_from_seed_eip2333(seed, path).map_err(map_err)
}

#[uniffi::export]
pub fn bls_pubkey_from_secret(secret: Vec<u8>) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::bls_pubkey_from_secret(secret).map_err(map_err)
}

#[uniffi::export]
pub fn bls_sign(secret: Vec<u8>, message: Vec<u8>) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::bls_sign(secret, message).map_err(map_err)
}

#[uniffi::export]
pub fn bls_verify(
    pubkey: Vec<u8>,
    message: Vec<u8>,
    signature: Vec<u8>,
) -> Result<bool, CoreError> {
    kontor_sdk::bls_verify(pubkey, message, signature).map_err(map_err)
}

#[uniffi::export]
pub fn aggregate_signing_message(
    claim_json: String,
    nonce: u64,
    sponsored: bool,
    inst_json: String,
) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::aggregate_signing_message(claim_json, nonce, sponsored, inst_json).map_err(map_err)
}

#[uniffi::export]
pub fn bls_aggregate_signatures(signatures: Vec<Vec<u8>>) -> Result<Vec<u8>, CoreError> {
    kontor_sdk::bls_aggregate_signatures(signatures).map_err(map_err)
}

// ─── Wit codec (interface object) ────────────────────────────────────

/// One instance per WIT document. Wraps the pure `kontor_sdk::WitResource`.
#[derive(uniffi::Object)]
pub struct Wit {
    inner: WitResource,
}

use kontor_sdk::WitResource;

#[uniffi::export]
impl Wit {
    #[uniffi::constructor]
    pub fn new(text: String) -> Arc<Self> {
        Arc::new(Self {
            inner: WitResource::new(text),
        })
    }

    pub fn encode_call(&self, fn_name: String, args_json: String) -> Result<String, CoreError> {
        self.inner.encode_call(fn_name, args_json).map_err(map_err)
    }

    pub fn decode_result(&self, fn_name: String, wave: String) -> Result<String, CoreError> {
        self.inner.decode_result(fn_name, wave).map_err(map_err)
    }
}

// ─── numerics: plain records + free-function ops ─────────────────────

#[derive(uniffi::Enum, Clone, Copy)]
pub enum Sign {
    Plus,
    Minus,
}

#[derive(uniffi::Enum, Clone, Copy)]
pub enum Ordering {
    Less,
    Equal,
    Greater,
}

#[derive(uniffi::Record, Clone, Copy)]
pub struct Integer {
    pub r0: u64,
    pub r1: u64,
    pub r2: u64,
    pub r3: u64,
    pub sign: Sign,
}

#[derive(uniffi::Record, Clone, Copy)]
pub struct Decimal {
    pub r0: u64,
    pub r1: u64,
    pub r2: u64,
    pub r3: u64,
    pub sign: Sign,
}

// ── type bridges: mobile records ↔ shared crate ──

impl From<Sign> for core_numerics::Sign {
    fn from(s: Sign) -> Self {
        match s {
            Sign::Plus => core_numerics::Sign::Plus,
            Sign::Minus => core_numerics::Sign::Minus,
        }
    }
}

impl From<core_numerics::Sign> for Sign {
    fn from(s: core_numerics::Sign) -> Self {
        match s {
            core_numerics::Sign::Plus => Sign::Plus,
            core_numerics::Sign::Minus => Sign::Minus,
        }
    }
}

impl From<core_numerics::Ordering> for Ordering {
    fn from(o: core_numerics::Ordering) -> Self {
        match o {
            core_numerics::Ordering::Less => Ordering::Less,
            core_numerics::Ordering::Equal => Ordering::Equal,
            core_numerics::Ordering::Greater => Ordering::Greater,
        }
    }
}

/// Bridges a mobile record to/from its field-identical `core_numerics`
/// counterpart (`{r0..r3, sign}`).
macro_rules! bridge_record {
    ($t:ident) => {
        impl From<$t> for core_numerics::$t {
            fn from(v: $t) -> Self {
                core_numerics::$t {
                    r0: v.r0,
                    r1: v.r1,
                    r2: v.r2,
                    r3: v.r3,
                    sign: v.sign.into(),
                }
            }
        }

        impl From<core_numerics::$t> for $t {
            fn from(v: core_numerics::$t) -> Self {
                $t {
                    r0: v.r0,
                    r1: v.r1,
                    r2: v.r2,
                    r3: v.r3,
                    sign: v.sign.into(),
                }
            }
        }
    };
}

bridge_record!(Integer);
bridge_record!(Decimal);

// ── op tables ──
//
// Every op is `core_numerics::<same name>` with args and result bridged
// through the `From` impls above, so one declaration per op is enough.
// Adding an op = one line here (uniffi picks the export up from the
// macro expansion; the generated TS bindings are drift-gated in CI).

/// Infallible ops: `core_numerics::$name(args…).into()`.
macro_rules! numerics_fns {
    ($($name:ident($($arg:ident: $ty:ty),*) -> $ret:ty;)*) => {$(
        #[uniffi::export]
        pub fn $name($($arg: $ty),*) -> $ret {
            core_numerics::$name($($arg.into()),*).into()
        }
    )*};
}

/// Fallible ops: same, with `Result` ok/err both bridged.
macro_rules! numerics_try_fns {
    ($($name:ident($($arg:ident: $ty:ty),*) -> $ok:ty;)*) => {$(
        #[uniffi::export]
        pub fn $name($($arg: $ty),*) -> Result<$ok, NumericsError> {
            core_numerics::$name($($arg.into()),*)
                .map(Into::into)
                .map_err(Into::into)
        }
    )*};
}

numerics_fns! {
    u64_to_integer(i: u64) -> Integer;
    s64_to_integer(i: i64) -> Integer;
    integer_to_string(i: Integer) -> String;
    eq_integer(a: Integer, b: Integer) -> bool;
    cmp_integer(a: Integer, b: Integer) -> Ordering;
    decimal_to_string(d: Decimal) -> String;
    cmp_decimal(a: Decimal, b: Decimal) -> Ordering;
}

numerics_try_fns! {
    add_integer(a: Integer, b: Integer) -> Integer;
    sub_integer(a: Integer, b: Integer) -> Integer;
    mul_integer(a: Integer, b: Integer) -> Integer;
    div_integer(a: Integer, b: Integer) -> Integer;
    sqrt_integer(i: Integer) -> Integer;
    integer_to_decimal(i: Integer) -> Decimal;
    decimal_to_integer(d: Decimal) -> Integer;
    u64_to_decimal(i: u64) -> Decimal;
    s64_to_decimal(i: i64) -> Decimal;
    f64_to_decimal(f: f64) -> Decimal;
    eq_decimal(a: Decimal, b: Decimal) -> bool;
    add_decimal(a: Decimal, b: Decimal) -> Decimal;
    sub_decimal(a: Decimal, b: Decimal) -> Decimal;
    mul_decimal(a: Decimal, b: Decimal) -> Decimal;
    div_decimal(a: Decimal, b: Decimal) -> Decimal;
    log10_decimal(a: Decimal) -> Decimal;
}

// The two `&str`-taking core fns don't fit the `.into()` bridging above
// (String → &str isn't `Into`), so they stay hand-written.

#[uniffi::export]
pub fn string_to_integer(s: String) -> Result<Integer, NumericsError> {
    core_numerics::string_to_integer(&s)
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn string_to_decimal(s: String) -> Result<Decimal, NumericsError> {
    core_numerics::string_to_decimal(&s)
        .map(Into::into)
        .map_err(Into::into)
}
