package root:component;

world root {
  include kontor:built-in/built-in-native;
  use kontor:built-in/context.{view-context, proc-context, contract};

  export init: async func(ctx: borrow<proc-context>) -> contract;
  export registered: async func(ctx: borrow<proc-context>);
  export provenance-updated: async func(ctx: borrow<proc-context>);
}
