//! uniffi wrapper over `kontor-core`, producing the native (iOS/Android)
//! backend for `@kontor/sdk-native`. Every exported symbol delegates to
//! `kontor_core::*` so the on-device bytes are identical to the WASM path.
//!
//! Bindings are generated by `uniffi-bindgen-react-native` from this crate
//! (a synchronous JSI Turbo Module). That toolchain is not run here — this
//! crate is only `cargo check`ed natively; the iOS/Android/uniffi-bindgen
//! toolchains are absent in this environment.

use std::sync::Arc;

use kontor_core::numerics as core_numerics;

uniffi::setup_scaffolding!();

// ─── error types ─────────────────────────────────────────────────────

/// Wraps the plain `String` errors the core returns so they cross the
/// uniffi FFI as a proper error type.
#[derive(Debug, uniffi::Error)]
pub enum CoreError {
    Message(String),
}

impl std::fmt::Display for CoreError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CoreError::Message(s) => write!(f, "{s}"),
        }
    }
}

impl std::error::Error for CoreError {}

/// Mirror of `kontor_core::numerics::Error` as a uniffi error.
#[derive(Debug, uniffi::Error)]
pub enum NumericsError {
    Message(String),
    Overflow(String),
    DivByZero(String),
    Syntax(String),
    Validation(String),
}

impl std::fmt::Display for NumericsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NumericsError::Message(s)
            | NumericsError::Overflow(s)
            | NumericsError::DivByZero(s)
            | NumericsError::Syntax(s)
            | NumericsError::Validation(s) => write!(f, "{s}"),
        }
    }
}

impl std::error::Error for NumericsError {}

impl From<core_numerics::Error> for NumericsError {
    fn from(e: core_numerics::Error) -> Self {
        match e {
            core_numerics::Error::Message(s) => NumericsError::Message(s),
            core_numerics::Error::Overflow(s) => NumericsError::Overflow(s),
            core_numerics::Error::DivByZero(s) => NumericsError::DivByZero(s),
            core_numerics::Error::Syntax(s) => NumericsError::Syntax(s),
            core_numerics::Error::Validation(s) => NumericsError::Validation(s),
        }
    }
}

fn map_err(s: String) -> CoreError {
    CoreError::Message(s)
}

// ─── runtime free functions (delegate to kontor_core) ────────────────

#[uniffi::export]
pub fn serialize_inst(json_str: String) -> Result<Vec<u8>, CoreError> {
    kontor_core::serialize_inst(json_str).map_err(map_err)
}

#[uniffi::export]
pub fn deserialize_inst(bytes: Vec<u8>) -> Result<String, CoreError> {
    kontor_core::deserialize_inst(bytes).map_err(map_err)
}

#[uniffi::export]
pub fn bls_secret_key_gen(ikm: Vec<u8>) -> Result<Vec<u8>, CoreError> {
    kontor_core::bls_secret_key_gen(ikm).map_err(map_err)
}

#[uniffi::export]
pub fn bls_secret_from_seed_eip2333(seed: Vec<u8>, path: Vec<u32>) -> Result<Vec<u8>, CoreError> {
    kontor_core::bls_secret_from_seed_eip2333(seed, path).map_err(map_err)
}

#[uniffi::export]
pub fn bls_pubkey_from_secret(secret: Vec<u8>) -> Result<Vec<u8>, CoreError> {
    kontor_core::bls_pubkey_from_secret(secret).map_err(map_err)
}

#[uniffi::export]
pub fn bls_sign(secret: Vec<u8>, message: Vec<u8>) -> Result<Vec<u8>, CoreError> {
    kontor_core::bls_sign(secret, message).map_err(map_err)
}

#[uniffi::export]
pub fn bls_verify(
    pubkey: Vec<u8>,
    message: Vec<u8>,
    signature: Vec<u8>,
) -> Result<bool, CoreError> {
    kontor_core::bls_verify(pubkey, message, signature).map_err(map_err)
}

#[uniffi::export]
pub fn aggregate_signing_message(
    claim_json: String,
    nonce: u64,
    sponsored: bool,
    inst_json: String,
) -> Result<Vec<u8>, CoreError> {
    kontor_core::aggregate_signing_message(claim_json, nonce, sponsored, inst_json).map_err(map_err)
}

#[uniffi::export]
pub fn bls_aggregate_signatures(signatures: Vec<Vec<u8>>) -> Result<Vec<u8>, CoreError> {
    kontor_core::bls_aggregate_signatures(signatures).map_err(map_err)
}

// ─── Wit codec (interface object) ────────────────────────────────────

/// One instance per WIT document. Wraps the pure `kontor_core::WitResource`.
#[derive(uniffi::Object)]
pub struct Wit {
    inner: WitResource,
}

use kontor_core::WitResource;

#[uniffi::export]
impl Wit {
    #[uniffi::constructor]
    pub fn new(text: String) -> Arc<Self> {
        Arc::new(Self {
            inner: WitResource::new(text),
        })
    }

    pub fn encode_call(&self, fn_name: String, args_json: String) -> Result<String, CoreError> {
        self.inner.encode_call(fn_name, args_json).map_err(map_err)
    }

    pub fn decode_result(&self, fn_name: String, wave: String) -> Result<String, CoreError> {
        self.inner.decode_result(fn_name, wave).map_err(map_err)
    }
}

// ─── numerics: plain records + free-function ops ─────────────────────

#[derive(uniffi::Enum, Clone, Copy)]
pub enum Sign {
    Plus,
    Minus,
}

#[derive(uniffi::Enum, Clone, Copy)]
pub enum Ordering {
    Less,
    Equal,
    Greater,
}

#[derive(uniffi::Record, Clone, Copy)]
pub struct Integer {
    pub r0: u64,
    pub r1: u64,
    pub r2: u64,
    pub r3: u64,
    pub sign: Sign,
}

#[derive(uniffi::Record, Clone, Copy)]
pub struct Decimal {
    pub r0: u64,
    pub r1: u64,
    pub r2: u64,
    pub r3: u64,
    pub sign: Sign,
}

// ── type bridges: mobile records ↔ shared crate ──

impl From<Sign> for core_numerics::Sign {
    fn from(s: Sign) -> Self {
        match s {
            Sign::Plus => core_numerics::Sign::Plus,
            Sign::Minus => core_numerics::Sign::Minus,
        }
    }
}

impl From<core_numerics::Sign> for Sign {
    fn from(s: core_numerics::Sign) -> Self {
        match s {
            core_numerics::Sign::Plus => Sign::Plus,
            core_numerics::Sign::Minus => Sign::Minus,
        }
    }
}

impl From<core_numerics::Ordering> for Ordering {
    fn from(o: core_numerics::Ordering) -> Self {
        match o {
            core_numerics::Ordering::Less => Ordering::Less,
            core_numerics::Ordering::Equal => Ordering::Equal,
            core_numerics::Ordering::Greater => Ordering::Greater,
        }
    }
}

impl From<Integer> for core_numerics::Integer {
    fn from(i: Integer) -> Self {
        core_numerics::Integer {
            r0: i.r0,
            r1: i.r1,
            r2: i.r2,
            r3: i.r3,
            sign: i.sign.into(),
        }
    }
}

impl From<core_numerics::Integer> for Integer {
    fn from(i: core_numerics::Integer) -> Self {
        Integer {
            r0: i.r0,
            r1: i.r1,
            r2: i.r2,
            r3: i.r3,
            sign: i.sign.into(),
        }
    }
}

impl From<Decimal> for core_numerics::Decimal {
    fn from(d: Decimal) -> Self {
        core_numerics::Decimal {
            r0: d.r0,
            r1: d.r1,
            r2: d.r2,
            r3: d.r3,
            sign: d.sign.into(),
        }
    }
}

impl From<core_numerics::Decimal> for Decimal {
    fn from(d: core_numerics::Decimal) -> Self {
        Decimal {
            r0: d.r0,
            r1: d.r1,
            r2: d.r2,
            r3: d.r3,
            sign: d.sign.into(),
        }
    }
}

// ── Integer ops ──

#[uniffi::export]
pub fn u64_to_integer(i: u64) -> Integer {
    core_numerics::u64_to_integer(i).into()
}

#[uniffi::export]
pub fn s64_to_integer(i: i64) -> Integer {
    core_numerics::s64_to_integer(i).into()
}

#[uniffi::export]
pub fn string_to_integer(s: String) -> Result<Integer, NumericsError> {
    core_numerics::string_to_integer(&s)
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn integer_to_string(i: Integer) -> String {
    core_numerics::integer_to_string(i.into())
}

#[uniffi::export]
pub fn eq_integer(a: Integer, b: Integer) -> bool {
    core_numerics::eq_integer(a.into(), b.into())
}

#[uniffi::export]
pub fn cmp_integer(a: Integer, b: Integer) -> Ordering {
    core_numerics::cmp_integer(a.into(), b.into()).into()
}

#[uniffi::export]
pub fn add_integer(a: Integer, b: Integer) -> Result<Integer, NumericsError> {
    core_numerics::add_integer(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn sub_integer(a: Integer, b: Integer) -> Result<Integer, NumericsError> {
    core_numerics::sub_integer(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn mul_integer(a: Integer, b: Integer) -> Result<Integer, NumericsError> {
    core_numerics::mul_integer(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn div_integer(a: Integer, b: Integer) -> Result<Integer, NumericsError> {
    core_numerics::div_integer(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn sqrt_integer(i: Integer) -> Result<Integer, NumericsError> {
    core_numerics::sqrt_integer(i.into())
        .map(Into::into)
        .map_err(Into::into)
}

// ── Integer ↔ Decimal conversions ──

#[uniffi::export]
pub fn integer_to_decimal(i: Integer) -> Result<Decimal, NumericsError> {
    core_numerics::integer_to_decimal(i.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn decimal_to_integer(d: Decimal) -> Result<Integer, NumericsError> {
    core_numerics::decimal_to_integer(d.into())
        .map(Into::into)
        .map_err(Into::into)
}

// ── Decimal ops ──

#[uniffi::export]
pub fn u64_to_decimal(i: u64) -> Result<Decimal, NumericsError> {
    core_numerics::u64_to_decimal(i)
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn s64_to_decimal(i: i64) -> Result<Decimal, NumericsError> {
    core_numerics::s64_to_decimal(i)
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn f64_to_decimal(f: f64) -> Result<Decimal, NumericsError> {
    core_numerics::f64_to_decimal(f)
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn string_to_decimal(s: String) -> Result<Decimal, NumericsError> {
    core_numerics::string_to_decimal(&s)
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn decimal_to_string(d: Decimal) -> String {
    core_numerics::decimal_to_string(d.into())
}

#[uniffi::export]
pub fn eq_decimal(a: Decimal, b: Decimal) -> Result<bool, NumericsError> {
    core_numerics::eq_decimal(a.into(), b.into()).map_err(Into::into)
}

#[uniffi::export]
pub fn cmp_decimal(a: Decimal, b: Decimal) -> Ordering {
    core_numerics::cmp_decimal(a.into(), b.into()).into()
}

#[uniffi::export]
pub fn add_decimal(a: Decimal, b: Decimal) -> Result<Decimal, NumericsError> {
    core_numerics::add_decimal(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn sub_decimal(a: Decimal, b: Decimal) -> Result<Decimal, NumericsError> {
    core_numerics::sub_decimal(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn mul_decimal(a: Decimal, b: Decimal) -> Result<Decimal, NumericsError> {
    core_numerics::mul_decimal(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn div_decimal(a: Decimal, b: Decimal) -> Result<Decimal, NumericsError> {
    core_numerics::div_decimal(a.into(), b.into())
        .map(Into::into)
        .map_err(Into::into)
}

#[uniffi::export]
pub fn log10_decimal(a: Decimal) -> Result<Decimal, NumericsError> {
    core_numerics::log10_decimal(a.into())
        .map(Into::into)
        .map_err(Into::into)
}
