// Generated by uniffi-bindgen-react-native
package com.kontor.sdknative

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = KontorSdkNativeModule.NAME)
class KontorSdkNativeModule(reactContext: ReactApplicationContext) :
  NativeKontorSdkNativeSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // kontor-sdk-native.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "KontorSdkNative"

    init {
      // The Rust core ships as a standalone shared library that the JSI
      // adapter (libkontor-sdk-native.so) links against dynamically. Load it
      // into the process first so the adapter's dependency is already
      // resolved when we load it next.
      System.loadLibrary("kontor_sdk_native")
      System.loadLibrary("kontor-sdk-native")
    }
  }
}