// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "kontor-mobile.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface KontorMobile : NSObject <NativeKontorMobileSpec>
#else
#import <React/RCTBridgeModule.h>

@interface KontorMobile : NSObject <RCTBridgeModule>
#endif

@end