// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "kontor-sdk-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface KontorSdkNative : NSObject <NativeKontorSdkNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface KontorSdkNative : NSObject <RCTBridgeModule>
#endif

@end