#![no_std]
contract!(
    name = "filestorage",
    indexed = "agreement-data.active, challenge-data.status"
);

use alloc::collections::BTreeSet;
use stdlib::*;

// ─────────────────────────────────────────────────────────────────
// Protocol Constants
// ─────────────────────────────────────────────────────────────────

/// Minimum number of storage nodes required for an agreement to be active
const DEFAULT_MIN_NODES: u64 = 3;

/// Number of blocks a storage node has to respond to a challenge (~2 weeks at 10 min/block)
const DEFAULT_CHALLENGE_DEADLINE_BLOCKS: u64 = 2016;

/// Target challenges per file per year
const DEFAULT_C_TARGET: u64 = 12;

/// Default Bitcoin blocks per year - ~52560 at 10 min/block
const DEFAULT_BLOCKS_PER_YEAR: u64 = 52560;

/// Number of sectors/symbols sampled per challenge
const DEFAULT_S_CHAL: u64 = 100;

/// Challenge count on regtest. The PoR prover (a Nova recursive SNARK) costs
/// roughly linearly in this count; a small value keeps proof generation fast on
/// the dev network and in tests. Soundness only matters on real networks, so
/// signet/testnet/mainnet keep `DEFAULT_S_CHAL`.
const REGTEST_S_CHAL: u64 = 8;

// ─────────────────────────────────────────────────────────────────
// STORAGE INDEX MODEL
//
// `IndexedMap` = a primary `Map<K, V>` plus framework-maintained secondary
// indexes (sibling `<map>#idx/...` rows — ordinary contract_state, so versioned,
// reorg-safe, checkpoint-covered). The bookkeeping lives in stdlib (audited
// once), not hand-rolled here.
//
//   agreements            indexed by `active` → where_active(true)
//   challenges            indexed by `status` → where_status(ChallengeStatus::Active)
//   agreement_nodes.nodes indexed by `active` → where_active(true)
//                                               (per agreement; nested IndexedMap)
//
// This collapses every former scan — expire's full challenge scan, generation's
// nested challenge×agreement scan, get_active_challenges' full scan, and the
// per-agreement active-node scan-and-filter — to indexed prefix reads over just
// the live subset. The `where_<field>(value)` lookups are typed: the method name
// is the index and the argument is the field's real type (no stringly-typed
// name or key), generated by the value's `Indexed` derive. For the WIT records
// (`agreement-data`/`challenge-data`) `#[index]` + `#[derive(Indexed)]` are
// injected by the `indexed = "..."` arg on `contract!` (forked wit-bindgen);
// internal structs (`NodeState`) carry `#[index]` directly.
//
// `set`/`remove` maintain the index, AND an in-place indexed-field setter does
// too (`get(&k).set_status(...)` / `set_active(...)` reconcile the bucket) — so
// no load→mutate→set dance. Departed/terminal rows move to the off bucket
// (`active/false`, `status/expired`…), out of the live scan but kept for history.
//
// Deferred (single-field index suffices today): partial/`filter` indexes,
// composite `(status, deadline_height)` sortable sweep, covering indexes (avoid
// the where_*→get N reads), and flattening `agreement_nodes` to a tuple-keyed
// `memberships` IndexedMap. See the upgrade backlog.
// ─────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────
// State Types
// ─────────────────────────────────────────────────────────────────

/// A node's membership in an agreement. Internal (non-WIT), so its `active`
/// flag is indexed with a plain `#[index]` — `nodes.where_active(true)`
/// returns the agreement's live members directly. Departed nodes keep an entry
/// with `active = false`; they sit in the `active/false` bucket and never
/// pollute the active scan.
#[derive(Clone, Default, Storage, Indexed)]
struct NodeState {
    #[index]
    pub active: bool,
}

#[derive(Clone, Default, Storage)]
struct AgreementNodes {
    /// signer_id -> membership. The node identity is the joining signer, so the
    /// key is its u64 signer_id. Indexed by `active` so live-member lookup is a
    /// prefix scan, not a scan-and-filter over every node that ever joined.
    pub nodes: IndexedMap<u64, NodeState>,
    pub node_count: u64,
}

#[derive(Clone, Default, StorageRoot)]
struct ProtocolState {
    pub min_nodes: u64,
    pub challenge_deadline_blocks: u64,
    pub c_target: u64,
    pub s_chal: u64,
    pub blocks_per_year: u64,
    pub agreements: IndexedMap<String, AgreementData>,
    pub agreement_nodes: Map<String, AgreementNodes>,
    pub agreement_count: u64,
    pub challenges: IndexedMap<String, ChallengeData>,
}

// `agreement-data`/`challenge-data` are indexed (by `active`/`status`) via the
// `indexed = "..."` arg on `contract!`, which injects `#[index]` +
// `#[derive(Indexed)]` onto the WIT records (forked wit-bindgen) — so their
// `Indexed` impls and index-aware setters are generated, not hand-written.
// `challenge-status` (like every enum the contract defines) automatically gets
// the `StorageEnum` machinery generated by `contract!` — its `IndexKey` (the
// discriminant is the index-bucket key), `Display`, and the `ChallengeStatusKind`
// marker. So the bucket a `where_status(..)` lookup scans and the bucket a write
// lands in both come from one generated source and can't drift.

// ─────────────────────────────────────────────────────────────────
// Contract Implementation
// ─────────────────────────────────────────────────────────────────

/// The caller's `u64` signer_id, which is the storage-node identity. Members
/// must be registered signers (a failed challenge has to resolve to a slashable
/// stake), so a non-signer holder — core, raw pubkey, utxo — is bad input here
/// rather than a silently skipped join.
fn require_signer_id(signer: &context::Signer) -> Result<u64, Error> {
    match signer.into() {
        HolderRef::SignerId(id) => Ok(id),
        _ => Err(Error::Message(
            "caller must be a registered signer identity".to_string(),
        )),
    }
}

impl Guest for Filestorage {
    fn init(ctx: &ProcContext) -> Contract {
        // Smaller challenge count on regtest so the Nova prover stays fast for
        // the dev network and tests; production networks use the full count.
        // Self-conditioning via the `network()` built-in (cf. token dev-mint).
        let s_chal = if ctx.network().is_regtest() {
            REGTEST_S_CHAL
        } else {
            DEFAULT_S_CHAL
        };
        ProtocolState {
            min_nodes: DEFAULT_MIN_NODES,
            challenge_deadline_blocks: DEFAULT_CHALLENGE_DEADLINE_BLOCKS,
            c_target: DEFAULT_C_TARGET,
            s_chal,
            blocks_per_year: DEFAULT_BLOCKS_PER_YEAR,
            agreements: IndexedMap::default(),
            agreement_nodes: Map::default(),
            agreement_count: 0,
            challenges: IndexedMap::default(),
        }
        .init(ctx);
        ctx.contract()
    }

    fn create_agreement(
        ctx: &ProcContext,
        descriptor: RawFileDescriptor,
    ) -> Result<CreateAgreementResult, Error> {
        // Validate inputs
        if descriptor.file_id.is_empty() {
            return Err(Error::Message("file_id cannot be empty".to_string()));
        }
        if descriptor.padded_len == 0 || !descriptor.padded_len.is_power_of_two() {
            return Err(Error::Message(
                "padded_len must be a positive power of 2".to_string(),
            ));
        }

        let model = ctx.model();

        // Check for duplicate agreement
        let agreement_id = descriptor.file_id.clone();
        if model.agreements().get(&agreement_id).is_some() {
            return Err(Error::Message(format!(
                "agreement already exists for file_id: {}",
                agreement_id
            )));
        }

        // Validate and register with the FileLedger host function
        register_file_descriptor(&descriptor)?;

        // Create the agreement (starts inactive until nodes join)
        let agreement = AgreementData {
            agreement_id: agreement_id.clone(),
            file_id: descriptor.file_id.clone(),
            active: false,
            active_challenge: None,
        };

        // Store the agreement and initialize node tracking
        model.agreements().set(&agreement_id, agreement);
        model
            .agreement_nodes()
            .set(&agreement_id, AgreementNodes::default());

        // Increment count
        model.update_agreement_count(|c| c + 1);

        Ok(CreateAgreementResult { agreement_id })
    }

    fn get_agreement(ctx: &ViewContext, agreement_id: String) -> Option<AgreementData> {
        ctx.model()
            .agreements()
            .get(&agreement_id)
            .map(|a| a.load())
    }

    fn agreement_count(ctx: &ViewContext) -> u64 {
        ctx.model().agreement_count()
    }

    fn get_all_active_agreements(ctx: &ViewContext) -> Vec<AgreementData> {
        let model = ctx.model();
        model
            .agreements()
            .where_active(true)
            .filter_map(|agreement_id: String| {
                model.agreements().get(&agreement_id).map(|a| a.load())
            })
            .collect()
    }

    fn join_agreement(
        ctx: &ProcContext,
        agreement_id: String,
    ) -> Result<JoinAgreementResult, Error> {
        let model = ctx.model();

        // Membership is keyed on the joining signer's u64 signer_id, so one
        // signer holds at most one slot per agreement (enforced by the dup-check
        // below). This is a legitimacy guardrail — not a replication guarantee:
        // replication is economic, and an operator behind multiple keys is
        // undetectable by design. Keying on the signer also makes a failed
        // challenge's `prover_id` resolve to a slashable stake.
        let node_id = require_signer_id(&ctx.signer())?;

        // Validate agreement exists
        let agreement = model
            .agreements()
            .get(&agreement_id)
            .ok_or(Error::Message(format!(
                "agreement not found: {}",
                agreement_id
            )))?;
        let nodes_state = model
            .agreement_nodes()
            .get(&agreement_id)
            .ok_or(Error::Message(format!(
                "agreement nodes not found: {}",
                agreement_id
            )))?;

        // Check if node is already active in agreement
        if nodes_state
            .nodes()
            .get(&node_id)
            .map(|n| n.active())
            .unwrap_or(false)
        {
            return Err(Error::Message(format!(
                "node {} already in agreement {}",
                node_id, agreement_id
            )));
        }

        // Add node to agreement (or reactivate if previously left) — `set`
        // moves it into the `active/true` index bucket.
        nodes_state
            .nodes()
            .set(&node_id, NodeState { active: true });

        // Increment node count
        nodes_state.update_node_count(|c| c + 1);
        let node_count = nodes_state.node_count();

        // Check if we should activate (only if not already active)
        let min_nodes = model.min_nodes();
        let activated = !agreement.active() && node_count >= min_nodes;

        if activated {
            // In-place set: the `active` index is maintained automatically
            // because `agreements().get()` binds the value model to the index.
            agreement.set_active(true);
        }

        Ok(JoinAgreementResult {
            agreement_id,
            node_id,
            activated,
        })
    }

    fn leave_agreement(
        ctx: &ProcContext,
        agreement_id: String,
    ) -> Result<LeaveAgreementResult, Error> {
        let model = ctx.model();

        // Only the signer that joined can leave its own membership — auth is
        // structural now that the key is the signer's identity.
        let node_id = require_signer_id(&ctx.signer())?;

        // Validate agreement exists
        let _agreement = model
            .agreements()
            .get(&agreement_id)
            .ok_or(Error::Message(format!(
                "agreement not found: {}",
                agreement_id
            )))?;
        let nodes_state = model
            .agreement_nodes()
            .get(&agreement_id)
            .ok_or(Error::Message(format!(
                "agreement nodes not found: {}",
                agreement_id
            )))?;

        // Validate node is active in agreement
        if !nodes_state
            .nodes()
            .get(&node_id)
            .map(|n| n.active())
            .unwrap_or(false)
        {
            return Err(Error::Message(format!(
                "node {} not in agreement {}",
                node_id, agreement_id
            )));
        }

        // TODO: the storage protocol spec does not allow
        // voluntary departure when the agreement would be at/below the minimum replication
        // threshold (|N_f| <= n_min). We do not enforce that rule yet.

        // Mark node as inactive (kept as a row; `set` moves it to the
        // `active/false` index bucket, out of the live-member scan).
        nodes_state
            .nodes()
            .set(&node_id, NodeState { active: false });

        // Decrement node count
        nodes_state.update_node_count(|c| c.saturating_sub(1));

        Ok(LeaveAgreementResult {
            agreement_id,
            node_id,
        })
    }

    fn get_agreement_nodes(ctx: &ViewContext, agreement_id: String) -> Vec<NodeInfo> {
        ctx.model()
            .agreement_nodes()
            .get(&agreement_id)
            .map(|s| {
                // Return all nodes we’ve seen, including inactive ones
                let nodes = s.nodes();
                nodes
                    .keys()
                    .map(|node_id: u64| NodeInfo {
                        node_id,
                        active: nodes.get(&node_id).map(|n| n.active()).unwrap_or(false),
                    })
                    .collect()
            })
            .unwrap_or_default()
    }

    fn is_node_in_agreement(ctx: &ViewContext, agreement_id: String, node_id: u64) -> bool {
        ctx.model()
            .agreement_nodes()
            .get(&agreement_id)
            .and_then(|s| s.nodes().get(&node_id).map(|n| n.active()))
            .unwrap_or(false)
    }

    fn get_min_nodes(ctx: &ViewContext) -> u64 {
        ctx.model().min_nodes()
    }

    // ─────────────────────────────────────────────────────────────────
    // Challenge Management
    // ─────────────────────────────────────────────────────────────────

    fn get_challenge(ctx: &ViewContext, challenge_id: String) -> Option<ChallengeData> {
        ctx.model()
            .challenges()
            .get(&challenge_id)
            .map(|c| c.load())
    }

    fn get_active_challenges(ctx: &ViewContext) -> Vec<ChallengeData> {
        let model = ctx.model();
        model
            .challenges()
            .where_status(ChallengeStatus::Active)
            .filter_map(|challenge_id: String| {
                model.challenges().get(&challenge_id).map(|c| c.load())
            })
            .collect()
    }

    fn expire_challenges(ctx: &CoreContext, current_height: u64) -> u64 {
        let model = ctx.proc_context().model();
        let mut expired = 0u64;

        // Snapshot the active bucket first: `set` below moves ids out of it, and
        // mutating an index while scanning it would corrupt the lazy iteration.
        let active_ids: Vec<String> = model
            .challenges()
            .where_status(ChallengeStatus::Active)
            .collect();

        for challenge_id in active_ids {
            if let Some(challenge) = model.challenges().get(&challenge_id)
                && challenge.deadline_height() <= current_height
            {
                // In-place; the `status` index follows via the get() binding.
                challenge.set_status(ChallengeStatus::Expired);
                // The agreement is free to be challenged again.
                if let Some(agreement) = model.agreements().get(&challenge.agreement_id()) {
                    agreement.set_active_challenge(None);
                }
                expired = expired.saturating_add(1);
            }
        }
        expired
    }

    // ─────────────────────────────────────────────────────────────────
    // Challenge Generation
    // ─────────────────────────────────────────────────────────────────

    fn generate_challenges_for_block(
        ctx: &CoreContext,
        block_height: u64,
        block_hash: Vec<u8>,
    ) -> Vec<ChallengeData> {
        let model = ctx.proc_context().model();
        let mut new_challenges = Vec::new();

        // Per-block batch seed: σ_batch = HKDF_SHA256(block_hash, "KONTOR-CHAL::v1" || block_height)
        let sigma_batch = derive_batch_seed(&block_hash, block_height);

        // Eligible agreements: active (indexed) and not already challenged.
        // "Already challenged?" is a point read of the agreement's co-located
        // `active_challenge` — no scan of the active-challenge set.
        let eligible_agreement_ids: Vec<String> = model
            .agreements()
            .where_active(true)
            .filter(|aid: &String| {
                model
                    .agreements()
                    .get(aid)
                    .is_some_and(|a| a.active_challenge().is_none())
            })
            .collect();

        let total_files = eligible_agreement_ids.len();
        if total_files == 0 {
            return new_challenges;
        }

        // Derive deterministic seed from the per-block batch seed for agreement selection
        let agreement_seed = derive_stream_seed(&sigma_batch, b"agreement_selection");
        let mut rng_counter: u64 = 0;

        // Calculate expected number of challenges: θ(t) = (C_target * |F|) / B
        let c_target = model.c_target();
        let blocks_per_year = model.blocks_per_year();

        // Stochastic component: add one more challenge with probability (expected - base)
        let roll = uniform_index(
            &agreement_seed,
            &mut rng_counter,
            b"roll",
            blocks_per_year as usize,
        ) as u64;
        let num_to_challenge =
            compute_num_to_challenge(c_target, total_files, blocks_per_year, roll);

        if num_to_challenge == 0 {
            return new_challenges;
        }

        // Don't try to challenge more agreements than exist
        let num_to_challenge = core::cmp::min(num_to_challenge, total_files);

        // Select random unique agreement indices (rejection sampling avoids modulo bias)
        let mut selected_indices = BTreeSet::new();
        let eligible_len = eligible_agreement_ids.len();
        if num_to_challenge == eligible_len {
            for i in 0..eligible_len {
                selected_indices.insert(i);
            }
        } else {
            while selected_indices.len() < num_to_challenge {
                let index =
                    uniform_index(&agreement_seed, &mut rng_counter, b"select", eligible_len);
                selected_indices.insert(index);
            }
        }

        let s_chal = model.s_chal();
        let deadline_height = block_height + model.challenge_deadline_blocks();

        // Create challenges for selected agreements
        for index in selected_indices {
            let agreement_id = &eligible_agreement_ids[index];
            let agreement = match model.agreements().get(agreement_id) {
                Some(a) => a,
                None => continue,
            };

            // Get active nodes for this agreement
            let nodes_state = match model.agreement_nodes().get(agreement_id) {
                Some(s) => s,
                None => continue,
            };
            // Live members of this agreement — an indexed prefix scan, not a
            // scan-and-filter over every node that ever joined.
            let active_nodes: Vec<u64> = nodes_state.nodes().where_active(true).collect();

            if active_nodes.is_empty() {
                continue;
            }

            // Get file_id early since we need it for multiple derivations
            let file_id = agreement.file_id();

            // Deterministically select one node (agreement-level exclusion ensures we create
            // at most 1 active challenge per agreement total).
            let node_seed = derive_stream_seed_for_file(&sigma_batch, b"node_selection", &file_id);
            let mut node_counter: u64 = 0;
            let node_index =
                uniform_index(&node_seed, &mut node_counter, b"node", active_nodes.len());
            let prover_id = active_nodes[node_index];

            // Per-challenge seed used by kontor-crypto as the Challenge.seed field.
            // Derived deterministically from the per-block batch seed and the file_id.
            let challenge_seed = derive_challenge_seed_for_file(&sigma_batch, &file_id);
            let seed: Vec<u8> = challenge_seed.to_vec();

            let descriptor = match file_registry::get_file_descriptor(&file_id) {
                Some(d) => d,
                None => continue,
            };

            // Compute challenge ID via file descriptor method
            let challenge_id =
                match descriptor.compute_challenge_id(block_height, s_chal, &seed, prover_id) {
                    Ok(id) => id,
                    Err(_) => continue,
                };

            let challenge = ChallengeData {
                challenge_id,
                agreement_id: agreement_id.clone(),
                block_height,
                num_challenges: s_chal,
                seed: seed.clone(),
                prover_id,
                deadline_height,
                status: ChallengeStatus::Active,
            };
            model
                .challenges()
                .set(&challenge.challenge_id, challenge.clone());
            agreement.set_active_challenge(Some(challenge.challenge_id.clone()));

            new_challenges.push(challenge);
        }

        new_challenges
    }

    /// Create a challenge for a specific agreement and node.
    /// This is primarily for testing to avoid probabilistic challenge generation.
    fn create_challenge_for_agreement(
        ctx: &ProcContext,
        agreement_id: String,
        prover_id: u64,
        block_height: u64,
        seed: Vec<u8>,
    ) -> Result<ChallengeData, Error> {
        let model = ctx.model();

        // Validate agreement exists and is active
        let agreement = model
            .agreements()
            .get(&agreement_id)
            .ok_or(Error::Message(format!(
                "Agreement not found: {}",
                agreement_id
            )))?;

        if !agreement.active() {
            return Err(Error::Message(format!(
                "Agreement {} is not active",
                agreement_id
            )));
        }

        // Validate node is in agreement
        let nodes_state = model
            .agreement_nodes()
            .get(&agreement_id)
            .ok_or(Error::Message("No nodes for agreement".to_string()))?;

        let is_active = nodes_state
            .nodes()
            .get(&prover_id)
            .map(|n| n.active())
            .unwrap_or(false);
        if !is_active {
            return Err(Error::Message(format!(
                "Node {} is not active in agreement {}",
                prover_id, agreement_id
            )));
        }

        // No active challenge already exists for this agreement — a point read
        // of the co-located `active_challenge`, not a scan.
        if agreement.active_challenge().is_some() {
            return Err(Error::Message(format!(
                "Agreement {} already has an active challenge",
                agreement_id
            )));
        }

        // Validate seed length (64 bytes required for unbiased field element conversion)
        if seed.len() != 64 {
            return Err(Error::Message(format!(
                "Seed must be 64 bytes, got {}",
                seed.len()
            )));
        }

        let file_id = agreement.file_id();
        let s_chal = model.s_chal();
        let deadline_height = block_height + model.challenge_deadline_blocks();

        let descriptor = file_registry::get_file_descriptor(&file_id).ok_or(Error::Message(
            format!("File descriptor not found for {}", file_id),
        ))?;

        let challenge_id =
            descriptor.compute_challenge_id(block_height, s_chal, &seed, prover_id)?;

        let challenge = ChallengeData {
            challenge_id,
            agreement_id,
            block_height,
            num_challenges: s_chal,
            seed,
            prover_id,
            deadline_height,
            status: ChallengeStatus::Active,
        };

        model
            .challenges()
            .set(&challenge.challenge_id, challenge.clone());
        agreement.set_active_challenge(Some(challenge.challenge_id.clone()));

        Ok(challenge)
    }

    fn get_c_target(ctx: &ViewContext) -> u64 {
        ctx.model().c_target()
    }

    fn get_blocks_per_year(ctx: &ViewContext) -> u64 {
        ctx.model().blocks_per_year()
    }

    fn get_s_chal(ctx: &ViewContext) -> u64 {
        ctx.model().s_chal()
    }

    // ─────────────────────────────────────────────────────────────────
    // Proof Verification
    // ─────────────────────────────────────────────────────────────────

    fn verify_proof(ctx: &ProcContext, proof_bytes: Vec<u8>) -> Result<VerifyProofResult, Error> {
        let model = ctx.model();

        // 1. Deserialize proof (single deserialization via host resource)
        let proof = file_registry::Proof::from_bytes(&proof_bytes)?;

        // 2. Get challenge IDs from proof
        let challenge_ids = proof.challenge_ids();
        if challenge_ids.is_empty() {
            return Err(Error::Message("Proof contains no challenges".to_string()));
        }

        // 3. Build challenge inputs from contract storage
        let mut challenge_inputs = Vec::new();
        for cid in &challenge_ids {
            let challenge = model
                .challenges()
                .get(cid)
                .ok_or(Error::Message(format!("Challenge not found: {}", cid)))?;

            // Only accept proofs for active challenges
            if challenge.status().load() != ChallengeStatus::Active {
                return Err(Error::Message(format!(
                    "Challenge {} is not active (status: {:?})",
                    cid,
                    challenge.status().load()
                )));
            }

            // Get file_id from agreement
            let agreement =
                model
                    .agreements()
                    .get(&challenge.agreement_id())
                    .ok_or(Error::Message(format!(
                        "Agreement not found: {}",
                        challenge.agreement_id()
                    )))?;

            challenge_inputs.push(file_registry::ChallengeInput {
                challenge_id: cid.clone(),
                file_id: agreement.file_id(),
                block_height: challenge.block_height(),
                num_challenges: challenge.num_challenges(),
                seed: challenge.seed(),
                prover_id: challenge.prover_id(),
            });
        }

        // 4. Verify the proof
        let result = proof.verify(&challenge_inputs)?;

        // 5. Update challenge statuses based on result
        let new_status = match result {
            file_registry::VerifyResult::Verified => ChallengeStatus::Proven,
            file_registry::VerifyResult::Rejected => ChallengeStatus::Failed,
            file_registry::VerifyResult::Invalid => ChallengeStatus::Invalid,
        };

        // In-place; the `status` index follows via the get() binding. The status
        // is terminal (proven/failed/invalid), so the agreement's challenge slot
        // is cleared.
        for cid in &challenge_ids {
            if let Some(c) = model.challenges().get(cid) {
                c.set_status(new_status);
                if let Some(agreement) = model.agreements().get(&c.agreement_id()) {
                    agreement.set_active_challenge(None);
                }
            }
        }

        Ok(VerifyProofResult {
            verified_count: challenge_ids.len() as u64,
        })
    }
}

// ─────────────────────────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────────────────────────

/// Compute the number of agreements to challenge for this block using:
///   θ(t) = (C_target * |F|) / B
///
/// We compute `base = floor((C_target * |F|)/B)` and then add 1 with probability equal to
/// the fractional remainder, using `roll_mod_1000` (0..999) as the deterministic RNG roll.
pub fn compute_num_to_challenge(
    c_target: u64,
    total_files: usize,
    blocks_per_year: u64,
    roll: u64,
) -> usize {
    if total_files == 0 || blocks_per_year == 0 {
        return 0;
    }

    let total_files_u64 = total_files as u64;
    let expected_challenges_scaled = c_target * total_files_u64;
    let num_challenges_base = expected_challenges_scaled / blocks_per_year;

    let remainder = expected_challenges_scaled % blocks_per_year;
    // Match simulation behavior: add one more with probability remainder / blocks_per_year.
    // We do this deterministically by drawing a roll in [0, blocks_per_year) and checking roll < remainder.
    let roll = roll % blocks_per_year;
    let num = if roll < remainder {
        num_challenges_base + 1
    } else {
        num_challenges_base
    };

    core::cmp::min(num, total_files_u64) as usize
}

/// Derive the per-block batch seed:
///   σ_batch = HKDF_SHA256(block_hash, info = "KONTOR-CHAL::v1" || block_height)
///
/// 64 bytes are suitable for unbiased field element conversion via from_uniform_bytes.
pub fn derive_batch_seed(block_hash: &[u8], block_height: u64) -> [u8; 64] {
    let full_info = [
        b"KONTOR-CHAL::v1".as_slice(),
        block_height.to_le_bytes().as_slice(),
    ]
    .concat();
    // Spec does not require a salt here; use empty salt for determinism.
    let derived = crypto::hkdf_derive(block_hash, &[], &full_info);
    derived
        .try_into()
        .expect("hkdf_derive must return 64 bytes")
}

/// Derive a deterministic stream seed from σ_batch for a particular purpose.
pub fn derive_stream_seed(sigma_batch: &[u8; 64], domain: &[u8]) -> [u8; 64] {
    let full_info = [b"KONTOR-CHAL-STREAM::v1/".as_slice(), domain].concat();
    let derived = crypto::hkdf_derive(sigma_batch, &[], &full_info);
    derived
        .try_into()
        .expect("hkdf_derive must return 64 bytes")
}

/// Domain-separated stream seed for a specific file.
pub fn derive_stream_seed_for_file(
    sigma_batch: &[u8; 64],
    domain: &[u8],
    file_id: &str,
) -> [u8; 64] {
    let full_info = [b"KONTOR-CHAL-STREAM::v1/".as_slice(), domain].concat();
    let derived = crypto::hkdf_derive(sigma_batch, file_id.as_bytes(), &full_info);
    derived
        .try_into()
        .expect("hkdf_derive must return 64 bytes")
}

/// Derive the per-file challenge seed (64 bytes) from σ_batch and file_id.
pub fn derive_challenge_seed_for_file(sigma_batch: &[u8; 64], file_id: &str) -> [u8; 64] {
    let derived = crypto::hkdf_derive(sigma_batch, file_id.as_bytes(), b"KONTOR-SEED::v1");
    derived
        .try_into()
        .expect("hkdf_derive must return 64 bytes")
}

/// Deterministically derive a u64 from a 64-byte seed using HKDF-SHA256 via host function.
/// `counter` is used as the HKDF salt to produce a stable stream of outputs.
pub fn seeded_u64(seed: &[u8; 64], counter: &mut u64, domain_separator: &[u8]) -> u64 {
    let full_info = [b"KONTOR-RNG::v1/".as_slice(), domain_separator].concat();
    let salt = counter.to_le_bytes();
    let derived = crypto::hkdf_derive(seed, &salt, &full_info);
    *counter = counter.wrapping_add(1);
    u64::from_le_bytes(derived[..8].try_into().expect("slice is 8 bytes"))
}

/// Generate unbiased random index in range [0, n) using rejection sampling
pub fn uniform_index(seed: &[u8; 64], counter: &mut u64, info: &[u8], n: usize) -> usize {
    uniform_index_from_u64(n, &mut || seeded_u64(seed, counter, info))
}

/// Generate unbiased random index in range [0, n) using rejection sampling.
///
/// This is a pure helper that can be unit-tested without host functions.
pub fn uniform_index_from_u64(n: usize, next_u64: &mut impl FnMut() -> u64) -> usize {
    if n == 0 {
        return 0;
    }

    let n_u64 = n as u64;

    // Find the largest multiple of n that fits in u64.
    // This is the threshold below which all values are unbiased.
    let limit = u64::MAX - (u64::MAX % n_u64);

    loop {
        let rand_val = next_u64();
        if rand_val < limit {
            return (rand_val % n_u64) as usize;
        }
        // Otherwise reject and generate a new value
    }
}

/// Validate and register a file descriptor with the file registry host.
fn register_file_descriptor(descriptor: &RawFileDescriptor) -> Result<(), Error> {
    let fd: file_registry::FileDescriptor = file_registry::FileDescriptor::from_raw(descriptor)?;
    file_registry::add_file(&fd);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{compute_num_to_challenge, uniform_index_from_u64};

    #[test]
    fn theta_total_files_zero() {
        assert_eq!(compute_num_to_challenge(12, 0, 52560, 0), 0);
    }

    #[test]
    fn theta_blocks_per_year_zero() {
        assert_eq!(compute_num_to_challenge(12, 10, 0, 0), 0);
    }

    #[test]
    fn theta_threshold_zero_always_zero_with_defaults_for_small_f() {
        // With defaults, total_files=4 => expected_scaled=48,
        // base=0, remainder=48 => +1 with probability 48/52560.
        assert_eq!(compute_num_to_challenge(12, 4, 52560, 0), 1); // roll < remainder
        assert_eq!(compute_num_to_challenge(12, 4, 52560, 47), 1);
        assert_eq!(compute_num_to_challenge(12, 4, 52560, 48), 0); // roll >= remainder
        assert_eq!(compute_num_to_challenge(12, 4, 52560, 52559), 0);
    }

    #[test]
    fn theta_threshold_positive_branches() {
        // total_files=100 => expected_scaled=1200
        // base=0, remainder=1200
        assert_eq!(compute_num_to_challenge(12, 100, 52560, 0), 1);
        assert_eq!(compute_num_to_challenge(12, 100, 52560, 1199), 1);
        assert_eq!(compute_num_to_challenge(12, 100, 52560, 1200), 0);
        assert_eq!(compute_num_to_challenge(12, 100, 52560, 52559), 0);
    }

    #[test]
    fn theta_base_and_remainder_cases_with_small_blocks_per_year() {
        // Use a small blocks_per_year to exercise base>0 without requiring huge |F|.
        // expected_scaled = 3*10=30, base=3, remainder=0 => always 3
        for roll in [0u64, 999] {
            assert_eq!(compute_num_to_challenge(3, 10, 10, roll), 3);
        }

        // expected_scaled = 3*12=36, base=3, remainder=6 => +1 when roll%10 < 6
        assert_eq!(compute_num_to_challenge(3, 12, 10, 0), 4);
        assert_eq!(compute_num_to_challenge(3, 12, 10, 5), 4);
        assert_eq!(compute_num_to_challenge(3, 12, 10, 6), 3);
        assert_eq!(compute_num_to_challenge(3, 12, 10, 9), 3);
    }

    #[test]
    fn theta_caps_to_total_files() {
        // expected_scaled = 12*10=120, base=12, remainder=0 => 12 but cap to total_files=10
        assert_eq!(compute_num_to_challenge(12, 10, 10, 0), 10);
    }

    #[test]
    fn uniform_index_n_zero_returns_zero() {
        let mut next = || 123u64;
        assert_eq!(uniform_index_from_u64(0, &mut next), 0);
    }

    #[test]
    fn uniform_index_returns_in_range() {
        let mut next = || 123u64;
        let idx = uniform_index_from_u64(10, &mut next);
        assert!(idx < 10);
    }

    #[test]
    fn uniform_index_rejects_values_at_or_above_limit() {
        // For n=10: any value >= limit should be rejected.
        let n = 10usize;
        let n_u64 = n as u64;
        let limit = u64::MAX - (u64::MAX % n_u64);

        // First draw is rejected, second draw should be accepted.
        let mut calls = 0u64;
        let mut next = || {
            calls += 1;
            if calls == 1 {
                limit // rejected (rand_val < limit must hold)
            } else {
                7 // accepted => 7 % 10 = 7
            }
        };

        assert_eq!(uniform_index_from_u64(n, &mut next), 7);
        assert_eq!(calls, 2);
    }
}
