use async_trait::async_trait;
use bon::Builder;
use glob::Paths;
use indexer::{
    database::{
        queries::{
            contract_has_state, get_checkpoint_latest, get_transaction_by_txid, insert_contract,
            insert_transaction,
        },
        types::{ContractRow, OpResultId},
    },
    reg_tester::{self},
    runtime::{Runtime as IndexerRuntime, TransactionContext},
    test_utils::new_mock_transaction,
};
pub use indexer::{logging::setup as logging, testlib_exports::*};
use indexer_types::{Inst, TransactionRow};
pub use serial_test;
use std::{collections::HashMap, path::PathBuf};
use tempfile::TempDir;
pub use tokio;
use tokio::{fs::File, io::AsyncReadExt, task};
pub use tracing;

/// A typed call that bundles an expression, contract address, and parse function.
/// Generated by the `interface!` macro for each exported function.
pub struct TypedCall<T> {
    pub contract: ContractAddress,
    pub expr: String,
    pub parse: fn(&str) -> T,
}

/// Trait for type-erased calls — used by Batch to store heterogeneous calls.
pub trait CallExpr {
    fn expr(&self) -> &str;
    fn contract(&self) -> &ContractAddress;
}

impl<T> CallExpr for TypedCall<T> {
    fn expr(&self) -> &str {
        &self.expr
    }
    fn contract(&self) -> &ContractAddress {
        &self.contract
    }
}

/// A typed handle to a batched call's result. Retains the type and parse function.
pub struct Handle<T> {
    index: usize,
    parse: fn(&str) -> T,
}

/// Results from a batch execution.
pub struct BatchResults {
    raw: Vec<String>,
}

impl BatchResults {
    pub fn get<T>(&self, handle: &Handle<T>) -> T {
        (handle.parse)(&self.raw[handle.index])
    }
}

#[macro_export]
macro_rules! absolute_file {
    () => {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join(file!())
    };
}

#[derive(Clone)]
pub struct ContractReader {
    dir: String,
    contracts: HashMap<String, PathBuf>,
}

impl ContractReader {
    pub async fn new(dir: &str) -> Result<Self> {
        let paths = Self::find_contracts(dir).await?;
        Ok(Self {
            dir: dir.to_string(),
            contracts: paths
                .filter_map(Result::ok)
                .filter(|p| p.is_file())
                .map(|p| {
                    {
                        (
                            p.file_name()
                                .expect("File has no name")
                                .to_string_lossy()
                                .strip_suffix(".wasm.br")
                                .unwrap()
                                .replace("_", "-")
                                .to_string(),
                            p,
                        )
                    }
                })
                .collect(),
        })
    }

    pub async fn read(&self, name: &str) -> Result<Option<Vec<u8>>> {
        Ok(if let Some(path) = self.contracts.get(name) {
            let mut file = File::open(path).await?;
            let mut buffer = Vec::new();
            file.read_to_end(&mut buffer).await?;
            Some(buffer)
        } else {
            None
        })
    }

    async fn find_contracts(dir: &str) -> Result<Paths> {
        let pattern = format!("{}/**/target/wasm32-unknown-unknown/release/*.wasm.br", dir);
        Ok(
            task::spawn_blocking(move || glob::glob(&pattern).expect("Invalid glob pattern"))
                .await?,
        )
    }
}

#[derive(Default, Builder)]
pub struct RuntimeConfig<'a> {
    pub contracts_dir: &'a str,
}

#[async_trait]
pub trait RuntimeImpl: Send {
    async fn identity(&mut self) -> Result<Signer>;
    async fn publish(
        &mut self,
        signer: &Signer,
        name: &str,
        contract: &[u8],
    ) -> Result<ContractAddress>;
    async fn wit(&self, contract_address: &ContractAddress) -> Result<String>;
    async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String>;
    async fn issuance(&mut self, signer: &Signer) -> Result<()>;
    async fn checkpoint(&mut self) -> Result<Option<String>>;

    /// Publish multiple contracts in a single block. Default implementation
    /// falls back to sequential publishes.
    async fn publish_many(
        &mut self,
        signer: &Signer,
        contracts: &[(&str, &[u8])],
    ) -> Result<Vec<ContractAddress>> {
        let mut addresses = Vec::with_capacity(contracts.len());
        for (name, bytes) in contracts {
            addresses.push(self.publish(signer, name, bytes).await?);
        }
        Ok(addresses)
    }

    /// Execute multiple calls in a single consensus batch. Default implementation
    /// falls back to sequential executes.
    async fn execute_many(
        &mut self,
        calls: &[(&Signer, &ContractAddress, &str)],
    ) -> Result<Vec<String>> {
        let mut results = Vec::with_capacity(calls.len());
        for (signer, contract, expr) in calls {
            results.push(self.execute(Some(signer), contract, expr).await?);
        }
        Ok(results)
    }
}

pub struct RuntimeLocal {
    runtime: IndexerRuntime,
    _db_dir: TempDir,
    _db_name: String,
}

impl RuntimeLocal {
    pub async fn load_contracts(
        &mut self,
        signer: &Signer,
        contracts: &[(&str, &[u8])],
    ) -> Result<()> {
        let height = 1;
        let tx_index = 0;
        let conn = self.runtime.get_storage_conn();
        let tx = new_mock_transaction(1);
        if get_transaction_by_txid(&conn, &tx.txid.to_string())
            .await?
            .is_none()
        {
            insert_transaction(
                &conn,
                TransactionRow::builder()
                    .height(height)
                    .tx_index(0)
                    .txid(tx.txid.to_string())
                    .build(),
            )
            .await?;
        };

        for (name, bytes) in contracts {
            let contract_id = insert_contract(
                &conn,
                ContractRow::builder()
                    .height(height)
                    .tx_index(tx_index)
                    .name(name.to_string())
                    .bytes(bytes.to_vec())
                    .build(),
            )
            .await?;
            if !contract_has_state(&conn, contract_id).await? {
                self.runtime
                    .execute(
                        Some(signer),
                        &ContractAddress {
                            name: name.to_string(),
                            height: height as u64,
                            tx_index: tx_index as u64,
                        },
                        "init()",
                    )
                    .await?;
            }
        }
        Ok(())
    }

    pub fn into_parts(self) -> (IndexerRuntime, TempDir) {
        (self.runtime, self._db_dir)
    }

    pub async fn new() -> Result<Self> {
        let (mut runtime, _db_dir, _db_name) = indexer::test_utils::test_runtime().await?;
        let conn = runtime.get_storage_conn();
        let height = 1i64;
        let tx_index = 1i64;
        let txid = new_mock_transaction(0).txid;
        let tx_id = insert_transaction(
            &conn,
            TransactionRow::builder()
                .height(height)
                .txid(txid.to_string())
                .tx_index(tx_index)
                .confirmed_height(height)
                .build(),
        )
        .await?;
        runtime
            .set_context(
                height,
                Some(
                    TransactionContext::builder()
                        .tx_id(tx_id)
                        .tx_index(tx_index)
                        .txid(txid)
                        .build(),
                ),
                None,
                None,
            )
            .await;
        Ok(Self {
            runtime,
            _db_dir,
            _db_name,
        })
    }
}

#[async_trait]
impl RuntimeImpl for RuntimeLocal {
    async fn identity(&mut self) -> Result<Signer> {
        let x_only_pubkey = reg_tester::random_x_only_pubkey();
        let signer = Signer::XOnlyPubKey(x_only_pubkey);
        self.issuance(&signer).await?;
        Ok(signer)
    }

    async fn publish(
        &mut self,
        signer: &Signer,
        name: &str,
        contract: &[u8],
    ) -> Result<ContractAddress> {
        self.load_contracts(signer, &[(name, contract)]).await?;
        Ok(ContractAddress {
            name: name.to_string(),
            height: 1,
            tx_index: 0,
        })
    }

    async fn wit(&self, contract_address: &ContractAddress) -> Result<String> {
        let contract_id = self
            .runtime
            .storage
            .contract_id(contract_address)
            .await?
            .ok_or(anyhow!("Contract not found"))?;
        self.runtime.storage.component_wit(contract_id).await
    }

    async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String> {
        let result = self.runtime.execute(signer, contract_address, expr).await;
        if let Some(c) = self.runtime.tx_context_mut() {
            c.op_index += 1;
        }
        result
    }

    async fn issuance(&mut self, signer: &Signer) -> Result<()> {
        self.runtime.issuance(signer).await
    }

    async fn checkpoint(&mut self) -> Result<Option<String>> {
        Ok(get_checkpoint_latest(&self.runtime.storage.conn)
            .await?
            .map(|r| r.hash))
    }
}

pub struct RuntimeRegtest {
    reg_tester: RegTester,
    pub identities: HashMap<Signer, reg_tester::Identity>,
}

impl RuntimeRegtest {
    pub fn new(reg_tester: RegTester) -> Self {
        let identities = HashMap::new();
        Self {
            reg_tester,
            identities,
        }
    }
}

#[async_trait]
impl RuntimeImpl for RuntimeRegtest {
    async fn identity(&mut self) -> Result<Signer> {
        let identity = if self.reg_tester.cluster_mode().await {
            // Pipeline RegisterBlsKey + Issuance into one consensus round
            self.reg_tester.identity_with_issuance().await?
        } else {
            // Standalone mode: sequential instructions with mining
            let ident = self.reg_tester.identity().await?;
            let signer = ident.signer();
            self.identities.insert(signer.clone(), ident);
            self.issuance(&signer).await?;
            return Ok(signer);
        };
        let signer = identity.signer();
        self.identities.insert(signer.clone(), identity);
        Ok(signer)
    }

    async fn publish(
        &mut self,
        signer: &Signer,
        name: &str,
        contract: &[u8],
    ) -> Result<ContractAddress> {
        Ok(self
            .publish_many(signer, &[(name, contract)])
            .await?
            .remove(0))
    }

    async fn wit(&self, contract_address: &ContractAddress) -> Result<String> {
        self.reg_tester.wit(contract_address).await
    }

    async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String> {
        if let Some(signer) = signer {
            let identity = self
                .identities
                .get_mut(signer)
                .ok_or_else(|| anyhow!("Identity not found"))?;
            self.reg_tester
                .instruction(
                    identity,
                    Inst::Call {
                        gas_limit: 10_000,
                        contract: contract_address.clone().into(),
                        nonce: None,
                        expr: expr.to_string(),
                    },
                )
                .await
                .map(|r| {
                    r.result
                        .value
                        .expect("Handling for error should have already occurred")
                })
        } else {
            self.reg_tester.view(contract_address, expr).await
        }
    }

    async fn issuance(&mut self, signer: &Signer) -> Result<()> {
        let identity = self
            .identities
            .get_mut(signer)
            .ok_or_else(|| anyhow!("Identity not found"))?;
        self.reg_tester
            .instruction(identity, Inst::Issuance)
            .await?;
        Ok(())
    }

    async fn publish_many(
        &mut self,
        signer: &Signer,
        contracts: &[(&str, &[u8])],
    ) -> Result<Vec<ContractAddress>> {
        // Check cache — filter out already-published contracts
        let mut addresses: Vec<Option<ContractAddress>> = Vec::with_capacity(contracts.len());
        let mut to_publish = Vec::new();
        for (i, (name, bytes)) in contracts.iter().enumerate() {
            if let Some(addr) = self.reg_tester.get_published(name).await {
                addresses.push(Some(addr));
            } else {
                addresses.push(None);
                to_publish.push((i, *name, *bytes));
            }
        }

        if to_publish.is_empty() {
            return Ok(addresses.into_iter().map(|a| a.unwrap()).collect());
        }

        // Send all publish instructions without mining
        let identity = self
            .identities
            .get_mut(signer)
            .ok_or_else(|| anyhow!("Identity not found"))?;
        let mut txids = Vec::new();
        for &(_, name, bytes) in &to_publish {
            let sent = self
                .reg_tester
                .send_instruction(
                    identity,
                    Inst::Publish {
                        gas_limit: 10_000,
                        name: name.to_string(),
                        bytes: bytes.to_vec(),
                    },
                )
                .await?;
            txids.push(sent.reveal_txid.to_string());
        }

        // Mine once, wait for all
        self.reg_tester.mine(1).await?;
        self.reg_tester.wait_for_txids(&txids).await?;

        // Query results for contract addresses
        let client = self.reg_tester.kontor_client().await;
        for (j, &(i, name, _)) in to_publish.iter().enumerate() {
            let id = OpResultId::builder().txid(txids[j].clone()).build();
            let result = client
                .result(&id)
                .await?
                .ok_or(anyhow!("Could not find op result for {}", name))?;
            let addr: ContractAddress = result
                .contract
                .parse()
                .map_err(|e: String| anyhow!("Failed to parse contract address: {}", e))?;
            self.reg_tester
                .set_published(name.to_string(), addr.clone())
                .await;
            addresses[i] = Some(addr);
        }

        Ok(addresses.into_iter().map(|a| a.unwrap()).collect())
    }

    async fn execute_many(
        &mut self,
        calls: &[(&Signer, &ContractAddress, &str)],
    ) -> Result<Vec<String>> {
        if calls.is_empty() {
            return Ok(vec![]);
        }

        let mut txids = Vec::with_capacity(calls.len());
        for (signer, contract, expr) in calls {
            let identity = self
                .identities
                .get_mut(signer)
                .ok_or_else(|| anyhow!("Identity not found"))?;
            let sent = self
                .reg_tester
                .send_instruction(
                    identity,
                    Inst::Call {
                        gas_limit: 10_000,
                        contract: (*contract).clone().into(),
                        expr: expr.to_string(),
                    },
                )
                .await?;
            txids.push(sent.reveal_txid.to_string());
        }

        // No mining — batchable calls go through consensus
        self.reg_tester.wait_for_txids(&txids).await?;

        let client = self.reg_tester.kontor_client().await;
        let mut results = Vec::with_capacity(txids.len());
        for txid in &txids {
            let id = OpResultId::builder().txid(txid.clone()).build();
            let result = client
                .result(&id)
                .await?
                .ok_or(anyhow!("Could not find op result"))?;
            results.push(result.value.ok_or(anyhow!("Call failed in processing"))?);
        }
        Ok(results)
    }

    async fn checkpoint(&mut self) -> Result<Option<String>> {
        self.reg_tester.checkpoint().await
    }
}

pub struct Runtime {
    pub contract_reader: ContractReader,
    pub runtime: Box<dyn RuntimeImpl>,
}

impl Runtime {
    pub async fn new_local(config: RuntimeConfig<'_>) -> Result<Self> {
        let runtime = RuntimeLocal::new().await?;
        Ok(Runtime {
            contract_reader: ContractReader::new(config.contracts_dir).await?,
            runtime: Box::new(runtime),
        })
    }

    pub async fn new_regtest(config: RuntimeConfig<'_>, reg_tester: RegTester) -> Result<Self> {
        let runtime = Box::new(RuntimeRegtest::new(reg_tester));
        Ok(Runtime {
            contract_reader: ContractReader::new(config.contracts_dir).await?,
            runtime,
        })
    }

    pub fn new_regtest_with_reader(contract_reader: ContractReader, reg_tester: RegTester) -> Self {
        Runtime {
            contract_reader,
            runtime: Box::new(RuntimeRegtest::new(reg_tester)),
        }
    }

    pub async fn identity(&mut self) -> Result<Signer> {
        self.runtime.identity().await
    }

    pub async fn publish(&mut self, signer: &Signer, name: &str) -> Result<ContractAddress> {
        self.publish_as(signer, name, name).await
    }

    pub async fn publish_many(
        &mut self,
        signer: &Signer,
        names: &[&str],
    ) -> Result<Vec<ContractAddress>> {
        let mut contracts = Vec::with_capacity(names.len());
        for name in names {
            let name = name.replace("_", "-");
            let bytes = self.contract_reader.read(&name).await?.ok_or(anyhow!(
                "Contract not found: {} in {}",
                name,
                self.contract_reader.dir,
            ))?;
            contracts.push((name, bytes));
        }
        let refs: Vec<(&str, &[u8])> = contracts
            .iter()
            .map(|(n, b)| (n.as_str(), b.as_slice()))
            .collect();
        self.runtime.publish_many(signer, &refs).await
    }

    pub async fn wit(&mut self, contract_address: &ContractAddress) -> Result<String> {
        self.runtime.wit(contract_address).await
    }

    pub async fn publish_as(
        &mut self,
        signer: &Signer,
        name: &str,
        alias: &str,
    ) -> Result<ContractAddress> {
        let name = name.replace("_", "-");
        let alias = alias.replace("_", "-");
        let contract = self.contract_reader.read(&name).await?.ok_or(anyhow!(
            "Contract not found: {} in {}",
            name,
            self.contract_reader.dir,
        ))?;
        self.runtime.publish(signer, &alias, &contract).await
    }

    pub async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String> {
        self.runtime.execute(signer, contract_address, expr).await
    }

    pub async fn issuance(&mut self, signer: &Signer) -> Result<()> {
        self.runtime.issuance(signer).await
    }

    pub async fn checkpoint(&mut self) -> Result<Option<String>> {
        self.runtime.checkpoint().await
    }

    pub fn batch(&mut self) -> Batch<'_> {
        Batch {
            runtime: self,
            calls: Vec::new(),
        }
    }
}

pub struct Batch<'a> {
    runtime: &'a mut Runtime,
    calls: Vec<(Signer, Box<dyn CallExpr>)>,
}

impl<'a> Batch<'a> {
    pub fn push<T: 'static>(&mut self, signer: &Signer, call: TypedCall<T>) -> Handle<T> {
        let index = self.calls.len();
        let parse = call.parse;
        self.calls.push((signer.clone(), Box::new(call)));
        Handle { index, parse }
    }

    pub async fn execute(self) -> Result<BatchResults> {
        let calls: Vec<(&Signer, &ContractAddress, &str)> = self
            .calls
            .iter()
            .map(|(s, c)| (s, c.contract(), c.expr()))
            .collect();
        let raw = self.runtime.runtime.execute_many(&calls).await?;
        Ok(BatchResults { raw })
    }
}
