use async_trait::async_trait;
use bon::Builder;
use glob::Paths;
use indexer::{
    bls::KONTOR_BLS_DST,
    database::{
        queries::{
            contract_has_state, get_checkpoint_latest, get_transaction_by_txid, insert_contract,
            insert_transaction,
        },
        types::{ContractRow, OpResultId},
    },
    reg_tester::{self},
    runtime::{Runtime as IndexerRuntime, TransactionContext},
    test_utils::new_mock_transaction,
};
pub use indexer::{logging::setup as logging, testlib_exports::*};
use indexer_types::{Inst, Insts, TransactionRow};
use std::{cell::Cell, collections::HashMap, path::PathBuf, rc::Rc};
use tempfile::TempDir;
pub use tokio;
use tokio::{fs::File, io::AsyncReadExt, task};
pub use tracing;

/// A typed call that bundles an expression, contract address, and parse function.
/// Generated by the `interface!` macro for each exported function.
pub struct TypedCall<T> {
    pub contract: ContractAddress,
    pub expr: String,
    pub parse: fn(&str) -> T,
}

/// Trait for type-erased calls — used by Batch to store heterogeneous calls.
pub trait CallExpr: Send {
    fn expr(&self) -> &str;
    fn contract(&self) -> &ContractAddress;
}

impl<T> CallExpr for TypedCall<T> {
    fn expr(&self) -> &str {
        &self.expr
    }
    fn contract(&self) -> &ContractAddress {
        &self.contract
    }
}

/// A typed handle to a submitted call's result. Retains the type and parse function.
/// The group_index is shared with the Ops that created it via Rc<Cell>, and gets
/// set when the Ops is added to a Submit.
pub struct Handle<T> {
    group_index: Rc<Cell<usize>>,
    op_index: usize,
    parse: fn(&str) -> T,
}

/// Results from a submit execution. Each group's results are stored separately.
pub struct SubmitResults {
    pub groups: Vec<Vec<String>>,
}

impl SubmitResults {
    pub fn get<T>(&self, handle: &Handle<T>) -> T {
        (handle.parse)(&self.groups[handle.group_index.get()][handle.op_index])
    }
}

/// Specifies a contract to publish: either just a name (published as itself)
/// or a (name, alias) pair (contract bytes loaded by name, published under alias).
#[derive(Copy, Clone)]
pub struct PublishSpec<'a> {
    pub name: &'a str,
    pub alias: &'a str,
}

impl<'a> PublishSpec<'a> {
    fn into_parts(self) -> (&'a str, &'a str) {
        (self.name, self.alias)
    }
}

impl<'a> From<&'a str> for PublishSpec<'a> {
    fn from(name: &'a str) -> Self {
        PublishSpec { name, alias: name }
    }
}

impl<'a> From<(&'a str, &'a str)> for PublishSpec<'a> {
    fn from((name, alias): (&'a str, &'a str)) -> Self {
        PublishSpec { name, alias }
    }
}

#[macro_export]
macro_rules! absolute_file {
    () => {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join(file!())
    };
}

#[derive(Clone)]
pub struct ContractReader {
    dir: String,
    contracts: HashMap<String, PathBuf>,
}

impl ContractReader {
    pub async fn new(dir: &str) -> Result<Self> {
        let paths = Self::find_contracts(dir).await?;
        Ok(Self {
            dir: dir.to_string(),
            contracts: paths
                .filter_map(Result::ok)
                .filter(|p| p.is_file())
                .map(|p| {
                    {
                        (
                            p.file_name()
                                .expect("File has no name")
                                .to_string_lossy()
                                .strip_suffix(".wasm.br")
                                .unwrap()
                                .replace("_", "-")
                                .to_string(),
                            p,
                        )
                    }
                })
                .collect(),
        })
    }

    pub async fn read(&self, name: &str) -> Result<Option<Vec<u8>>> {
        Ok(if let Some(path) = self.contracts.get(name) {
            let mut file = File::open(path).await?;
            let mut buffer = Vec::new();
            file.read_to_end(&mut buffer).await?;
            Some(buffer)
        } else {
            None
        })
    }

    async fn find_contracts(dir: &str) -> Result<Paths> {
        let pattern = format!("{}/**/target/wasm32-unknown-unknown/release/*.wasm.br", dir);
        Ok(
            task::spawn_blocking(move || glob::glob(&pattern).expect("Invalid glob pattern"))
                .await?,
        )
    }
}

#[derive(Default, Builder)]
pub struct RuntimeConfig<'a> {
    pub contracts_dir: &'a str,
}

#[async_trait]
pub trait RuntimeImpl: Send {
    async fn identity(&mut self) -> Result<Signer>;
    async fn publish(
        &mut self,
        signer: &Signer,
        name: &str,
        contract: &[u8],
    ) -> Result<ContractAddress>;
    async fn wit(&self, contract_address: &ContractAddress) -> Result<String>;
    async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String>;
    async fn issuance(&mut self, signer: &Signer) -> Result<()>;
    async fn checkpoint(&mut self) -> Result<Option<String>>;

    /// Get a clone of the underlying RegTester, if running against a regtest cluster.
    fn reg_tester(&self) -> Option<RegTester> {
        None
    }

    /// Publish multiple contracts in a single block. Default implementation
    /// falls back to sequential publishes.
    async fn publish_many(
        &mut self,
        signer: &Signer,
        contracts: &[(&str, &[u8])],
    ) -> Result<Vec<ContractAddress>> {
        let mut addresses = Vec::with_capacity(contracts.len());
        for (name, bytes) in contracts {
            addresses.push(self.publish(signer, name, bytes).await?);
        }
        Ok(addresses)
    }

    /// Execute a submission of grouped calls. Default falls back to sequential.
    async fn execute_submit(&mut self, groups: &[SubmitGroup<'_>]) -> Result<Vec<Vec<String>>> {
        let mut results = Vec::with_capacity(groups.len());
        for group in groups {
            match group {
                SubmitGroup::Single(signer, contract, expr) => {
                    results.push(vec![self.execute(Some(signer), contract, expr).await?]);
                }
                SubmitGroup::Ordered(signer, calls) => {
                    let mut group_results = Vec::with_capacity(calls.len());
                    for (contract, expr) in calls {
                        group_results.push(self.execute(Some(signer), contract, expr).await?);
                    }
                    results.push(group_results);
                }
                SubmitGroup::Aggregate(calls) => {
                    let mut group_results = Vec::with_capacity(calls.len());
                    for (signer, contract, expr) in calls {
                        group_results.push(self.execute(Some(signer), contract, expr).await?);
                    }
                    results.push(group_results);
                }
            }
        }
        Ok(results)
    }
}

/// A group of calls within a Submit.
pub enum SubmitGroup<'a> {
    /// Single call, one tx.
    Single(&'a Signer, &'a ContractAddress, &'a str),
    /// Ordered calls, same signer, one tx.
    Ordered(&'a Signer, Vec<(&'a ContractAddress, &'a str)>),
    /// Ordered calls, per-call signers, BLS aggregate, one tx.
    Aggregate(Vec<(&'a Signer, &'a ContractAddress, &'a str)>),
}

pub struct RuntimeLocal {
    runtime: IndexerRuntime,
    _db_dir: TempDir,
    _db_name: String,
}

impl RuntimeLocal {
    pub async fn load_contracts(
        &mut self,
        signer: &Signer,
        contracts: &[(&str, &[u8])],
    ) -> Result<()> {
        let height = 1;
        let tx_index = 0;
        let conn = self.runtime.get_storage_conn();
        let tx = new_mock_transaction(1);
        if get_transaction_by_txid(&conn, &tx.txid.to_string())
            .await?
            .is_none()
        {
            insert_transaction(
                &conn,
                TransactionRow::builder()
                    .height(height)
                    .tx_index(0)
                    .txid(tx.txid.to_string())
                    .build(),
            )
            .await?;
        };

        for (name, bytes) in contracts {
            let contract_id = insert_contract(
                &conn,
                ContractRow::builder()
                    .height(height)
                    .tx_index(tx_index)
                    .name(name.to_string())
                    .bytes(bytes.to_vec())
                    .build(),
            )
            .await?;
            if !contract_has_state(&conn, contract_id).await? {
                self.runtime
                    .execute(
                        Some(signer),
                        &ContractAddress {
                            name: name.to_string(),
                            height: height as u64,
                            tx_index: tx_index as u64,
                        },
                        "init()",
                    )
                    .await
                    .map_err(anyhow::Error::from)?;
            }
        }
        Ok(())
    }

    pub fn into_parts(self) -> (IndexerRuntime, TempDir) {
        (self.runtime, self._db_dir)
    }

    pub async fn new() -> Result<Self> {
        let (mut runtime, _db_dir, _db_name) = indexer::test_utils::test_runtime().await?;
        let conn = runtime.get_storage_conn();
        let height = 1i64;
        let tx_index = 1i64;
        let txid = new_mock_transaction(0).txid;
        let tx_id = insert_transaction(
            &conn,
            TransactionRow::builder()
                .height(height)
                .txid(txid.to_string())
                .tx_index(tx_index)
                .confirmed_height(height)
                .build(),
        )
        .await?;
        runtime
            .set_context(
                height,
                Some(
                    TransactionContext::builder()
                        .tx_id(tx_id)
                        .tx_index(tx_index)
                        .txid(txid)
                        .build(),
                ),
                None,
                None,
            )
            .await;
        Ok(Self {
            runtime,
            _db_dir,
            _db_name,
        })
    }
}

#[async_trait]
impl RuntimeImpl for RuntimeLocal {
    async fn identity(&mut self) -> Result<Signer> {
        let x_only_pubkey = reg_tester::random_x_only_pubkey();
        let conn = self.runtime.get_storage_conn();
        let identity = indexer::database::queries::get_or_create_identity(
            &conn,
            &x_only_pubkey,
            self.runtime.storage.height,
        )
        .await?;
        let signer = Signer::Id(identity);
        self.issuance(&signer).await?;
        Ok(signer)
    }

    async fn publish(
        &mut self,
        signer: &Signer,
        name: &str,
        contract: &[u8],
    ) -> Result<ContractAddress> {
        self.load_contracts(signer, &[(name, contract)]).await?;
        Ok(ContractAddress {
            name: name.to_string(),
            height: 1,
            tx_index: 0,
        })
    }

    async fn wit(&self, contract_address: &ContractAddress) -> Result<String> {
        let contract_id = self
            .runtime
            .storage
            .contract_id(contract_address)
            .await?
            .ok_or(anyhow!("Contract not found"))?;
        self.runtime.storage.component_wit(contract_id).await
    }

    async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String> {
        let result = self.runtime.execute(signer, contract_address, expr).await;
        if let Some(c) = self.runtime.tx_context_mut() {
            c.op_index += 1;
        }
        result.map_err(Into::into)
    }

    async fn issuance(&mut self, signer: &Signer) -> Result<()> {
        self.runtime.issuance(signer).await.map_err(Into::into)
    }

    async fn checkpoint(&mut self) -> Result<Option<String>> {
        Ok(get_checkpoint_latest(&self.runtime.storage.conn)
            .await?
            .map(|r| r.hash))
    }
}

pub struct RuntimeRegtest {
    reg_tester: RegTester,
    pub identities: HashMap<Signer, reg_tester::Identity>,
}

impl RuntimeRegtest {
    pub fn new(reg_tester: RegTester) -> Self {
        let identities = HashMap::new();
        Self {
            reg_tester,
            identities,
        }
    }

    /// Build BLS aggregate Insts for multi-signer ordered execution.
    /// Looks up signer_ids and nonces via API views, signs each op, aggregates.
    async fn build_aggregate_insts(
        &self,
        calls: &[(&Signer, &ContractAddress, &str)],
    ) -> Result<Insts> {
        use blst::min_sig::{AggregateSignature, SecretKey as BlsSecretKey};

        let mut ops = Vec::with_capacity(calls.len());
        let mut signer_ids = Vec::with_capacity(calls.len());
        // Track nonce per signer — starts at 0 for each signer in this batch,
        // incremented for subsequent ops from the same signer.
        let mut nonce_counters: HashMap<u64, u64> = HashMap::new();

        for (signer, contract, expr) in calls {
            let signer_id = match signer {
                Signer::Id(identity) => identity.signer_id() as u64,
                _ => anyhow::bail!("BLS aggregate requires Id signer"),
            };

            let nonce = nonce_counters.entry(signer_id).or_insert(0);
            let current_nonce = *nonce;
            *nonce += 1;

            ops.push(Inst::Call {
                gas_limit: 10_000,
                contract: (*contract).clone().into(),
                nonce: Some(current_nonce),
                expr: expr.to_string(),
            });
            signer_ids.push(signer_id);
        }

        // Sign each op with its signer's BLS key and aggregate
        let mut sigs = Vec::with_capacity(calls.len());
        for (i, (signer, _, _)) in calls.iter().enumerate() {
            let identity = self
                .identities
                .get(signer)
                .ok_or_else(|| anyhow!("Identity not found for BLS signing"))?;
            let sk = BlsSecretKey::from_bytes(&identity.bls_secret_key)
                .map_err(|e| anyhow!("Invalid BLS secret key: {:?}", e))?;
            let msg = ops[i].aggregate_signing_message(signer_ids[i])?;
            sigs.push(sk.sign(&msg, KONTOR_BLS_DST, &[]));
        }

        let sig_refs: Vec<_> = sigs.iter().collect();
        let aggregate = AggregateSignature::aggregate(&sig_refs, true)
            .map_err(|e| anyhow!("BLS aggregate failed: {:?}", e))?;

        Ok(Insts {
            ops,
            aggregate: Some(indexer_types::AggregateInfo {
                signer_ids,
                signature: aggregate.to_signature().to_bytes().to_vec(),
            }),
        })
    }
}

#[async_trait]
impl RuntimeImpl for RuntimeRegtest {
    async fn identity(&mut self) -> Result<Signer> {
        let identity = self.reg_tester.identity().await?;
        let signer_id = self
            .reg_tester
            .get_signer_id(&identity.x_only_public_key().to_string())
            .await?
            .expect("identity must be registered");
        let signer = Signer::Id(indexer::database::types::Identity::new(signer_id as i64));
        self.identities.insert(signer.clone(), identity);
        Ok(signer)
    }

    async fn publish(
        &mut self,
        signer: &Signer,
        name: &str,
        contract: &[u8],
    ) -> Result<ContractAddress> {
        let mut guard = self.reg_tester.lock_published(name).await;
        if let Some(addr) = guard.as_ref() {
            return Ok(addr.clone());
        }

        let identity = self
            .identities
            .get_mut(signer)
            .ok_or_else(|| anyhow!("Identity not found"))?;
        let sent = self
            .reg_tester
            .send_instruction(
                identity,
                Inst::Publish {
                    gas_limit: 10_000,
                    name: name.to_string(),
                    bytes: contract.to_vec(),
                },
            )
            .await?;
        let txid = sent.reveal_txid.to_string();
        self.reg_tester.mine(1).await?;
        self.reg_tester
            .wait_for_txids(std::slice::from_ref(&txid))
            .await?;

        let client = self.reg_tester.kontor_client().await;
        let id = OpResultId::builder().txid(txid).build();
        let result = client
            .result(&id)
            .await?
            .ok_or(anyhow!("Could not find op result for {}", name))?;
        let addr: ContractAddress = result
            .contract
            .parse()
            .map_err(|e: String| anyhow!("Failed to parse contract address: {}", e))?;

        *guard = Some(addr.clone());
        Ok(addr)
    }

    async fn wit(&self, contract_address: &ContractAddress) -> Result<String> {
        self.reg_tester.wit(contract_address).await
    }

    async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String> {
        if let Some(signer) = signer {
            let identity = self
                .identities
                .get_mut(signer)
                .ok_or_else(|| anyhow!("Identity not found"))?;
            self.reg_tester
                .instruction(
                    identity,
                    Inst::Call {
                        gas_limit: 10_000,
                        contract: contract_address.clone().into(),
                        nonce: None,
                        expr: expr.to_string(),
                    },
                )
                .await
                .map(|r| {
                    r.result
                        .value
                        .expect("Handling for error should have already occurred")
                })
        } else {
            self.reg_tester.view(contract_address, expr).await
        }
    }

    async fn issuance(&mut self, signer: &Signer) -> Result<()> {
        let identity = self
            .identities
            .get_mut(signer)
            .ok_or_else(|| anyhow!("Identity not found"))?;
        self.reg_tester
            .instruction(identity, Inst::Issuance)
            .await?;
        Ok(())
    }

    async fn publish_many(
        &mut self,
        signer: &Signer,
        contracts: &[(&str, &[u8])],
    ) -> Result<Vec<ContractAddress>> {
        let mut addresses = Vec::with_capacity(contracts.len());
        for &(name, bytes) in contracts {
            let addr = self.publish(signer, name, bytes).await?;
            addresses.push(addr);
        }
        Ok(addresses)
    }

    async fn execute_submit(&mut self, groups: &[SubmitGroup<'_>]) -> Result<Vec<Vec<String>>> {
        // Phase 1: Send all txs to mempool, collecting txids and op counts
        struct Sent {
            txid: String,
            op_count: usize,
        }
        let mut all_sent: Vec<Sent> = Vec::with_capacity(groups.len());

        for group in groups {
            match group {
                SubmitGroup::Single(signer, contract, expr) => {
                    let identity = self
                        .identities
                        .get_mut(signer)
                        .ok_or_else(|| anyhow!("Identity not found"))?;
                    let sent = self
                        .reg_tester
                        .send_instruction(
                            identity,
                            Inst::Call {
                                gas_limit: 10_000,
                                contract: (*contract).clone().into(),
                                nonce: None,
                                expr: expr.to_string(),
                            },
                        )
                        .await?;
                    all_sent.push(Sent {
                        txid: sent.reveal_txid.to_string(),
                        op_count: 1,
                    });
                }
                SubmitGroup::Ordered(signer, calls) => {
                    let insts: Vec<Inst> = calls
                        .iter()
                        .map(|(contract, expr)| Inst::Call {
                            gas_limit: 10_000,
                            contract: (*contract).clone().into(),
                            nonce: None,
                            expr: expr.to_string(),
                        })
                        .collect();
                    let op_count = insts.len();
                    let identity = self
                        .identities
                        .get_mut(signer)
                        .ok_or_else(|| anyhow!("Identity not found"))?;
                    let sent = self
                        .reg_tester
                        .send_insts(identity, Insts::direct(insts))
                        .await?;
                    all_sent.push(Sent {
                        txid: sent.reveal_txid.to_string(),
                        op_count,
                    });
                }
                SubmitGroup::Aggregate(calls) => {
                    let insts = self.build_aggregate_insts(calls).await?;
                    let op_count = insts.ops.len();
                    let identity = self
                        .identities
                        .get_mut(calls[0].0)
                        .ok_or_else(|| anyhow!("Identity not found"))?;
                    let sent = self.reg_tester.send_insts(identity, insts).await?;
                    all_sent.push(Sent {
                        txid: sent.reveal_txid.to_string(),
                        op_count,
                    });
                }
            }
        }

        // Phase 2: Wait for all txids at once
        let txids: Vec<String> = all_sent.iter().map(|s| s.txid.clone()).collect();
        self.reg_tester.wait_for_txids(&txids).await?;

        // Phase 3: Query results
        let client = self.reg_tester.kontor_client().await;
        let mut results = Vec::with_capacity(all_sent.len());
        for sent in &all_sent {
            let mut group_results = Vec::with_capacity(sent.op_count);
            for op_index in 0..sent.op_count {
                let id = OpResultId::builder()
                    .txid(sent.txid.clone())
                    .op_index(op_index as i64)
                    .build();
                let result = client.result(&id).await?.ok_or(anyhow!(
                    "Could not find op result for txid {} op_index {}",
                    sent.txid,
                    op_index
                ))?;
                group_results.push(
                    result
                        .value
                        .ok_or(anyhow!("Call failed at op_index {}", op_index))?,
                );
            }
            results.push(group_results);
        }
        Ok(results)
    }

    async fn checkpoint(&mut self) -> Result<Option<String>> {
        self.reg_tester.checkpoint().await
    }

    fn reg_tester(&self) -> Option<RegTester> {
        Some(self.reg_tester.clone())
    }
}

pub struct Runtime {
    pub contract_reader: ContractReader,
    pub runtime: Box<dyn RuntimeImpl>,
}

impl Runtime {
    pub async fn new_local(config: RuntimeConfig<'_>) -> Result<Self> {
        let runtime = RuntimeLocal::new().await?;
        Ok(Runtime {
            contract_reader: ContractReader::new(config.contracts_dir).await?,
            runtime: Box::new(runtime),
        })
    }

    pub async fn new_regtest(config: RuntimeConfig<'_>, reg_tester: RegTester) -> Result<Self> {
        let runtime = Box::new(RuntimeRegtest::new(reg_tester));
        Ok(Runtime {
            contract_reader: ContractReader::new(config.contracts_dir).await?,
            runtime,
        })
    }

    pub fn new_regtest_with_reader(contract_reader: ContractReader, reg_tester: RegTester) -> Self {
        Runtime {
            contract_reader,
            runtime: Box::new(RuntimeRegtest::new(reg_tester)),
        }
    }

    pub async fn identity(&mut self) -> Result<Signer> {
        self.runtime.identity().await
    }

    pub async fn publish(&mut self, signer: &Signer, name: &str) -> Result<ContractAddress> {
        self.publish_as(signer, name, name).await
    }

    pub async fn publish_many<'b>(
        &mut self,
        signer: &Signer,
        specs: &[impl Into<PublishSpec<'b>> + Copy],
    ) -> Result<Vec<ContractAddress>> {
        let mut contracts = Vec::with_capacity(specs.len());
        for spec in specs {
            let (name, alias) = (*spec).into().into_parts();
            let name = name.replace("_", "-");
            let alias = alias.replace("_", "-");
            let bytes = self.contract_reader.read(&name).await?.ok_or(anyhow!(
                "Contract not found: {} in {}",
                name,
                self.contract_reader.dir,
            ))?;
            contracts.push((alias, bytes));
        }
        let refs: Vec<(&str, &[u8])> = contracts
            .iter()
            .map(|(n, b)| (n.as_str(), b.as_slice()))
            .collect();
        self.runtime.publish_many(signer, &refs).await
    }

    pub async fn wit(&mut self, contract_address: &ContractAddress) -> Result<String> {
        self.runtime.wit(contract_address).await
    }

    pub async fn publish_as(
        &mut self,
        signer: &Signer,
        name: &str,
        alias: &str,
    ) -> Result<ContractAddress> {
        let name = name.replace("_", "-");
        let alias = alias.replace("_", "-");
        let contract = self.contract_reader.read(&name).await?.ok_or(anyhow!(
            "Contract not found: {} in {}",
            name,
            self.contract_reader.dir,
        ))?;
        self.runtime.publish(signer, &alias, &contract).await
    }

    pub async fn execute(
        &mut self,
        signer: Option<&Signer>,
        contract_address: &ContractAddress,
        expr: &str,
    ) -> Result<String> {
        #[allow(clippy::useless_conversion)]
        self.runtime
            .execute(signer, contract_address, expr)
            .await
            .map_err(Into::into)
    }

    pub async fn issuance(&mut self, signer: &Signer) -> Result<()> {
        self.runtime.issuance(signer).await
    }

    pub async fn checkpoint(&mut self) -> Result<Option<String>> {
        self.runtime.checkpoint().await
    }

    pub fn reg_tester(&self) -> Option<RegTester> {
        self.runtime.reg_tester()
    }

    pub fn submit(&mut self) -> Submit<'_> {
        Submit {
            runtime: self,
            groups: Vec::new(),
        }
    }
}

/// A mempool submission: multiple groups of calls sent at once.
pub struct Submit<'a> {
    runtime: &'a mut Runtime,
    groups: Vec<SubmittedGroup>,
}

struct SubmittedGroup {
    _group_index: Rc<Cell<usize>>,
    kind: SubmittedGroupKind,
}

enum SubmittedGroupKind {
    Single(Signer, Box<dyn CallExpr>),
    Ordered {
        signer: Signer,
        calls: Vec<Box<dyn CallExpr>>,
    },
    Aggregate(Vec<(Signer, Box<dyn CallExpr>)>),
}

impl<'a> Submit<'a> {
    /// Add a single call as its own transaction.
    pub fn push<T: 'static>(&mut self, signer: &Signer, call: TypedCall<T>) -> Handle<T> {
        let group_index = Rc::new(Cell::new(self.groups.len()));
        let parse = call.parse;
        self.groups.push(SubmittedGroup {
            _group_index: group_index.clone(),
            kind: SubmittedGroupKind::Single(signer.clone(), Box::new(call)),
        });
        Handle {
            group_index,
            op_index: 0,
            parse,
        }
    }

    /// Add a pre-built ops group (same-signer or aggregate).
    pub fn add(&mut self, group: impl Into<OpsGroup>) {
        let group = group.into();
        let (group_index, kind) = match group {
            OpsGroup::Direct(ops) => (
                ops.group_index,
                SubmittedGroupKind::Ordered {
                    signer: ops.signer,
                    calls: ops.calls,
                },
            ),
            OpsGroup::Aggregate(ops) => (ops.group_index, SubmittedGroupKind::Aggregate(ops.calls)),
        };
        group_index.set(self.groups.len());
        self.groups.push(SubmittedGroup {
            _group_index: group_index,
            kind,
        });
    }

    /// Send all groups to mempool and wait for all results.
    pub async fn execute(self) -> Result<SubmitResults> {
        let mut all_calls: Vec<SubmitGroup> = Vec::new();
        for group in &self.groups {
            match &group.kind {
                SubmittedGroupKind::Single(signer, call) => {
                    all_calls.push(SubmitGroup::Single(signer, call.contract(), call.expr()));
                }
                SubmittedGroupKind::Ordered { signer, calls } => {
                    let exprs: Vec<(&ContractAddress, &str)> =
                        calls.iter().map(|c| (c.contract(), c.expr())).collect();
                    all_calls.push(SubmitGroup::Ordered(signer, exprs));
                }
                SubmittedGroupKind::Aggregate(calls) => {
                    let exprs: Vec<(&Signer, &ContractAddress, &str)> = calls
                        .iter()
                        .map(|(s, c)| (s, c.contract(), c.expr()))
                        .collect();
                    all_calls.push(SubmitGroup::Aggregate(exprs));
                }
            }
        }

        let results = self.runtime.runtime.execute_submit(&all_calls).await?;
        Ok(SubmitResults { groups: results })
    }
}

/// Builder for an ordered same-signer sequence. Standalone — does not borrow Submit.
pub struct Ops {
    signer: Signer,
    calls: Vec<Box<dyn CallExpr>>,
    group_index: Rc<Cell<usize>>,
}

impl Ops {
    pub fn new(signer: &Signer) -> Self {
        Self {
            signer: signer.clone(),
            calls: Vec::new(),
            group_index: Rc::new(Cell::new(0)),
        }
    }

    pub fn push<T: 'static>(&mut self, call: TypedCall<T>) -> Handle<T> {
        let parse = call.parse;
        let op_index = self.calls.len();
        self.calls.push(Box::new(call));
        Handle {
            group_index: self.group_index.clone(),
            op_index,
            parse,
        }
    }
}

/// Builder for an ordered multi-signer sequence (BLS aggregate). Standalone.
pub struct AggregateOps {
    calls: Vec<(Signer, Box<dyn CallExpr>)>,
    group_index: Rc<Cell<usize>>,
}

impl AggregateOps {
    pub fn new() -> Self {
        Self {
            calls: Vec::new(),
            group_index: Rc::new(Cell::new(0)),
        }
    }

    pub fn push<T: 'static>(&mut self, signer: &Signer, call: TypedCall<T>) -> Handle<T> {
        let parse = call.parse;
        let op_index = self.calls.len();
        self.calls.push((signer.clone(), Box::new(call)));
        Handle {
            group_index: self.group_index.clone(),
            op_index,
            parse,
        }
    }
}

/// Wrapper for passing either Ops or AggregateOps to Submit::add.
pub enum OpsGroup {
    Direct(Ops),
    Aggregate(AggregateOps),
}

impl From<Ops> for OpsGroup {
    fn from(ops: Ops) -> Self {
        OpsGroup::Direct(ops)
    }
}

impl From<AggregateOps> for OpsGroup {
    fn from(ops: AggregateOps) -> Self {
        OpsGroup::Aggregate(ops)
    }
}
