// Generated by uniffi-bindgen-react-native
#include "kontor-mobile.h"
#include "/kontor_mobile.hpp"

namespace kontormobile {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeKontorMobile::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}