// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
#pragma once
#include <jsi/jsi.h>
#include <iostream>
#include <map>
#include <memory>
#include <ReactCommon/CallInvoker.h>
#include "UniffiCallInvoker.h"

namespace react = facebook::react;
namespace jsi = facebook::jsi;

class NativeKontorMobile : public jsi::HostObject {
  private:
    // For calling back into JS from Rust.
    std::shared_ptr<uniffi_runtime::UniffiCallInvoker> callInvoker;

  protected:
    std::map<std::string,jsi::Value> props;
    jsi::Value cpp_uniffi_internal_fn_func_ffi__string_to_byte_length(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_func_ffi__string_to_arraybuffer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_func_ffi__arraybuffer_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_clone_wit(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_free_wit(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_constructor_wit_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_method_wit_decode_result(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_method_wit_encode_call(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_add_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_add_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_aggregate_signing_message(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_bls_aggregate_signatures(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_bls_pubkey_from_secret(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_bls_secret_from_seed_eip2333(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_bls_secret_key_gen(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_bls_sign(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_bls_verify(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_cmp_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_cmp_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_decimal_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_decimal_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_deserialize_inst(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_div_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_div_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_eq_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_eq_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_f64_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_integer_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_integer_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_log10_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_mul_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_mul_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_s64_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_s64_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_serialize_inst(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_sqrt_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_string_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_string_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_sub_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_sub_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_u64_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_fn_func_u64_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_add_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_add_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_aggregate_signing_message(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_bls_aggregate_signatures(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_bls_pubkey_from_secret(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_bls_secret_from_seed_eip2333(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_bls_secret_key_gen(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_bls_sign(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_bls_verify(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_cmp_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_cmp_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_decimal_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_decimal_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_deserialize_inst(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_div_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_div_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_eq_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_eq_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_f64_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_integer_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_integer_to_string(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_log10_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_mul_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_mul_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_s64_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_s64_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_serialize_inst(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_sqrt_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_string_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_string_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_sub_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_sub_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_u64_to_decimal(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_func_u64_to_integer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_method_wit_decode_result(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_method_wit_encode_call(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_kontor_mobile_checksum_constructor_wit_new(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_ffi_kontor_mobile_uniffi_contract_version(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);
    jsi::Value cpp_uniffi_internal_fn_method_wit_ffi__bless_pointer(jsi::Runtime& rt, const jsi::Value& thisVal, const jsi::Value* args, size_t count);

  public:
    NativeKontorMobile(jsi::Runtime &rt, std::shared_ptr<uniffi_runtime::UniffiCallInvoker> callInvoker);
    virtual ~NativeKontorMobile();

    /**
     * The entry point into the crate.
     *
     * React Native must call `NativeKontorMobile.registerModule(rt, callInvoker)` before using
     * the Javascript interface.
     */
    static void registerModule(jsi::Runtime &rt, std::shared_ptr<react::CallInvoker> callInvoker);

    /**
     * Some cleanup into the crate goes here.
     *
     * Current implementation is empty, however, this is not guaranteed to always be the case.
     *
     * Clients should call `NativeKontorMobile.unregisterModule(rt)` after final use where possible.
     */
    static void unregisterModule(jsi::Runtime &rt);

    virtual jsi::Value get(jsi::Runtime& rt, const jsi::PropNameID& name);
    virtual void set(jsi::Runtime& rt,const jsi::PropNameID& name,const jsi::Value& value);
    virtual std::vector<jsi::PropNameID> getPropertyNames(jsi::Runtime& rt);
};