//! `IndexedMap<K, V>` — a height-versioned `Map<K, V>` plus framework-maintained
//! secondary indexes, so filtered reads are prefix scans of a declared index
//! rather than a `keys()` scan-and-filter.
//!
//! Layout (all ordinary path-prefixed `contract_state` rows, so versioned,
//! reorg-safe, and folded into the checkpoint hash):
//! ```text
//!   <primary>/<key>                        -> V
//!   <primary>#idx/<index_name>/<index_key>/<key> -> ()   (sibling of <primary>)
//! ```
//! `by_index(name, key)` scans `<primary>#idx/<name>/<key>/`, whose child
//! segments ARE the primary keys. A key's index memberships are derived from its
//! value via [`Indexed`] — there is no separate record of them, so the value
//! stays the one source of truth (same as every other generated model). On
//! update the prior entries are recomputed and diffed against the new ones via
//! [`apply_index_diff`]: delete `old − new`, write `new − old`, so an unchanged
//! index (or a no-op re-set) costs zero index ops.
//!
//! Like [`StorageMap`](crate::StorageMap), the type a contract declares is an
//! inert placeholder; the real per-key `get`/`set`/`remove`/`by_index` accessors
//! are generated by the `#[derive(Model)]` field model. The only logic carried
//! here is (a) [`apply_index_diff`], the single audited maintenance routine both
//! the field model and the bulk [`Store`] impl call, and (b) the [`Store`] impl
//! below, which keeps a *wholesale* write of the map (root init, or any nested
//! struct set through `Store`) index-consistent — the field model's per-key path
//! can't catch that.

use alloc::format;
use alloc::rc::Rc;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::marker::PhantomData;
use core::str::FromStr;

use crate::{DotPathBuf, Store, WriteStorage};

/// A value's secondary-index memberships: `(index_name, index_key)` pairs.
/// An empty result means "in no index" — partial indexes fall out by omitting
/// the pair when a predicate is false. `index_key` becomes a path segment, so
/// it must serialise deterministically (reproducible across nodes) and without
/// the path delimiter (`.`); [`apply_index_diff`] enforces the latter.
pub trait Indexed {
    fn index_entries(&self) -> Vec<(&'static str, String)>;
}

/// A path segment carries one index/primary key. `.` is the path delimiter, so a
/// key containing it would silently split into extra segments and alias or
/// corrupt the index. Indexes are only correct if their keys are delimiter-free,
/// so we reject the violation loudly rather than store an unfindable row.
fn assert_segment(s: &str) {
    assert!(
        !s.contains('.'),
        "index/primary key must not contain the path delimiter '.': {s:?}"
    );
}

/// Reconcile one key's index rows from `old` to `new`: delete entries in `old`
/// that aren't in `new`, write entries in `new` that weren't in `old`. Unchanged
/// entries are left untouched (zero ops). Index roots are siblings of the
/// primary map.
///
/// The caller computes `old`/`new`: the field model reads the old value's
/// indexed fields through its generated model; the bulk [`Store`] impl starts
/// from empty (a fresh wholesale write). Either way the maintenance logic lives
/// only here.
pub fn apply_index_diff<S: WriteStorage + ?Sized>(
    ctx: &Rc<S>,
    index_root: &DotPathBuf,
    key: &str,
    old: &[(&'static str, String)],
    new: &[(&'static str, String)],
) {
    assert_segment(key);
    for (name, index_key) in old {
        if !new.iter().any(|(n, k)| n == name && k == index_key) {
            ctx.__delete(&index_root.push(*name).push(index_key).push(key));
        }
    }
    for (name, index_key) in new {
        assert_segment(index_key);
        if !old.iter().any(|(n, k)| n == name && k == index_key) {
            ctx.__set_void(&index_root.push(*name).push(index_key).push(key));
        }
    }
}

/// Inert placeholder a contract declares as an `IndexedMap<K, V>` field (the
/// `contract!` preamble aliases `IndexedMap` to this). Holds no live data — the
/// generated field model is the real accessor — except when written wholesale,
/// where the [`Store`] impl maintains the index.
pub struct StorageIndexedMap<K, V, S: ?Sized> {
    pub entries: Vec<(K, V)>,
    pub _marker: PhantomData<S>,
}

impl<K, V, S: ?Sized> StorageIndexedMap<K, V, S>
where
    K: Clone,
    V: Clone,
{
    pub fn new(entries: &[(K, V)]) -> Self {
        StorageIndexedMap {
            entries: entries.to_vec(),
            _marker: PhantomData,
        }
    }
}

impl<K: Clone, V: Clone, S: ?Sized> Clone for StorageIndexedMap<K, V, S> {
    fn clone(&self) -> Self {
        Self {
            entries: self.entries.clone(),
            _marker: PhantomData,
        }
    }
}

impl<K, V, S: ?Sized> Default for StorageIndexedMap<K, V, S> {
    fn default() -> Self {
        Self {
            entries: Vec::new(),
            _marker: PhantomData,
        }
    }
}

impl<K, V, S> Store<S> for StorageIndexedMap<K, V, S>
where
    K: ToString + FromStr + Clone,
    V: Store<S> + Clone + Indexed,
    S: WriteStorage + ?Sized,
{
    /// Wholesale write: persist every entry's value AND its index rows, so a map
    /// populated before `init` (at the root or any nested level) lands
    /// index-consistent. The index root is the `<primary>#idx` sibling, derived
    /// from `base_path` the same way the field model builds it. This is an
    /// upsert from empty — it adds rows, it doesn't reconcile against existing
    /// ones; per-key updates that must diff go through the field model's `set`.
    fn __set(ctx: &Rc<S>, base_path: DotPathBuf, value: StorageIndexedMap<K, V, S>) {
        let (parent, last) = base_path.pop();
        let Some(last) = last else { return };
        let index_root = parent.push(format!("{last}#idx"));
        for (k, v) in value.entries.into_iter() {
            let key_str = k.to_string();
            let new_entries = v.index_entries();
            apply_index_diff(ctx, &index_root, &key_str, &[], &new_entries);
            ctx.__set(base_path.push(key_str.as_str()), v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ReadStorage;
    use alloc::collections::BTreeMap;
    use alloc::vec;
    use core::cell::RefCell;
    use core::fmt::Debug;

    #[derive(Clone)]
    enum Cell {
        U64(u64),
        Void,
    }

    #[derive(Default)]
    struct Mock {
        map: RefCell<BTreeMap<String, Cell>>,
        void_sets: RefCell<usize>,
        deletes: RefCell<usize>,
    }

    impl ReadStorage for Mock {
        fn __get_u64(self: &Rc<Self>, path: &str) -> Option<u64> {
            match self.map.borrow().get(path) {
                Some(Cell::U64(v)) => Some(*v),
                _ => None,
            }
        }
        fn __get_keys<T: ToString + FromStr + Clone>(
            self: &Rc<Self>,
            path: &str,
        ) -> impl Iterator<Item = T> + use<T>
        where
            <T as FromStr>::Err: Debug,
        {
            let prefix = format!("{path}.");
            let mut segs: Vec<String> = self
                .map
                .borrow()
                .keys()
                .filter_map(|k| k.strip_prefix(&prefix))
                .map(|rest| rest.split('.').next().unwrap().to_string())
                .collect();
            segs.sort();
            segs.dedup();
            segs.into_iter().map(|s| T::from_str(&s).unwrap())
        }
        fn __get<T: crate::Retrieve<Self>>(self: &Rc<Self>, path: DotPathBuf) -> Option<T> {
            T::__get(self, path)
        }
        fn __get_str(self: &Rc<Self>, _: &str) -> Option<String> {
            unimplemented!()
        }
        fn __get_s64(self: &Rc<Self>, _: &str) -> Option<i64> {
            unimplemented!()
        }
        fn __get_bool(self: &Rc<Self>, _: &str) -> Option<bool> {
            unimplemented!()
        }
        fn __get_list_u8(self: &Rc<Self>, _: &str) -> Option<Vec<u8>> {
            unimplemented!()
        }
        fn __exists(self: &Rc<Self>, path: &str) -> bool {
            self.map.borrow().contains_key(path)
        }
        fn __extend_path_with_match(self: &Rc<Self>, _: &str, _: &[&str]) -> Option<String> {
            unimplemented!()
        }
    }

    impl WriteStorage for Mock {
        fn __set_u64(self: &Rc<Self>, path: &str, value: u64) {
            self.map
                .borrow_mut()
                .insert(path.to_string(), Cell::U64(value));
        }
        fn __set_void(self: &Rc<Self>, path: &str) {
            *self.void_sets.borrow_mut() += 1;
            self.map.borrow_mut().insert(path.to_string(), Cell::Void);
        }
        fn __delete(self: &Rc<Self>, path: &str) -> bool {
            *self.deletes.borrow_mut() += 1;
            self.map.borrow_mut().remove(path).is_some()
        }
        fn __set<T: Store<Self>>(self: &Rc<Self>, path: DotPathBuf, value: T) {
            T::__set(self, path, value)
        }
        fn __set_str(self: &Rc<Self>, _: &str, _: &str) {
            unimplemented!()
        }
        fn __set_s64(self: &Rc<Self>, _: &str, _: i64) {
            unimplemented!()
        }
        fn __set_bool(self: &Rc<Self>, _: &str, _: bool) {
            unimplemented!()
        }
        fn __set_list_u8(self: &Rc<Self>, _: &str, _: Vec<u8>) {
            unimplemented!()
        }
        fn __delete_matching_paths(self: &Rc<Self>, _: &str, _: &[&str]) -> u64 {
            unimplemented!()
        }
    }

    fn p(s: &str) -> DotPathBuf {
        DotPathBuf::new().push(s)
    }

    // A struct value with one indexed field — the shape an IndexedMap holds.
    #[derive(Clone)]
    struct Position {
        status: u64,
    }

    impl Store<Mock> for Position {
        fn __set(ctx: &Rc<Mock>, base_path: DotPathBuf, value: Position) {
            ctx.__set(base_path.push("status"), value.status);
        }
    }

    impl Indexed for Position {
        fn index_entries(&self) -> Vec<(&'static str, String)> {
            vec![("status", self.status.to_string())]
        }
    }

    // Drive `apply_index_diff` directly — the routine both the field model and
    // the bulk Store impl delegate to.
    #[test]
    fn apply_index_diff_reconciles_entries() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // From nothing -> {status:active, owner:1}: two writes.
        apply_index_diff(
            &ctx,
            &index,
            "k",
            &[],
            &[("status", "active".to_string()), ("owner", "1".to_string())],
        );
        assert_eq!(*ctx.void_sets.borrow(), 2);
        assert_eq!(*ctx.deletes.borrow(), 0);

        // {active,1} -> {proven,1}: only status moves (1 delete + 1 write); owner
        // is unchanged and untouched.
        apply_index_diff(
            &ctx,
            &index,
            "k",
            &[("status", "active".to_string()), ("owner", "1".to_string())],
            &[("status", "proven".to_string()), ("owner", "1".to_string())],
        );
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(*ctx.void_sets.borrow(), 3); // 2 + 1

        // A no-op re-set (old == new) touches nothing.
        *ctx.void_sets.borrow_mut() = 0;
        *ctx.deletes.borrow_mut() = 0;
        let same = [("status", "proven".to_string()), ("owner", "1".to_string())];
        apply_index_diff(&ctx, &index, "k", &same, &same);
        assert_eq!(*ctx.deletes.borrow(), 0);
        assert_eq!(*ctx.void_sets.borrow(), 0);

        // The status entry moved buckets; the owner entry is still in place.
        assert!(ctx.__exists("t#idx.status.proven.k"));
        assert!(!ctx.__exists("t#idx.status.active.k"));
        assert!(ctx.__exists("t#idx.owner.1.k"));
    }

    // The bulk `Store` path: a map populated before a wholesale write must land
    // with both its primary values and its index rows.
    #[test]
    fn bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let m = StorageIndexedMap::<u64, Position, Mock>::new(&[
            (1, Position { status: 2 }),
            (2, Position { status: 2 }),
            (3, Position { status: 5 }),
        ]);

        Store::__set(&ctx, p("positions"), m);

        // Primary values (stored under the value's own field path).
        assert_eq!(ctx.__get_u64("positions.1.status"), Some(2));
        assert_eq!(ctx.__get_u64("positions.3.status"), Some(5));

        // Index rows, in the `#idx` sibling.
        assert!(ctx.__exists("positions#idx.status.2.1"));
        assert!(ctx.__exists("positions#idx.status.2.2"));
        assert!(ctx.__exists("positions#idx.status.5.3"));

        // by_index resolves to the primary keys.
        let bucket = p("positions#idx").push("status").push("2");
        let mut keys: Vec<u64> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, vec![1, 2]);
    }

    // An IndexedMap nested inside a struct. Its `Store::__set` writes the field
    // wholesale, the way a derived struct `Store` does — this is the recursive
    // bulk path that the field model's per-key writes can't see.
    #[derive(Clone, Default)]
    struct Account {
        positions: StorageIndexedMap<u64, Position, Mock>,
    }

    impl Store<Mock> for Account {
        fn __set(ctx: &Rc<Mock>, base_path: DotPathBuf, value: Account) {
            ctx.__set(base_path.push("positions"), value.positions);
        }
    }

    // The recursive case: writing a struct wholesale must keep a *nested*
    // IndexedMap index-consistent, with the index sibling derived at the right
    // depth (`account.positions#idx`, not `positions#idx`).
    #[test]
    fn nested_bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let account = Account {
            positions: StorageIndexedMap::new(&[
                (1, Position { status: 2 }),
                (2, Position { status: 5 }),
            ]),
        };

        Store::__set(&ctx, p("account"), account);

        // Primary values land under the nested path.
        assert_eq!(ctx.__get_u64("account.positions.1.status"), Some(2));

        // Index rows are the `#idx` sibling *at depth* — same path the field
        // model would build (parent `account` + `positions#idx`).
        assert!(ctx.__exists("account.positions#idx.status.2.1"));
        assert!(ctx.__exists("account.positions#idx.status.5.2"));

        let bucket = p("account.positions#idx").push("status").push("2");
        assert_eq!(ctx.__get_keys::<u64>(&bucket).collect::<Vec<_>>(), vec![1]);
    }

    // An IndexedMap reached through a plain `Map` *value*. Bulk-writing a
    // `Map<K, Account>` flows through the UNMODIFIED `StorageMap::__set`, which
    // dispatches each value to `Account::__set`, which reaches the nested
    // IndexedMap's index-aware `Store`. The index must still be maintained.
    #[test]
    fn indexed_map_in_map_value_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let accounts = crate::StorageMap::<u64, Account, Mock>::new(&[
            (
                7,
                Account {
                    positions: StorageIndexedMap::new(&[(1, Position { status: 2 })]),
                },
            ),
            (
                8,
                Account {
                    positions: StorageIndexedMap::new(&[(1, Position { status: 5 })]),
                },
            ),
        ]);

        Store::__set(&ctx, p("accounts"), accounts);

        // Inner index rows land at the nested depth for each map entry.
        assert!(ctx.__exists("accounts.7.positions#idx.status.2.1"));
        assert!(ctx.__exists("accounts.8.positions#idx.status.5.1"));
        assert_eq!(ctx.__get_u64("accounts.7.positions.1.status"), Some(2));
    }

    // A plain `Map` nested inside an IndexedMap *value*. The outer index is keyed
    // off the value (`tag`); the inner map is just data. Both must persist.
    #[derive(Clone, Default)]
    struct Bag {
        tag: u64,
        items: crate::StorageMap<u64, u64, Mock>,
    }

    impl Store<Mock> for Bag {
        fn __set(ctx: &Rc<Mock>, base_path: DotPathBuf, value: Bag) {
            ctx.__set(base_path.push("tag"), value.tag);
            ctx.__set(base_path.push("items"), value.items);
        }
    }

    impl Indexed for Bag {
        fn index_entries(&self) -> Vec<(&'static str, String)> {
            vec![("tag", self.tag.to_string())]
        }
    }

    #[test]
    fn map_in_indexed_map_value() {
        let ctx = Rc::new(Mock::default());
        let bags = StorageIndexedMap::<u64, Bag, Mock>::new(&[(
            1,
            Bag {
                tag: 9,
                items: crate::StorageMap::new(&[(100, 1), (200, 2)]),
            },
        )]);

        Store::__set(&ctx, p("bags"), bags);

        // Outer index maintained by the value's `tag`.
        assert!(ctx.__exists("bags#idx.tag.9.1"));
        // Inner map data persisted under the value's path.
        assert_eq!(ctx.__get_u64("bags.1.items.100"), Some(1));
        assert_eq!(ctx.__get_u64("bags.1.items.200"), Some(2));
    }

    #[test]
    #[should_panic(expected = "path delimiter")]
    fn rejects_dotted_index_key() {
        let ctx = Rc::new(Mock::default());
        apply_index_diff(&ctx, &p("t#idx"), "k", &[], &[("name", "a.b".to_string())]);
    }
}
