//! `IndexedMap<K, V>` — a height-versioned `Map<K, V>` plus framework-maintained
//! secondary indexes, so filtered reads are prefix scans of a declared index
//! rather than a `keys()` scan-and-filter.
//!
//! Layout (all ordinary path-prefixed `contract_state` rows, so versioned,
//! reorg-safe, and folded into the checkpoint hash):
//! ```text
//!   <primary>/<key>                        -> V
//!   <primary>#idx/<index_name>/<index_key>/<key> -> ()   (sibling of <primary>)
//! ```
//! `by_index(name, key)` scans `<primary>#idx/<name>/<key>/`, whose child
//! segments ARE the primary keys. A key's index memberships are derived from its
//! value via [`Indexed`] — there is no separate record of them, so the value
//! stays the one source of truth (same as every other generated model). On
//! update the prior entries are recomputed and diffed against the new ones via
//! [`apply_index_diff`]: delete `old − new`, write `new − old`, so an unchanged
//! index (or a no-op re-set) costs zero index ops.
//!
//! Like [`StorageMap`](crate::StorageMap), the type a contract declares is an
//! inert placeholder; the real per-key `get`/`set`/`remove`/`by_index` accessors
//! are generated by the `#[derive(Model)]` field model. The only logic carried
//! here is (a) [`apply_index_diff`], the single audited maintenance routine both
//! the field model and the bulk [`Store`] impl call, and (b) the [`Store`] impl
//! below, which keeps a *wholesale* write of the map (root init, or any nested
//! struct set through `Store`) index-consistent — the field model's per-key path
//! can't catch that.

use alloc::borrow::Cow;
use alloc::format;
use alloc::rc::Rc;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::str::FromStr;

use crate::{DotPathBuf, ReadStorage, Store, WriteStorage};

/// The canonical string a value contributes to an index bucket. The SINGLE
/// source every index path stringifies through — a value's
/// [`Indexed::index_entries`], the read model's `__index_entries`, the in-place
/// indexed-field setter, and the generated `where_<field>` lookup — so the
/// bucket a write lands in and the bucket a lookup scans can never drift.
///
/// Primitives key by their `Display`. A storage enum keys by its DISCRIMINANT
/// (case name), not its payload — so a payload-carrying case like `Failed(r)`
/// always lands in bucket `"failed"`, and changing the payload is a no-op for
/// the index. The `Storage` derive supplies that impl (and a payload-free
/// `<E>Kind` marker for referencing a case without constructing one).
///
/// Returns `Cow` so an enum discriminant (a `&'static str`) costs no allocation
/// — the hot case, since the key is built on every `set`/`where_` just to compare
/// or borrow as `&str`. Primitives still own (their `Display` allocates anyway).
pub trait IndexKey {
    fn index_key(&self) -> Cow<'static, str>;
}

macro_rules! index_key_via_display {
    ($($t:ty),*) => {
        $(
            impl IndexKey for $t {
                fn index_key(&self) -> Cow<'static, str> {
                    Cow::Owned(ToString::to_string(self))
                }
            }
        )*
    };
}

// Primitive index keys are just their `Display`. (No blanket `impl<T: Display>`
// — that would collide with the discriminant impl the `Storage` derive
// generates for enums.)
index_key_via_display!(bool, u64, i64, u32, i32, String, str, &str);

/// An `Option<T>` indexes by its `none`/`some` **discriminant** (like an enum
/// keys by its case), ignoring the payload — so a composite index can partition
/// on "is this field set?" without a predicate DSL. Keys match [`Presence`], the
/// payload-free marker a `where_*` lookup passes, so the bucket a write lands in
/// and the bucket a lookup scans agree. Blanket over all `T`: `Option` is neither
/// a keyed primitive nor a storage enum, so no impl overlaps it.
impl<T> IndexKey for Option<T> {
    fn index_key(&self) -> Cow<'static, str> {
        match self {
            None => Cow::Borrowed("none"),
            Some(_) => Cow::Borrowed("some"),
        }
    }
}

/// The payload-free marker for bucketing an `Option` index field by presence —
/// the `Option` analogue of a storage enum's `<E>Kind`. Lets a lookup name the
/// bucket (`where_eligible(true, Presence::Absent)`) without constructing an
/// `Option` value or writing `None::<T>` with a turbofish. Its [`IndexKey`]
/// matches `Option`'s, so lookup and stored bucket can't drift.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Presence {
    Absent,
    Present,
}

impl IndexKey for Presence {
    fn index_key(&self) -> Cow<'static, str> {
        match self {
            Presence::Absent => Cow::Borrowed("none"),
            Presence::Present => Cow::Borrowed("some"),
        }
    }
}

/// An **order-preserving, fixed-width** path segment for *ordering* members
/// within an index bucket: the lexicographic byte order of `sort_key()` equals
/// the numeric order of the value. This is what lets a sortable index scan in
/// value order and early-break, while storage stays the generic `contract_state`
/// log (sortability lives in the key, never a column).
///
/// Distinct from [`IndexKey`], which only needs a *distinct, delimiter-free*
/// bucket segment — order irrelevant. A field can be both (a `u64` buckets via
/// `Display`, orders via `SortKey`).
///
/// Encoded as fixed-width **hex** so the segment is path-safe (printable, no
/// `.`); `WIDTH` is the exact char count, which the scan strips to recover the
/// primary key from a `<sort‖pk>` member segment. Signed types are sign-biased
/// (flip the sign bit) so negatives sort before positives.
pub trait SortKey: Sized {
    /// Exact character width of every `sort_key()` for this type. Part of an
    /// index's on-disk format (fixed for the life of the immutable contract).
    const WIDTH: usize;
    fn sort_key(&self) -> String;
    /// Decode a `sort_key()` back to the value — the inverse of [`sort_key`], so a
    /// fixed-width segment can carry a value that's recovered, not just compared
    /// (e.g. the `B` tail of a [`Pair`] compound key). Panics on a malformed
    /// segment, surfacing storage corruption rather than masking it.
    ///
    /// [`sort_key`]: SortKey::sort_key
    fn from_sort_key(segment: &str) -> Self;
}

macro_rules! sort_key_unsigned {
    ($($t:ty => $width:expr),* $(,)?) => {
        $(
            impl SortKey for $t {
                const WIDTH: usize = $width;
                fn sort_key(&self) -> String {
                    alloc::format!("{:0width$x}", self, width = $width)
                }
                fn from_sort_key(segment: &str) -> Self {
                    <$t>::from_str_radix(segment, 16).expect("malformed SortKey segment")
                }
            }
        )*
    };
}
sort_key_unsigned!(u8 => 2, u16 => 4, u32 => 8, u64 => 16);

macro_rules! sort_key_signed {
    ($($t:ty => $unsigned:ty, $width:expr),* $(,)?) => {
        $(
            impl SortKey for $t {
                const WIDTH: usize = $width;
                fn sort_key(&self) -> String {
                    // Bias by 2^(bits-1) (flip the sign bit) so the most-negative
                    // value maps to all-zero hex and ordering is preserved.
                    let biased = (*self as $unsigned) ^ (1 as $unsigned).rotate_right(1);
                    alloc::format!("{:0width$x}", biased, width = $width)
                }
                fn from_sort_key(segment: &str) -> Self {
                    // Inverse of `sort_key`: decode the hex, then un-bias (XOR is its
                    // own inverse) and cast back to the signed type.
                    let biased = <$unsigned>::from_str_radix(segment, 16)
                        .expect("malformed SortKey segment");
                    (biased ^ (1 as $unsigned).rotate_right(1)) as $t
                }
            }
        )*
    };
}
sort_key_signed!(i8 => u8, 2, i16 => u16, 4, i32 => u32, 8, i64 => u64, 16);

/// A two-part primary key `(A, B)` for `IndexedMap`/`Map`, encoded delimiter-safe
/// as `<A><fixed-width B>`: `A`'s `Display` (which must be `.`-free — `.` is the
/// path delimiter, and `push` rejects it) followed by `B`'s fixed-width
/// [`SortKey`]. Recovered by splitting the known-width `B` suffix off the tail
/// (unambiguous because `B` is fixed width and `A` is `.`-free). Sorts by `A` then
/// `B`, so primary `keys()` iteration is ordered without `Pair` itself being a
/// `SortKey`.
///
/// `A` is the *variable* part (typically a `String`); `B` the fixed-width part (a
/// numeric `SortKey`) — e.g. `Pair<String, u64>` for `(agreement_id, node_id)`.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Pair<A, B>(pub A, pub B);

impl<A, B> Pair<A, B> {
    pub fn new(a: A, b: B) -> Self {
        Pair(a, b)
    }
}

impl<A: core::fmt::Display, B: SortKey> core::fmt::Display for Pair<A, B> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}{}", self.0, self.1.sort_key())
    }
}

impl<A, B> FromStr for Pair<A, B>
where
    A: FromStr,
    <A as FromStr>::Err: core::fmt::Debug,
    B: SortKey,
{
    type Err = String;

    fn from_str(s: &str) -> Result<Self, String> {
        if s.len() < B::WIDTH {
            return Err(alloc::format!(
                "Pair key {s:?} shorter than its {}-char B suffix",
                B::WIDTH
            ));
        }
        // `B::WIDTH` ASCII hex chars at the tail ⇒ the split is always on a char
        // boundary, even when `A` carries multi-byte UTF-8.
        let (a, b) = s.split_at(s.len() - B::WIDTH);
        let a = A::from_str(a).map_err(|e| alloc::format!("Pair key A part {a:?}: {e:?}"))?;
        Ok(Pair(a, B::from_sort_key(b)))
    }
}

/// An ordered scan over a *sorted* index bucket. The bucket's child segments are
/// `<sort‖pk>` (a fixed-width [`SortKey`] prefix followed by the primary key),
/// already handed back in ascending path order by `keys()`. The scan strips the
/// prefix — exactly [`SortKey::WIDTH`] chars for the sort type `S` — to recover
/// each primary key `K`.
///
/// Iterating it directly walks the whole bucket in sort order. [`up_to`] /
/// [`range`] bound it by comparing the **encoded** SortKey prefix — a plain
/// string compare, no decode — and early-break, so the contract pays only for the
/// members it keeps (the host still materializes the bucket; see the module's
/// cost note). The bound is typed `S` — the index's own sort field type — so its
/// encoding can't be a different width than the stored prefix, and passing the
/// wrong integer type is a compile error rather than a silent miscompare.
///
/// [`up_to`]: SortedScan::up_to
/// [`range`]: SortedScan::range
pub struct SortedScan<K, S> {
    // Boxed so the generated `where_<index>` can name a single return type
    // (`SortedScan<K, S>`) without threading the concrete `keys()` iterator type
    // through the lookup trait. One box per scan — negligible next to the bucket
    // walk it wraps.
    segments: alloc::boxed::Box<dyn Iterator<Item = String>>,
    _key: core::marker::PhantomData<K>,
    _sort: core::marker::PhantomData<S>,
}

impl<K, S> SortedScan<K, S>
where
    K: FromStr,
    <K as FromStr>::Err: core::fmt::Debug,
    S: SortKey,
{
    pub fn new(segments: alloc::boxed::Box<dyn Iterator<Item = String>>) -> Self {
        Self {
            segments,
            _key: core::marker::PhantomData,
            _sort: core::marker::PhantomData,
        }
    }

    /// Members whose sort value is `≤ bound`, in ascending order. Early-breaks at
    /// the first member above the bound — nothing later in a sorted bucket can
    /// qualify.
    pub fn up_to(self, bound: S) -> impl Iterator<Item = K> {
        let bound = bound.sort_key();
        self.segments
            .take_while(move |seg| seg[..S::WIDTH] <= bound[..])
            .map(|seg| K::from_str(&seg[S::WIDTH..]).unwrap())
    }

    /// Members whose sort value is within `range` (inclusive), in ascending order.
    /// Skips below `lo`, then early-breaks past `hi`.
    pub fn range(self, range: core::ops::RangeInclusive<S>) -> impl Iterator<Item = K> {
        let lo = range.start().sort_key();
        let hi = range.end().sort_key();
        self.segments
            .skip_while(move |seg| seg[..S::WIDTH] < lo[..])
            .take_while(move |seg| seg[..S::WIDTH] <= hi[..])
            .map(|seg| K::from_str(&seg[S::WIDTH..]).unwrap())
    }
}

impl<K, S> Iterator for SortedScan<K, S>
where
    K: FromStr,
    <K as FromStr>::Err: core::fmt::Debug,
    S: SortKey,
{
    type Item = K;

    /// Unbounded walk of the bucket in sort order.
    fn next(&mut self) -> Option<K> {
        self.segments
            .next()
            .map(|seg| K::from_str(&seg[S::WIDTH..]).unwrap())
    }
}

/// One secondary-index membership of a value: which index, which bucket, and
/// (optionally) where it sorts within that bucket. The leaf it maps to is
/// `<index>/<bucket…>/<sort‖pk>` (see the `IndexedMap` module docs). All segments
/// must be delimiter-free (`.`); [`apply_index_diff`] enforces it.
///
/// `bucket` is a vec so a composite index can partition on several fields (one
/// segment each, in declared order); a single-field index has one. `sort` is the
/// fixed-width [`SortKey`] segment prepended to the primary key in the member
/// segment, so the bucket scans in value order. (A covering projection will be
/// added here later as the leaf *value*; the diff already keys on the leaf path
/// so that stays additive.)
pub struct IndexEntry {
    pub name: &'static str,
    pub bucket: Vec<Cow<'static, str>>,
    pub sort: Option<Cow<'static, str>>,
}

impl IndexEntry {
    /// The bucket-prefix path `<index>/<bucket…>` (where the count lives; members
    /// are its children).
    fn bucket_path(&self, index_root: &DotPathBuf) -> DotPathBuf {
        let mut path = index_root.push(self.name);
        for segment in &self.bucket {
            path = path.push(segment.as_ref());
        }
        path
    }

    /// The member segment `<sort‖pk>`: the sort key (fixed width) prepended to the
    /// primary key, or just the primary key when unsorted.
    fn member_segment(&self, key: &str) -> String {
        match &self.sort {
            Some(sort) => alloc::format!("{sort}{key}"),
            None => key.to_string(),
        }
    }

    /// Two entries share a leaf (same `<index>/<bucket…>/<sort‖pk>`) iff they agree
    /// on name+bucket+sort. The diff keys on this; a future covering projection is
    /// the leaf *value*, updated in place when the path matches.
    fn same_leaf(&self, other: &IndexEntry) -> bool {
        self.name == other.name && self.bucket == other.bucket && self.sort == other.sort
    }
}

/// A value's secondary-index memberships. An empty result means "in no index" —
/// partial indexes fall out by omitting an entry when a predicate is false.
pub trait Indexed {
    fn index_entries(&self) -> Vec<IndexEntry>;
}

/// A path segment carries one index/primary key. `.` is the path delimiter, so a
/// key containing it would silently split into extra segments and alias or
/// corrupt the index. Indexes are only correct if their keys are delimiter-free,
/// so we reject the violation loudly rather than store an unfindable row.
fn assert_segment(s: &str) {
    assert!(
        !s.contains('.'),
        "index/primary key must not contain the path delimiter '.': {s:?}"
    );
}

/// Reconcile one key's index rows from `old` to `new`: delete entries in `old`
/// that aren't in `new`, write entries in `new` that weren't in `old`. Unchanged
/// entries are left untouched (zero ops). Index roots are siblings of the
/// primary map.
///
/// The caller computes `old`/`new`: the field model's `set`/`remove` load the
/// prior value and read its `Indexed::index_entries`; an in-place indexed-field
/// setter diffs just that field's entry; the bulk [`Store`] impl starts from
/// empty (a fresh wholesale write). Either way the maintenance logic lives only
/// here.
pub fn apply_index_diff<S: WriteStorage + ReadStorage + ?Sized>(
    ctx: &Rc<S>,
    index_root: &DotPathBuf,
    key: &str,
    old: &[IndexEntry],
    new: &[IndexEntry],
) {
    assert_segment(key);
    for entry in old {
        if !new.iter().any(|n| n.same_leaf(entry)) {
            let bucket = entry.bucket_path(index_root);
            // Decrement ONLY when the delete actually removed a live row.
            // `__delete` returns false for a no-op (the entry was already
            // tombstoned or never written — an index/count that drifted); counting
            // that as a removal would underflow the bucket count and trap. The
            // delete result is the authority on whether membership changed.
            if ctx.__delete(&bucket.push(entry.member_segment(key))) {
                bump_bucket_count(ctx, &bucket, false);
            }
        }
    }
    for entry in new {
        for segment in &entry.bucket {
            assert_segment(segment);
        }
        if !old.iter().any(|o| o.same_leaf(entry)) {
            let bucket = entry.bucket_path(index_root);
            ctx.__set_void(&bucket.push(entry.member_segment(key)));
            bump_bucket_count(ctx, &bucket, true);
        }
    }
}

/// Adjust a bucket's framework-maintained member count. The count lives AT the
/// bucket-prefix path (`<map>#idx/<name>/<key>`); the bucket's members are its
/// CHILDREN (`…/<key>/<primary_key>`), so this value is invisible to the
/// `by_index` child-scan and to `keys()`. Maintained only here — the one site
/// every index add/remove funnels through (field-model `set`/`remove`, in-place
/// setter, and the bulk `Store`) — so it can't drift from the membership it
/// counts. It's an ordinary height-versioned `contract_state` row, so it rolls
/// back with everything else on a reorg.
fn bump_bucket_count<S: WriteStorage + ReadStorage + ?Sized>(
    ctx: &Rc<S>,
    bucket: &DotPathBuf,
    up: bool,
) {
    let current = ctx.__get_u64(bucket).unwrap_or(0);
    // A decrement always follows a counted insert (reorgs roll the count row back
    // as versioned state, they don't decrement), so underflow can only mean a
    // framework bug. Trap loudly and deterministically rather than clamp and let a
    // wrong count drive wrong decisions — surfacing corruption, not masking it.
    let next = if up {
        current + 1
    } else {
        current
            .checked_sub(1)
            .expect("IndexedMap bucket count underflow — framework bug")
    };
    ctx.__set_u64(bucket, next);
}

storage_placeholder!(
    /// Inert placeholder a contract declares as an `IndexedMap<K, V>` field (the
    /// `contract!` preamble aliases `IndexedMap` to this). Holds no live data —
    /// the generated field model is the real accessor — except when written
    /// wholesale, where the [`Store`] impl below maintains the index.
    StorageIndexedMap
);

impl<K, V, S> Store<S> for StorageIndexedMap<K, V, S>
where
    K: ToString + FromStr + Clone,
    V: Store<S> + Clone + Indexed,
    S: WriteStorage + ReadStorage + ?Sized,
{
    /// Wholesale write: persist every entry's value AND its index rows, so a map
    /// populated before `init` (at the root or any nested level) lands
    /// index-consistent. The index root is the `<primary>#idx` sibling, derived
    /// from `base_path` the same way the field model builds it. This is an
    /// upsert from empty — it adds rows, it doesn't reconcile against existing
    /// ones; per-key updates that must diff go through the field model's `set`.
    fn __set(ctx: &Rc<S>, base_path: DotPathBuf, value: StorageIndexedMap<K, V, S>) {
        let (parent, last) = base_path.pop();
        let Some(last) = last else { return };
        let index_root = parent.push(format!("{last}#idx"));
        for (k, v) in value.entries.into_iter() {
            let key_str = k.to_string();
            let new_entries = v.index_entries();
            apply_index_diff(ctx, &index_root, &key_str, &[], &new_entries);
            ctx.__set(base_path.push(key_str.as_str()), v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ReadStorage;
    use crate::keycodec::{KeyElement, next_element};
    use alloc::collections::BTreeMap;
    use alloc::vec;
    use core::cell::RefCell;
    use core::fmt::Debug;

    #[derive(Clone)]
    enum Cell {
        U64(u64),
        Void,
    }

    #[derive(Default)]
    struct Mock {
        map: RefCell<BTreeMap<Vec<u8>, Cell>>,
        void_sets: RefCell<usize>,
        deletes: RefCell<usize>,
    }

    impl ReadStorage for Mock {
        fn __get_u64(self: &Rc<Self>, path: &[u8]) -> Option<u64> {
            match self.map.borrow().get(path) {
                Some(Cell::U64(v)) => Some(*v),
                _ => None,
            }
        }
        fn __get_keys<T: ToString + FromStr + Clone>(
            self: &Rc<Self>,
            path: &[u8],
        ) -> impl Iterator<Item = T> + use<T>
        where
            <T as FromStr>::Err: Debug,
        {
            // Distinct child elements: byte-prefix the path, take the next element
            // of the suffix (mirrors the host's `next_element` extraction).
            let mut elems: Vec<Vec<u8>> = self
                .map
                .borrow()
                .keys()
                .filter_map(|k| {
                    let rest = k.as_slice().strip_prefix(path)?;
                    if rest.is_empty() {
                        return None;
                    }
                    Some(next_element(rest).ok()?.0.to_vec())
                })
                .collect();
            elems.sort();
            elems.dedup();
            elems.into_iter().map(|e| {
                let (s, _) = String::decode_from(&e).unwrap();
                T::from_str(&s).unwrap()
            })
        }
        fn __get<T: crate::Retrieve<Self>>(self: &Rc<Self>, path: DotPathBuf) -> Option<T> {
            T::__get(self, path)
        }
        fn __get_str(self: &Rc<Self>, _: &[u8]) -> Option<String> {
            unimplemented!()
        }
        fn __get_s64(self: &Rc<Self>, _: &[u8]) -> Option<i64> {
            unimplemented!()
        }
        fn __get_bool(self: &Rc<Self>, _: &[u8]) -> Option<bool> {
            unimplemented!()
        }
        fn __get_list_u8(self: &Rc<Self>, _: &[u8]) -> Option<Vec<u8>> {
            unimplemented!()
        }
        fn __exists(self: &Rc<Self>, path: &[u8]) -> bool {
            self.map.borrow().contains_key(path)
        }
        fn __extend_path_with_match(self: &Rc<Self>, _: &[u8], _: &[&str]) -> Option<String> {
            unimplemented!()
        }
    }

    impl WriteStorage for Mock {
        fn __set_u64(self: &Rc<Self>, path: &[u8], value: u64) {
            self.map.borrow_mut().insert(path.to_vec(), Cell::U64(value));
        }
        fn __set_void(self: &Rc<Self>, path: &[u8]) {
            *self.void_sets.borrow_mut() += 1;
            self.map.borrow_mut().insert(path.to_vec(), Cell::Void);
        }
        fn __delete(self: &Rc<Self>, path: &[u8]) -> bool {
            *self.deletes.borrow_mut() += 1;
            self.map.borrow_mut().remove(path).is_some()
        }
        fn __set<T: Store<Self>>(self: &Rc<Self>, path: DotPathBuf, value: T) {
            T::__set(self, path, value)
        }
        fn __set_str(self: &Rc<Self>, _: &[u8], _: &str) {
            unimplemented!()
        }
        fn __set_s64(self: &Rc<Self>, _: &[u8], _: i64) {
            unimplemented!()
        }
        fn __set_bool(self: &Rc<Self>, _: &[u8], _: bool) {
            unimplemented!()
        }
        fn __set_list_u8(self: &Rc<Self>, _: &[u8], _: Vec<u8>) {
            unimplemented!()
        }
        fn __delete_matching_paths(self: &Rc<Self>, _: &[u8], _: &[&str]) -> u64 {
            unimplemented!()
        }
    }

    // A path from a dotted string (each piece a segment) → codec bytes.
    fn p(s: &str) -> DotPathBuf {
        DotPathBuf::from(s)
    }

    // Codec bytes for an exact path string (for asserting on the Mock's map).
    fn pb(s: &str) -> Vec<u8> {
        p(s).as_bytes().to_vec()
    }

    // A single-field index entry (one bucket segment, unsorted) — the shape the
    // shipped `#[index]` produces.
    fn e(name: &'static str, key: &str) -> IndexEntry {
        IndexEntry {
            name,
            bucket: alloc::vec![key.to_string().into()],
            sort: None,
        }
    }

    // A struct value with one indexed field — the shape an IndexedMap holds.
    #[derive(Clone)]
    struct Position {
        status: u64,
    }

    impl Store<Mock> for Position {
        fn __set(ctx: &Rc<Mock>, base_path: DotPathBuf, value: Position) {
            ctx.__set(base_path.push("status"), value.status);
        }
    }

    impl Indexed for Position {
        fn index_entries(&self) -> Vec<IndexEntry> {
            alloc::vec![e("status", &self.status.to_string())]
        }
    }

    // Drive `apply_index_diff` directly — the routine both the field model and
    // the bulk Store impl delegate to.
    #[test]
    fn apply_index_diff_reconciles_entries() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // From nothing -> {status:active, owner:1}: two writes.
        apply_index_diff(
            &ctx,
            &index,
            "k",
            &[],
            &[e("status", "active"), e("owner", "1")],
        );
        assert_eq!(*ctx.void_sets.borrow(), 2);
        assert_eq!(*ctx.deletes.borrow(), 0);

        // {active,1} -> {proven,1}: only status moves (1 delete + 1 write); owner
        // is unchanged and untouched.
        apply_index_diff(
            &ctx,
            &index,
            "k",
            &[e("status", "active"), e("owner", "1")],
            &[e("status", "proven"), e("owner", "1")],
        );
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(*ctx.void_sets.borrow(), 3); // 2 + 1

        // A no-op re-set (old == new) touches nothing.
        *ctx.void_sets.borrow_mut() = 0;
        *ctx.deletes.borrow_mut() = 0;
        let same = [e("status", "proven"), e("owner", "1")];
        apply_index_diff(&ctx, &index, "k", &same, &same);
        assert_eq!(*ctx.deletes.borrow(), 0);
        assert_eq!(*ctx.void_sets.borrow(), 0);

        // The status entry moved buckets; the owner entry is still in place.
        assert!(ctx.__exists(&pb("t#idx.status.proven.k")));
        assert!(!ctx.__exists(&pb("t#idx.status.active.k")));
        assert!(ctx.__exists(&pb("t#idx.owner.1.k")));

        // Framework-maintained bucket counts track the membership: status moved
        // active(0) -> proven(1); owner.1 stayed at 1.
        assert_eq!(ctx.__get_u64(&pb("t#idx.status.proven")), Some(1));
        assert_eq!(ctx.__get_u64(&pb("t#idx.status.active")), Some(0));
        assert_eq!(ctx.__get_u64(&pb("t#idx.owner.1")), Some(1));
    }

    // A removal whose index row isn't live (already tombstoned / never written —
    // a count that drifted) must be a no-op for the count, NOT a decrement: the
    // `__delete` returns false, and decrementing anyway would underflow the bucket
    // count and trap mid-update. Regression for "index diff ignores delete result".
    #[test]
    fn apply_index_diff_noop_delete_does_not_decrement() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // `old` claims `k` is in the `status.active` bucket, but no void row was
        // ever written there and the count is unset (0). Removing it is a no-op
        // delete; an unconditional decrement would `checked_sub(0)` → trap.
        apply_index_diff(&ctx, &index, "k", &[e("status", "active")], &[]);

        // Reaching here means no trap. The delete was attempted but removed
        // nothing, so the (absent) count was left untouched.
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(ctx.__get_u64(&pb("t#idx.status.active")), None);
    }

    // The bulk `Store` path: a map populated before a wholesale write must land
    // with both its primary values and its index rows.
    #[test]
    fn bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let m = StorageIndexedMap::<u64, Position, Mock>::new(&[
            (1, Position { status: 2 }),
            (2, Position { status: 2 }),
            (3, Position { status: 5 }),
        ]);

        Store::__set(&ctx, p("positions"), m);

        // Primary values (stored under the value's own field path).
        assert_eq!(ctx.__get_u64(&pb("positions.1.status")), Some(2));
        assert_eq!(ctx.__get_u64(&pb("positions.3.status")), Some(5));

        // Index rows, in the `#idx` sibling.
        assert!(ctx.__exists(&pb("positions#idx.status.2.1")));
        assert!(ctx.__exists(&pb("positions#idx.status.2.2")));
        assert!(ctx.__exists(&pb("positions#idx.status.5.3")));

        // by_index resolves to the primary keys.
        let bucket = p("positions#idx").push("status").push("2");
        let mut keys: Vec<u64> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, vec![1, 2]);

        // The bulk path maintains bucket counts too (it funnels through
        // apply_index_diff): status 2 has {1,2}, status 5 has {3}.
        assert_eq!(ctx.__get_u64(&pb("positions#idx.status.2")), Some(2));
        assert_eq!(ctx.__get_u64(&pb("positions#idx.status.5")), Some(1));
        // The count lives AT the bucket path, NOT as a child — so it never leaks
        // into a `by_index` scan of that bucket's members.
        assert_eq!(ctx.__get_keys::<u64>(&bucket).count(), 2);
    }

    // An IndexedMap nested inside a struct. Its `Store::__set` writes the field
    // wholesale, the way a derived struct `Store` does — this is the recursive
    // bulk path that the field model's per-key writes can't see.
    #[derive(Clone, Default)]
    struct Account {
        positions: StorageIndexedMap<u64, Position, Mock>,
    }

    impl Store<Mock> for Account {
        fn __set(ctx: &Rc<Mock>, base_path: DotPathBuf, value: Account) {
            ctx.__set(base_path.push("positions"), value.positions);
        }
    }

    // The recursive case: writing a struct wholesale must keep a *nested*
    // IndexedMap index-consistent, with the index sibling derived at the right
    // depth (`account.positions#idx`, not `positions#idx`).
    #[test]
    fn nested_bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let account = Account {
            positions: StorageIndexedMap::new(&[
                (1, Position { status: 2 }),
                (2, Position { status: 5 }),
            ]),
        };

        Store::__set(&ctx, p("account"), account);

        // Primary values land under the nested path.
        assert_eq!(ctx.__get_u64(&pb("account.positions.1.status")), Some(2));

        // Index rows are the `#idx` sibling *at depth* — same path the field
        // model would build (parent `account` + `positions#idx`).
        assert!(ctx.__exists(&pb("account.positions#idx.status.2.1")));
        assert!(ctx.__exists(&pb("account.positions#idx.status.5.2")));

        let bucket = p("account.positions#idx").push("status").push("2");
        assert_eq!(ctx.__get_keys::<u64>(&bucket).collect::<Vec<_>>(), vec![1]);
    }

    // An IndexedMap reached through a plain `Map` *value*. Bulk-writing a
    // `Map<K, Account>` flows through the UNMODIFIED `StorageMap::__set`, which
    // dispatches each value to `Account::__set`, which reaches the nested
    // IndexedMap's index-aware `Store`. The index must still be maintained.
    #[test]
    fn indexed_map_in_map_value_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let accounts = crate::StorageMap::<u64, Account, Mock>::new(&[
            (
                7,
                Account {
                    positions: StorageIndexedMap::new(&[(1, Position { status: 2 })]),
                },
            ),
            (
                8,
                Account {
                    positions: StorageIndexedMap::new(&[(1, Position { status: 5 })]),
                },
            ),
        ]);

        Store::__set(&ctx, p("accounts"), accounts);

        // Inner index rows land at the nested depth for each map entry.
        assert!(ctx.__exists(&pb("accounts.7.positions#idx.status.2.1")));
        assert!(ctx.__exists(&pb("accounts.8.positions#idx.status.5.1")));
        assert_eq!(ctx.__get_u64(&pb("accounts.7.positions.1.status")), Some(2));
    }

    // A plain `Map` nested inside an IndexedMap *value*. The outer index is keyed
    // off the value (`tag`); the inner map is just data. Both must persist.
    #[derive(Clone, Default)]
    struct Bag {
        tag: u64,
        items: crate::StorageMap<u64, u64, Mock>,
    }

    impl Store<Mock> for Bag {
        fn __set(ctx: &Rc<Mock>, base_path: DotPathBuf, value: Bag) {
            ctx.__set(base_path.push("tag"), value.tag);
            ctx.__set(base_path.push("items"), value.items);
        }
    }

    impl Indexed for Bag {
        fn index_entries(&self) -> Vec<IndexEntry> {
            alloc::vec![e("tag", &self.tag.to_string())]
        }
    }

    #[test]
    fn map_in_indexed_map_value() {
        let ctx = Rc::new(Mock::default());
        let bags = StorageIndexedMap::<u64, Bag, Mock>::new(&[(
            1,
            Bag {
                tag: 9,
                items: crate::StorageMap::new(&[(100, 1), (200, 2)]),
            },
        )]);

        Store::__set(&ctx, p("bags"), bags);

        // Outer index maintained by the value's `tag`.
        assert!(ctx.__exists(&pb("bags#idx.tag.9.1")));
        // Inner map data persisted under the value's path.
        assert_eq!(ctx.__get_u64(&pb("bags.1.items.100")), Some(1));
        assert_eq!(ctx.__get_u64(&pb("bags.1.items.200")), Some(2));
    }

    #[test]
    #[should_panic(expected = "path delimiter")]
    fn rejects_dotted_index_key() {
        let ctx = Rc::new(Mock::default());
        apply_index_diff(&ctx, &p("t#idx"), "k", &[], &[e("name", "a.b")]);
    }

    #[test]
    fn sort_key_is_order_preserving_and_fixed_width() {
        // Unsigned: lexicographic == numeric, fixed width.
        assert!(0u64.sort_key() < 1u64.sort_key());
        assert!(1u64.sort_key() < 256u64.sort_key());
        assert!((u64::MAX - 1).sort_key() < u64::MAX.sort_key());
        assert_eq!(0u64.sort_key().len(), <u64 as SortKey>::WIDTH);
        assert_eq!(u64::MAX.sort_key().len(), 16);
        assert_eq!(0u8.sort_key().len(), 2);
        assert_eq!(0u32.sort_key().len(), 8);

        // Signed: negatives sort before positives, monotone across zero.
        assert!(i64::MIN.sort_key() < (-1i64).sort_key());
        assert!((-1i64).sort_key() < 0i64.sort_key());
        assert!(0i64.sort_key() < 1i64.sort_key());
        assert!(1i64.sort_key() < i64::MAX.sort_key());
        assert_eq!((-1i64).sort_key().len(), 16);
        assert_eq!(i8::MIN.sort_key(), "00");
        assert_eq!(0i8.sort_key(), "80");
        assert_eq!(i8::MAX.sort_key(), "ff");
    }

    // SortKey encode/decode is a bijection, so a fixed-width segment can carry a
    // value that's recovered (the `B` tail of a `Pair`), not just compared.
    #[test]
    fn sort_key_decode_round_trips() {
        for v in [0u64, 1, 255, u64::MAX] {
            assert_eq!(u64::from_sort_key(&v.sort_key()), v);
        }
        for v in [i64::MIN, -1, 0, 1, i64::MAX] {
            assert_eq!(i64::from_sort_key(&v.sort_key()), v);
        }
        assert_eq!(i8::from_sort_key(&i8::MIN.sort_key()), i8::MIN);
        assert_eq!(u8::from_sort_key(&200u8.sort_key()), 200);
    }

    // A compound `Pair<String, u64>` primary key round-trips and sorts by (A, B) —
    // so an `IndexedMap` keyed on it iterates in key order.
    #[test]
    fn pair_compound_key_round_trips_and_orders() {
        let k = Pair::new("agreement-7".to_string(), 42u64);
        let s = k.to_string();
        assert_eq!(s, alloc::format!("agreement-7{}", 42u64.sort_key()));
        assert_eq!(Pair::<String, u64>::from_str(&s).unwrap(), k);

        // Sorts by A, then by B within an A.
        let a = Pair::new("a".to_string(), 2u64).to_string();
        let b = Pair::new("a".to_string(), 10u64).to_string();
        let c = Pair::new("b".to_string(), 1u64).to_string();
        assert!(a < b); // same A: 2 < 10
        assert!(b < c); // "a" < "b" regardless of B

        // Empty A is fine (suffix is the whole string).
        let empty = Pair::new(String::new(), 5u64);
        assert_eq!(
            Pair::<String, u64>::from_str(&empty.to_string()).unwrap(),
            empty
        );
    }

    // A composite index buckets on more than one segment (`<a>/<b>`). The member
    // rows, the count, and a scan all live under the multi-segment bucket path, and
    // a field change moves the member between buckets.
    #[test]
    fn composite_bucket_two_segments() {
        let ctx = Rc::new(Mock::default());
        let index = p("a#idx");
        // eligible index: bucket = [active, presence].
        let entry = |active: &str, presence: &str| IndexEntry {
            name: "eligible",
            bucket: alloc::vec![active.to_string().into(), presence.to_string().into()],
            sort: None,
        };
        apply_index_diff(&ctx, &index, "k1", &[], &[entry("true", "none")]);
        apply_index_diff(&ctx, &index, "k2", &[], &[entry("true", "none")]);
        apply_index_diff(&ctx, &index, "k3", &[], &[entry("true", "some")]);

        assert!(ctx.__exists(&pb("a#idx.eligible.true.none.k1")));
        assert!(ctx.__exists(&pb("a#idx.eligible.true.some.k3")));
        // Count lives AT the two-segment bucket path.
        assert_eq!(ctx.__get_u64(&pb("a#idx.eligible.true.none")), Some(2));
        assert_eq!(ctx.__get_u64(&pb("a#idx.eligible.true.some")), Some(1));
        // Scan of the (true, none) bucket yields just its members.
        let bucket = p("a#idx.eligible.true.none");
        let mut keys: Vec<String> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["k1".to_string(), "k2".to_string()]);

        // Flip k1's presence none -> some: one delete + one write, counts follow.
        apply_index_diff(
            &ctx,
            &index,
            "k1",
            &[entry("true", "none")],
            &[entry("true", "some")],
        );
        assert!(!ctx.__exists(&pb("a#idx.eligible.true.none.k1")));
        assert!(ctx.__exists(&pb("a#idx.eligible.true.some.k1")));
        assert_eq!(ctx.__get_u64(&pb("a#idx.eligible.true.none")), Some(1));
        assert_eq!(ctx.__get_u64(&pb("a#idx.eligible.true.some")), Some(2));
    }

    // An `Option` field and the `Presence` marker a lookup passes must produce the
    // same bucket key, or a write and its query would land in different buckets.
    #[test]
    fn option_and_presence_index_keys_agree() {
        assert_eq!(None::<u64>.index_key(), Presence::Absent.index_key());
        assert_eq!(Some(7u64).index_key(), Presence::Present.index_key());
        assert_eq!(None::<String>.index_key(), "none");
        assert_eq!(Some(7u64).index_key(), "some");
    }

    // SortedScan in isolation: strip the fixed-width sort prefix to recover K, and
    // bound on the ENCODED prefix (a string compare, no decode).
    #[test]
    fn sorted_scan_strips_prefix_and_bounds() {
        // width-4 (u16) sort prefix + a single-char primary key, ascending.
        let segs = || {
            alloc::boxed::Box::new(
                alloc::vec![
                    alloc::format!("{}a", 1u16.sort_key()),
                    alloc::format!("{}b", 3u16.sort_key()),
                    alloc::format!("{}c", 5u16.sort_key()),
                ]
                .into_iter(),
            ) as alloc::boxed::Box<dyn Iterator<Item = String>>
        };
        let scan = || SortedScan::<String, u16>::new(segs());

        assert_eq!(scan().collect::<Vec<_>>(), vec!["a", "b", "c"]);
        // up_to is inclusive and early-breaks past the bound.
        assert_eq!(scan().up_to(3u16).collect::<Vec<_>>(), vec!["a", "b"]);
        assert_eq!(scan().up_to(0u16).collect::<Vec<_>>(), Vec::<String>::new());
        // range is inclusive on both ends.
        assert_eq!(scan().range(3u16..=5u16).collect::<Vec<_>>(), vec!["b", "c"]);
        assert_eq!(scan().range(2u16..=2u16).collect::<Vec<_>>(), Vec::<String>::new());
    }

    // End-to-end: a sorted index entry writes a `<sort‖pk>` member, and a
    // SortedScan over that bucket recovers the keys in value order regardless of
    // insertion order — the shape `where_<index>` builds.
    #[test]
    fn sorted_scan_over_bucket_recovers_keys_in_order() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        // Index "due", bucket "active", sorted by a u64 height.
        let entry = |height: u64| IndexEntry {
            name: "due",
            bucket: alloc::vec!["active".to_string().into()],
            sort: Some(height.sort_key().into()),
        };
        // Insert out of order.
        apply_index_diff(&ctx, &index, "c", &[], &[entry(30)]);
        apply_index_diff(&ctx, &index, "a", &[], &[entry(10)]);
        apply_index_diff(&ctx, &index, "b", &[], &[entry(20)]);

        let bucket = index.push("due").push("active");
        let scan = || {
            SortedScan::<String, u64>::new(alloc::boxed::Box::new(ctx.__get_keys::<String>(&bucket)))
        };
        assert_eq!(scan().collect::<Vec<_>>(), vec!["a", "b", "c"]);
        assert_eq!(scan().up_to(20u64).collect::<Vec<_>>(), vec!["a", "b"]);
        assert_eq!(scan().range(20u64..=30u64).collect::<Vec<_>>(), vec!["b", "c"]);
    }
}
