//! Secondary-index infrastructure for [`StorageMap`](crate::StorageMap) — the one
//! `Map<K, V>`. When the value carries `#[index]` fields the map gains
//! framework-maintained secondary indexes, so filtered reads are prefix scans of a
//! declared index rather than a `keys()` scan-and-filter. A value with no `#[index]`
//! (or a primitive value) is a plain map: [`Indexed::HAS_INDEXES`] is `false` and all
//! of this const-folds out — there is no separate map type.
//!
//! Layout (all ordinary path-prefixed `contract_state` rows, so versioned,
//! reorg-safe, and folded into the checkpoint hash):
//! ```text
//!   <primary>/<key>                        -> V
//!   <primary>#idx/<index_name>/<index_key>/<key> -> ()   (sibling of <primary>)
//! ```
//! `by_index(name, key)` scans `<primary>#idx/<name>/<key>/`, whose child
//! segments ARE the primary keys. A key's index memberships are derived from its
//! value via [`Indexed`] — there is no separate record of them, so the value
//! stays the one source of truth (same as every other generated model). On
//! update the prior entries are recomputed and diffed against the new ones via
//! [`apply_index_diff`]: delete `old − new`, write `new − old`, so an unchanged
//! index (or a no-op re-set) costs zero index ops.
//!
//! The type a contract declares is the inert [`StorageMap`] placeholder; the real
//! per-key `get`/`set`/`remove`/`by_index` accessors are generated by the
//! `#[derive(Model)]` field model. The only logic carried here is (a)
//! [`apply_index_diff`], the single audited maintenance routine both the field model
//! and the bulk [`Store`] impl call, and (b) the [`Store`] impl below, which keeps a
//! *wholesale* write of the map (root init, or any nested struct set through
//! `Store`) index-consistent — the field model's per-key path can't catch that.

use alloc::rc::Rc;
use alloc::string::String;
use alloc::vec::Vec;

use crate::keycodec::{self, KeyElement};
use crate::{KeyPath, ReadStorage, Store, WriteStorage};

/// The codec element a value contributes as one index-bucket segment. The SINGLE
/// source every index path encodes through — a value's [`Indexed::index_entries`],
/// the read model's `__index_entries`, the in-place indexed-field setter, and the
/// generated `where_<field>` lookup — so the bucket a write lands in and the
/// bucket a lookup scans can never drift.
///
/// A bucket is an equality partition (order *within* it is irrelevant), so the
/// only requirement is a *distinct* element per value — no ordering, unlike a
/// [`KeyElement`] sort key. A [`KeyElement`] type encodes itself (a `u64` bucket
/// is a compact int element; a `Vec<u8>` its raw bytes — no hex). A storage enum
/// keys by its DISCRIMINANT (case name) as a string element, not its payload — so
/// `Failed(r)` always lands in the `"failed"` bucket and changing the payload is a
/// no-op for the index. The `Storage` derive supplies that impl (and a payload-free
/// `<E>Kind` marker for referencing a case without constructing one).
pub trait IndexKey {
    /// One complete, self-delimiting codec element (e.g. from [`KeyElement::encode`]).
    fn index_key(&self) -> Vec<u8>;
}

// A `KeyElement` type buckets by encoding itself — distinct per value, and far
// more compact than its `Display` for ints/bytes (a `u64` is ≤9 bytes vs up to 20
// decimal chars; `Vec<u8>` is raw, not 2× hex). No blanket `impl<T: KeyElement>`:
// it would collide with the discriminant impl the `Storage` derive emits for enums.
macro_rules! index_key_via_keyelement {
    ($($t:ty),*) => {
        $(
            impl IndexKey for $t {
                fn index_key(&self) -> Vec<u8> {
                    KeyElement::encode(self)
                }
            }
        )*
    };
}
index_key_via_keyelement!(bool, u8, u16, u32, u64, i8, i16, i32, i64, String, Vec<u8>);

/// An `Option<T>` indexes by its `none`/`some` **discriminant** (like an enum keys
/// by its case), ignoring the payload — so a composite index can partition on "is
/// this field set?" without a predicate DSL. The discriminant is a string element,
/// matching [`Presence`] (the payload-free marker a `where_*` lookup passes) and
/// storage enums, so the bucket a write lands in and a lookup scans agree. Blanket
/// over all `T`: `Option` is neither a keyed primitive nor a storage enum, so no
/// impl overlaps it.
impl<T> IndexKey for Option<T> {
    fn index_key(&self) -> Vec<u8> {
        let s = match self {
            None => "none",
            Some(_) => "some",
        };
        String::from(s).encode()
    }
}

/// The payload-free marker for bucketing an `Option` index field by presence —
/// the `Option` analogue of a storage enum's `<E>Kind`. Lets a lookup name the
/// bucket (`where_eligible(true, Presence::Absent)`) without constructing an
/// `Option` value or writing `None::<T>` with a turbofish. Its [`IndexKey`]
/// matches `Option`'s, so lookup and stored bucket can't drift.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Presence {
    Absent,
    Present,
}

impl IndexKey for Presence {
    fn index_key(&self) -> Vec<u8> {
        let s = match self {
            Presence::Absent => "none",
            Presence::Present => "some",
        };
        String::from(s).encode()
    }
}

/// An ordered scan over a *sorted* index bucket. Each member segment is one
/// `(sort, pk)` nested-tuple element, handed back in ascending path order by
/// `keys()` — which, because the codec is order-preserving and `sort` leads the
/// tuple, is ascending by sort value (then primary key). Decoding the tuple yields
/// `(S, K)`; the scan drops the sort field and keeps `K`. This is what lets a
/// sortable index scan in value order and early-break, while storage stays the
/// generic `contract_state` log (sortability lives in the key, never a column).
///
/// Iterating it directly walks the whole bucket in sort order. [`up_to`] /
/// [`range`] bound it on the **decoded** sort value `S` and early-break, so the
/// contract pays only for the members it keeps (the host still materializes the
/// bucket; see the module's cost note). The bound is typed `S` — the index's own
/// sort field type — so the wrong type is a compile error, not a silent
/// miscompare.
///
/// [`up_to`]: SortedScan::up_to
/// [`range`]: SortedScan::range
pub struct SortedScan<K, S> {
    // Boxed so the generated `where_<index>` can name a single return type
    // (`SortedScan<K, S>`) without threading the concrete `keys()` iterator type
    // through the lookup trait. One box per scan — negligible next to the bucket
    // walk it wraps. Yields `(sort, pk)` in ascending order.
    members: alloc::boxed::Box<dyn Iterator<Item = (S, K)>>,
}

impl<K, S> SortedScan<K, S> {
    pub fn new(members: alloc::boxed::Box<dyn Iterator<Item = (S, K)>>) -> Self {
        Self { members }
    }
}

impl<K, S: PartialOrd> SortedScan<K, S> {
    /// Members whose sort value is `≤ bound`, in ascending order. Early-breaks at
    /// the first member above the bound — nothing later in a sorted bucket can
    /// qualify.
    pub fn up_to(self, bound: S) -> impl Iterator<Item = K> {
        self.members
            .take_while(move |(s, _)| *s <= bound)
            .map(|(_, k)| k)
    }

    /// Members whose sort value is within `range` (inclusive), in ascending order.
    /// Skips below `lo`, then early-breaks past `hi`.
    pub fn range(self, range: core::ops::RangeInclusive<S>) -> impl Iterator<Item = K> {
        let (lo, hi) = range.into_inner();
        self.members
            .skip_while(move |(s, _)| *s < lo)
            .take_while(move |(s, _)| *s <= hi)
            .map(|(_, k)| k)
    }
}

impl<K, S> Iterator for SortedScan<K, S> {
    type Item = K;

    /// Unbounded walk of the bucket in sort order.
    fn next(&mut self) -> Option<K> {
        self.members.next().map(|(_, k)| k)
    }
}

/// One secondary-index membership of a value: which index, which bucket, and
/// (optionally) where it sorts within that bucket. The leaf it maps to is
/// `<index>/<bucket…>/<sort‖pk>` (see the `Map` module docs).
///
/// `bucket` is a vec so a composite index can partition on several fields (one
/// segment each, in declared order); a single-field index has one — each a
/// pre-encoded [`IndexKey`] codec element (distinct partitioning, order
/// irrelevant). `sort` is the sort field's pre-encoded codec element
/// (`KeyElement::encode`), which leads the `(sort, pk)` member tuple so the bucket
/// scans in value order. (A covering projection will be added here later as the
/// leaf *value*; the diff already keys on the leaf path so that stays additive.)
pub struct IndexEntry {
    /// The index's interned id (its declaration order within the value type), the
    /// structural `<index>` segment — a dict-ref, like every other structural name.
    /// Per value type; only ever used under that value's `#idx` root, so distinct
    /// value types' id spaces never meet.
    pub name_id: u8,
    pub bucket: Vec<Vec<u8>>,
    pub sort: Option<Vec<u8>>,
}

impl IndexEntry {
    /// The bucket-prefix path `<index>/<bucket…>` (where the count lives; members
    /// are its children). The index name is an interned structural segment; each
    /// bucket segment is a pre-encoded `IndexKey` element.
    fn bucket_path(&self, index_root: &KeyPath) -> KeyPath {
        index_root
            .push_interned(self.name_id)
            .push_raw_elements(&self.bucket)
    }

    /// The member element: the `(sort, pk)` nested tuple (so the bucket sorts by
    /// value, then key), or just the primary-key element when unsorted. `key` is
    /// the already-encoded primary-key element. Both inputs are full codec
    /// elements, so packing them is a tuple wrap.
    fn member_element(&self, key: &[u8]) -> Vec<u8> {
        match &self.sort {
            Some(sort) => keycodec::tuple_from_elements(&[sort, key]),
            None => key.to_vec(),
        }
    }

    /// Two entries share a leaf (same `<index>/<bucket…>/<member>`) iff they agree
    /// on name+bucket+sort. The diff keys on this; a future covering projection is
    /// the leaf *value*, updated in place when the path matches.
    fn same_leaf(&self, other: &IndexEntry) -> bool {
        self.name_id == other.name_id && self.bucket == other.bucket && self.sort == other.sort
    }
}

/// A value's secondary-index memberships. An empty result means "in no index" —
/// partial indexes fall out by omitting an entry when a predicate is false.
///
/// Every storage value implements this — structs/enums via `#[derive(Storage)]`,
/// primitives via the blanket-ish impls below — so one `Map<K, V>` covers both
/// plain and indexed values. `HAS_INDEXES` is a compile-time flag: the generated
/// `set`/`remove` skip all index maintenance when it's `false`, so a non-indexed
/// map compiles to exactly the plain path (verified: no read-before-write emitted).
pub trait Indexed {
    /// Whether this value declares any secondary indexes. Const so callers can
    /// `if <V as Indexed>::HAS_INDEXES { … }` and have the branch const-fold.
    const HAS_INDEXES: bool = false;
    fn index_entries(&self) -> Vec<IndexEntry> {
        Vec::new()
    }
}

// Primitive (leaf) storage values are never indexed. (WIT "primitives" like
// `Integer`/`Decimal`/`Holder` are records and get `Indexed` from their `Storage`
// derive; these are the bare Rust types.)
macro_rules! impl_indexed_leaf {
    ($($t:ty),* $(,)?) => { $( impl Indexed for $t {} )* };
}
impl_indexed_leaf!(u8, u16, u32, u64, i32, i64, bool, String, Vec<u8>, ());

/// Reconcile one key's index rows from `old` to `new`: delete entries in `old`
/// that aren't in `new`, write entries in `new` that weren't in `old`. Unchanged
/// entries are left untouched (zero ops). Index roots are siblings of the
/// primary map.
///
/// `key` is the primary key's already-encoded codec element. Type-erased (raw
/// bytes, not generic `K`) so this stays the one audited routine every caller —
/// of differing key types — funnels through; the typed call sites encode. Because
/// every segment is now a self-delimiting codec element, a key may contain any
/// content (no delimiter to alias on — what the old `.`-join had to reject).
///
/// The caller computes `old`/`new`: the field model's `set`/`remove` load the
/// prior value and read its `Indexed::index_entries`; an in-place indexed-field
/// setter diffs just that field's entry; the bulk [`Store`] impl starts from
/// empty (a fresh wholesale write). Either way the maintenance logic lives only
/// here.
pub fn apply_index_diff<S: WriteStorage + ReadStorage + ?Sized>(
    ctx: &Rc<S>,
    index_root: &KeyPath,
    key: &[u8],
    old: &[IndexEntry],
    new: &[IndexEntry],
) {
    for entry in old {
        if !new.iter().any(|n| n.same_leaf(entry)) {
            let bucket = entry.bucket_path(index_root);
            // Decrement ONLY when the delete actually removed a live row.
            // `__delete` returns false for a no-op (the entry was already
            // tombstoned or never written — an index/count that drifted); counting
            // that as a removal would underflow the bucket count and trap. The
            // delete result is the authority on whether membership changed.
            if ctx.__delete(&bucket.push_raw_element(&entry.member_element(key))) {
                bump_bucket_count(ctx, &bucket, false);
            }
        }
    }
    for entry in new {
        if !old.iter().any(|o| o.same_leaf(entry)) {
            let bucket = entry.bucket_path(index_root);
            ctx.__set_void(&bucket.push_raw_element(&entry.member_element(key)));
            bump_bucket_count(ctx, &bucket, true);
        }
    }
}

/// Adjust a bucket's framework-maintained member count. The count lives AT the
/// bucket-prefix path (`<map>#idx/<name>/<key>`); the bucket's members are its
/// CHILDREN (`…/<key>/<primary_key>`), so this value is invisible to the
/// `by_index` child-scan and to `keys()`. Maintained only here — the one site
/// every index add/remove funnels through (field-model `set`/`remove`, in-place
/// setter, and the bulk `Store`) — so it can't drift from the membership it
/// counts. It's an ordinary height-versioned `contract_state` row, so it rolls
/// back with everything else on a reorg.
fn bump_bucket_count<S: WriteStorage + ReadStorage + ?Sized>(
    ctx: &Rc<S>,
    bucket: &KeyPath,
    up: bool,
) {
    let current = ctx.__get_u64(bucket).unwrap_or(0);
    // A decrement always follows a counted insert (reorgs roll the count row back
    // as versioned state, they don't decrement), so underflow can only mean a
    // framework bug. Trap loudly and deterministically rather than clamp and let a
    // wrong count drive wrong decisions — surfacing corruption, not masking it.
    let next = if up {
        current + 1
    } else {
        current
            .checked_sub(1)
            .expect("Map bucket count underflow — framework bug")
    };
    ctx.__set_u64(bucket, next);
}

impl<K, V, S> Store<S> for crate::StorageMap<K, V, S>
where
    K: KeyElement + Clone,
    V: Store<S> + Clone + Indexed,
    S: WriteStorage + ReadStorage + ?Sized,
{
    /// Wholesale write: persist every entry's value, plus its index rows when the
    /// value type declares indexes, so a map populated before `init` (at the root
    /// or any nested level) lands index-consistent. The index root is the
    /// `<primary>#idx` sibling, derived from `base_path` the same way the field
    /// model builds it. An upsert from empty (adds rows; per-key updates that must
    /// diff go through the field model's `set`). For a non-indexed value
    /// `HAS_INDEXES` is `false`, so the index block const-folds out and this is the
    /// plain entry write.
    fn __set(ctx: &Rc<S>, base_path: KeyPath, value: crate::StorageMap<K, V, S>) {
        for (k, v) in value.entries.into_iter() {
            if V::HAS_INDEXES
                && let Some(index_root) = base_path.interned_index_sibling()
            {
                apply_index_diff(ctx, &index_root, &k.encode(), &[], &v.index_entries());
            }
            ctx.__set(base_path.push_element(&k), v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ReadStorage;
    use crate::StorageMap;
    use crate::keycodec::next_element;
    use alloc::collections::BTreeMap;
    use alloc::string::ToString;
    use alloc::vec;
    use core::cell::RefCell;

    #[derive(Clone)]
    enum Cell {
        U64(u64),
        Void,
    }

    #[derive(Default)]
    struct Mock {
        map: RefCell<BTreeMap<Vec<u8>, Cell>>,
        void_sets: RefCell<usize>,
        deletes: RefCell<usize>,
    }

    impl ReadStorage for Mock {
        fn __get_u64(self: &Rc<Self>, path: &[u8]) -> Option<u64> {
            match self.map.borrow().get(path) {
                Some(Cell::U64(v)) => Some(*v),
                _ => None,
            }
        }
        fn __get_keys<T: KeyElement + Clone>(
            self: &Rc<Self>,
            path: &[u8],
        ) -> impl Iterator<Item = T> + use<T> {
            // Distinct child elements: byte-prefix the path, take the next element
            // of the suffix (mirrors the host's `next_element` extraction).
            let mut elems: Vec<Vec<u8>> = self
                .map
                .borrow()
                .keys()
                .filter_map(|k| {
                    let rest = k.as_slice().strip_prefix(path)?;
                    if rest.is_empty() {
                        return None;
                    }
                    Some(next_element(rest).ok()?.0.to_vec())
                })
                .collect();
            elems.sort();
            elems.dedup();
            elems.into_iter().map(|e| {
                let (v, _) = T::decode_from(&e).unwrap();
                v
            })
        }
        fn __get<T: crate::Retrieve<Self>>(self: &Rc<Self>, path: KeyPath) -> Option<T> {
            T::__get(self, path)
        }
        fn __get_str(self: &Rc<Self>, _: &[u8]) -> Option<String> {
            unimplemented!()
        }
        fn __get_s64(self: &Rc<Self>, _: &[u8]) -> Option<i64> {
            unimplemented!()
        }
        fn __get_bool(self: &Rc<Self>, _: &[u8]) -> Option<bool> {
            unimplemented!()
        }
        fn __get_list_u8(self: &Rc<Self>, _: &[u8]) -> Option<Vec<u8>> {
            unimplemented!()
        }
        fn __exists(self: &Rc<Self>, path: &[u8]) -> bool {
            self.map.borrow().contains_key(path)
        }
        fn __extend_path_with_match(self: &Rc<Self>, _: &[u8], _: &[Vec<u8>]) -> Option<u32> {
            unimplemented!()
        }
    }

    impl WriteStorage for Mock {
        fn __set_u64(self: &Rc<Self>, path: &[u8], value: u64) {
            self.map
                .borrow_mut()
                .insert(path.to_vec(), Cell::U64(value));
        }
        fn __set_void(self: &Rc<Self>, path: &[u8]) {
            *self.void_sets.borrow_mut() += 1;
            self.map.borrow_mut().insert(path.to_vec(), Cell::Void);
        }
        fn __delete(self: &Rc<Self>, path: &[u8]) -> bool {
            *self.deletes.borrow_mut() += 1;
            self.map.borrow_mut().remove(path).is_some()
        }
        fn __set<T: Store<Self>>(self: &Rc<Self>, path: KeyPath, value: T) {
            T::__set(self, path, value)
        }
        fn __set_str(self: &Rc<Self>, _: &[u8], _: &str) {
            unimplemented!()
        }
        fn __set_s64(self: &Rc<Self>, _: &[u8], _: i64) {
            unimplemented!()
        }
        fn __set_bool(self: &Rc<Self>, _: &[u8], _: bool) {
            unimplemented!()
        }
        fn __set_list_u8(self: &Rc<Self>, _: &[u8], _: Vec<u8>) {
            unimplemented!()
        }
        fn __delete_matching_paths(self: &Rc<Self>, _: &[u8], _: &[Vec<u8>]) -> u64 {
            unimplemented!()
        }
    }

    // A path from a dotted string (each piece a string-element segment) → codec bytes.
    fn p(s: &str) -> KeyPath {
        KeyPath::from(s)
    }

    // Codec bytes of a `KeyPath` (e.g. one ending in a typed key element).
    fn b(path: KeyPath) -> Vec<u8> {
        path.as_bytes().to_vec()
    }

    // The interned id a real contract's macro would assign a Map field
    // (its declaration index). Wholesale `Store` derives the `#idx` sibling from
    // this via `interned_index_sibling`, so the map-field segment MUST be interned
    // (not a string) for those tests to mirror production.
    const IM: u8 = 0;

    // A primary key encoded as its codec element (what `apply_index_diff` takes,
    // and the member segment of an unsorted index).
    fn kb(k: impl KeyElement) -> Vec<u8> {
        k.encode()
    }

    // A test index name's interned id. The real `Storage` derive assigns ids by
    // declaration order; these direct unit tests don't run the macro, so we map
    // names to stable ids here (distinct within a single `#idx` root: status≠owner).
    fn nid(name: &str) -> u8 {
        match name {
            "status" => 0,
            "owner" => 1,
            "name" => 0,
            "eligible" => 0,
            "due" => 0,
            "tag" => 0,
            other => panic!("unknown test index name `{other}`"),
        }
    }

    // The interned `<index>` segment under an `#idx` root — what `bucket_path`
    // builds. Lets assertions mirror the production (interned) index-name encoding.
    fn ix(root: &KeyPath, name: &str) -> KeyPath {
        root.push_interned(nid(name))
    }

    // A single-field index entry (one bucket segment, unsorted) — the shape the
    // shipped `#[index]` produces.
    fn e(name: &str, key: &str) -> IndexEntry {
        IndexEntry {
            name_id: nid(name),
            bucket: alloc::vec![key.to_string().encode()],
            sort: None,
        }
    }

    // A struct value with one indexed field — the shape a Map holds.
    #[derive(Clone)]
    struct Position {
        status: u64,
    }

    impl Store<Mock> for Position {
        fn __set(ctx: &Rc<Mock>, base_path: KeyPath, value: Position) {
            ctx.__set(base_path.push("status"), value.status);
        }
    }

    impl Indexed for Position {
        const HAS_INDEXES: bool = true;
        fn index_entries(&self) -> Vec<IndexEntry> {
            alloc::vec![e("status", &self.status.to_string())]
        }
    }

    // Drive `apply_index_diff` directly — the routine both the field model and
    // the bulk Store impl delegate to.
    #[test]
    fn apply_index_diff_reconciles_entries() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // From nothing -> {status:active, owner:1}: two writes.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[],
            &[e("status", "active"), e("owner", "1")],
        );
        assert_eq!(*ctx.void_sets.borrow(), 2);
        assert_eq!(*ctx.deletes.borrow(), 0);

        // {active,1} -> {proven,1}: only status moves (1 delete + 1 write); owner
        // is unchanged and untouched.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[e("status", "active"), e("owner", "1")],
            &[e("status", "proven"), e("owner", "1")],
        );
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(*ctx.void_sets.borrow(), 3); // 2 + 1

        // A no-op re-set (old == new) touches nothing.
        *ctx.void_sets.borrow_mut() = 0;
        *ctx.deletes.borrow_mut() = 0;
        let same = [e("status", "proven"), e("owner", "1")];
        apply_index_diff(&ctx, &index, &kb("k".to_string()), &same, &same);
        assert_eq!(*ctx.deletes.borrow(), 0);
        assert_eq!(*ctx.void_sets.borrow(), 0);

        // The status entry moved buckets; the owner entry is still in place. The
        // `<index>` name segment is interned (`ix`); the bucket value + member stay
        // string elements (what `e`/`kb` produce).
        assert!(ctx.__exists(&b(ix(&index, "status").push("proven").push("k"))));
        assert!(!ctx.__exists(&b(ix(&index, "status").push("active").push("k"))));
        assert!(ctx.__exists(&b(ix(&index, "owner").push("1").push("k"))));

        // Framework-maintained bucket counts track the membership: status moved
        // active(0) -> proven(1); owner.1 stayed at 1.
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "status").push("proven"))),
            Some(1)
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "status").push("active"))),
            Some(0)
        );
        assert_eq!(ctx.__get_u64(&b(ix(&index, "owner").push("1"))), Some(1));
    }

    // A removal whose index row isn't live (already tombstoned / never written —
    // a count that drifted) must be a no-op for the count, NOT a decrement: the
    // `__delete` returns false, and decrementing anyway would underflow the bucket
    // count and trap mid-update. Regression for "index diff ignores delete result".
    #[test]
    fn apply_index_diff_noop_delete_does_not_decrement() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // `old` claims `k` is in the `status.active` bucket, but no void row was
        // ever written there and the count is unset (0). Removing it is a no-op
        // delete; an unconditional decrement would `checked_sub(0)` → trap.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[e("status", "active")],
            &[],
        );

        // Reaching here means no trap. The delete was attempted but removed
        // nothing, so the (absent) count was left untouched.
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(ctx.__get_u64(&b(ix(&index, "status").push("active"))), None);
    }

    // The bulk `Store` path: a map populated before a wholesale write must land
    // with both its primary values and its index rows.
    #[test]
    fn bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let m = StorageMap::<u64, Position, Mock>::new(&[
            (1, Position { status: 2 }),
            (2, Position { status: 2 }),
            (3, Position { status: 5 }),
        ]);

        let base = KeyPath::new().push_interned(IM); // the interned `positions` field
        Store::__set(&ctx, base.clone(), m);

        // Primary values (stored under the value's own field path; the u64 map key
        // is a native int element, not a stringified segment).
        assert_eq!(
            ctx.__get_u64(&b(base.push_element(&1u64).push("status"))),
            Some(2)
        );
        assert_eq!(
            ctx.__get_u64(&b(base.push_element(&3u64).push("status"))),
            Some(5)
        );

        // Index rows, in the `#idx` sibling (derived the same way production does).
        // The member is the u64 primary key.
        let idx = base.interned_index_sibling().unwrap();
        assert!(ctx.__exists(&b(ix(&idx, "status").push("2").push_element(&1u64))));
        assert!(ctx.__exists(&b(ix(&idx, "status").push("2").push_element(&2u64))));
        assert!(ctx.__exists(&b(ix(&idx, "status").push("5").push_element(&3u64))));

        // by_index resolves to the primary keys.
        let bucket = ix(&idx, "status").push("2");
        let mut keys: Vec<u64> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, vec![1, 2]);

        // The bulk path maintains bucket counts too (it funnels through
        // apply_index_diff): status 2 has {1,2}, status 5 has {3}.
        assert_eq!(ctx.__get_u64(&b(ix(&idx, "status").push("2"))), Some(2));
        assert_eq!(ctx.__get_u64(&b(ix(&idx, "status").push("5"))), Some(1));
        // The count lives AT the bucket path, NOT as a child — so it never leaks
        // into a `by_index` scan of that bucket's members.
        assert_eq!(ctx.__get_keys::<u64>(&bucket).count(), 2);
    }

    // An Map nested inside a struct. Its `Store::__set` writes the field
    // wholesale, the way a derived struct `Store` does — this is the recursive
    // bulk path that the field model's per-key writes can't see.
    #[derive(Clone, Default)]
    struct Account {
        positions: StorageMap<u64, Position, Mock>,
    }

    impl Store<Mock> for Account {
        fn __set(ctx: &Rc<Mock>, base_path: KeyPath, value: Account) {
            // `positions` is an interned field name (as the macro would emit).
            ctx.__set(base_path.push_interned(IM), value.positions);
        }
    }

    // Account itself has no indexes; it only nests an indexed map.
    impl Indexed for Account {}

    // The recursive case: writing a struct wholesale must keep a *nested*
    // Map index-consistent, with the index sibling derived at the right
    // depth (`account.positions#idx`, not `positions#idx`).
    #[test]
    fn nested_bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let account = Account {
            positions: StorageMap::new(&[(1, Position { status: 2 }), (2, Position { status: 5 })]),
        };

        Store::__set(&ctx, p("account"), account);

        // The nested `positions` field, interned under `account`.
        let base = p("account").push_interned(IM);

        // Primary values land under the nested path.
        assert_eq!(
            ctx.__get_u64(&b(base.push_element(&1u64).push("status"))),
            Some(2)
        );

        // Index rows are the `#idx` sibling *at depth* — same path the field
        // model would build (parent `account` + `positions#idx`).
        let idx = base.interned_index_sibling().unwrap();
        assert!(ctx.__exists(&b(ix(&idx, "status").push("2").push_element(&1u64))));
        assert!(ctx.__exists(&b(ix(&idx, "status").push("5").push_element(&2u64))));

        let bucket = ix(&idx, "status").push("2");
        assert_eq!(ctx.__get_keys::<u64>(&bucket).collect::<Vec<_>>(), vec![1]);
    }

    // An Map reached through a plain `Map` *value*. Bulk-writing a
    // `Map<K, Account>` flows through the UNMODIFIED `StorageMap::__set`, which
    // dispatches each value to `Account::__set`, which reaches the nested
    // Map's index-aware `Store`. The index must still be maintained.
    #[test]
    fn indexed_map_in_map_value_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let accounts = crate::StorageMap::<u64, Account, Mock>::new(&[
            (
                7,
                Account {
                    positions: StorageMap::new(&[(1, Position { status: 2 })]),
                },
            ),
            (
                8,
                Account {
                    positions: StorageMap::new(&[(1, Position { status: 5 })]),
                },
            ),
        ]);

        Store::__set(&ctx, p("accounts"), accounts);

        // Inner index rows land at the nested depth for each map entry (outer and
        // inner keys are u64 elements; `positions`/`#idx` are interned, the bucket
        // name/value segments are strings).
        let pos7 = p("accounts").push_element(&7u64).push_interned(IM);
        let pos8 = p("accounts").push_element(&8u64).push_interned(IM);
        assert!(
            ctx.__exists(&b(ix(&pos7.interned_index_sibling().unwrap(), "status")
                .push("2")
                .push_element(&1u64)))
        );
        assert!(
            ctx.__exists(&b(ix(&pos8.interned_index_sibling().unwrap(), "status")
                .push("5")
                .push_element(&1u64)))
        );
        assert_eq!(
            ctx.__get_u64(&b(pos7.push_element(&1u64).push("status"))),
            Some(2)
        );
    }

    // A plain `Map` nested inside a Map *value*. The outer index is keyed
    // off the value (`tag`); the inner map is just data. Both must persist.
    #[derive(Clone, Default)]
    struct Bag {
        tag: u64,
        items: crate::StorageMap<u64, u64, Mock>,
    }

    impl Store<Mock> for Bag {
        fn __set(ctx: &Rc<Mock>, base_path: KeyPath, value: Bag) {
            ctx.__set(base_path.push("tag"), value.tag);
            ctx.__set(base_path.push("items"), value.items);
        }
    }

    impl Indexed for Bag {
        const HAS_INDEXES: bool = true;
        fn index_entries(&self) -> Vec<IndexEntry> {
            alloc::vec![e("tag", &self.tag.to_string())]
        }
    }

    #[test]
    fn map_in_indexed_map_value() {
        let ctx = Rc::new(Mock::default());
        let bags = StorageMap::<u64, Bag, Mock>::new(&[(
            1,
            Bag {
                tag: 9,
                items: crate::StorageMap::new(&[(100, 1), (200, 2)]),
            },
        )]);

        let base = KeyPath::new().push_interned(IM); // the interned `bags` field
        Store::__set(&ctx, base.clone(), bags);

        // Outer index maintained by the value's `tag` (member is the u64 key 1).
        let idx = base.interned_index_sibling().unwrap();
        assert!(ctx.__exists(&b(ix(&idx, "tag").push("9").push_element(&1u64))));
        // Inner map data persisted under the value's path (u64 key + u64 item keys).
        assert_eq!(
            ctx.__get_u64(&b(base
                .push_element(&1u64)
                .push("items")
                .push_element(&100u64))),
            Some(1)
        );
        assert_eq!(
            ctx.__get_u64(&b(base
                .push_element(&1u64)
                .push("items")
                .push_element(&200u64))),
            Some(2)
        );
    }

    // A primary key may now contain the old path delimiter `.`: every segment is a
    // self-delimiting codec element, so a `.` is just content — distinct, recoverable
    // bytes — not a separator that aliases (what the old `.`-join had to reject).
    #[test]
    fn dotted_keys_are_just_content() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        apply_index_diff(&ctx, &index, &kb("a.b".to_string()), &[], &[e("name", "x")]);
        apply_index_diff(&ctx, &index, &kb("a".to_string()), &[], &[e("name", "x")]);
        // Distinct members despite the `.` — both live under the same bucket.
        let bucket = ix(&index, "name").push("x");
        let mut keys: Vec<String> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["a".to_string(), "a.b".to_string()]);
        assert_eq!(ctx.__get_u64(&b(ix(&index, "name").push("x"))), Some(2));
    }

    // A bucket segment is the field's TYPED codec element (not its decimal string):
    // a `u64` bucket is an int element, so the path is compact and a lookup that
    // encodes the same value finds the members — while the old string form ("5")
    // is NOT where the rows live.
    #[test]
    fn bucket_is_typed_codec_element() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let entry = |status: u64| IndexEntry {
            name_id: nid("status"),
            bucket: alloc::vec![status.index_key()], // int element, not "5"
            sort: None,
        };
        apply_index_diff(&ctx, &index, &kb("k1".to_string()), &[], &[entry(5)]);
        apply_index_diff(&ctx, &index, &kb("k2".to_string()), &[], &[entry(5)]);

        // Rows live under the int-element bucket, NOT the string "5" bucket.
        let int_bucket = ix(&index, "status").push_element(&5u64);
        assert_eq!(ctx.__get_u64(&int_bucket), Some(2));
        assert_eq!(ctx.__get_u64(&ix(&index, "status").push("5")), None);
        let mut keys: Vec<String> = ctx.__get_keys(&int_bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["k1".to_string(), "k2".to_string()]);
    }

    // A composite index buckets on more than one segment (`<a>/<b>`). The member
    // rows, the count, and a scan all live under the multi-segment bucket path, and
    // a field change moves the member between buckets.
    #[test]
    fn composite_bucket_two_segments() {
        let ctx = Rc::new(Mock::default());
        let index = p("a#idx");
        // eligible index: bucket = [active, presence].
        let entry = |active: &str, presence: &str| IndexEntry {
            name_id: nid("eligible"),
            bucket: alloc::vec![active.to_string().encode(), presence.to_string().encode()],
            sort: None,
        };
        apply_index_diff(
            &ctx,
            &index,
            &kb("k1".to_string()),
            &[],
            &[entry("true", "none")],
        );
        apply_index_diff(
            &ctx,
            &index,
            &kb("k2".to_string()),
            &[],
            &[entry("true", "none")],
        );
        apply_index_diff(
            &ctx,
            &index,
            &kb("k3".to_string()),
            &[],
            &[entry("true", "some")],
        );

        assert!(ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("none").push("k1")
        )));
        assert!(ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("some").push("k3")
        )));
        // Count lives AT the two-segment bucket path.
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("none"))),
            Some(2)
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("some"))),
            Some(1)
        );
        // Scan of the (true, none) bucket yields just its members.
        let bucket = ix(&index, "eligible").push("true").push("none");
        let mut keys: Vec<String> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["k1".to_string(), "k2".to_string()]);

        // Flip k1's presence none -> some: one delete + one write, counts follow.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k1".to_string()),
            &[entry("true", "none")],
            &[entry("true", "some")],
        );
        assert!(!ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("none").push("k1")
        )));
        assert!(ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("some").push("k1")
        )));
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("none"))),
            Some(1)
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("some"))),
            Some(2)
        );
    }

    // A byte field buckets by its raw codec bytes element (not hex) — distinct per
    // value, and decodable back to the bytes.
    #[test]
    fn bytes_index_key_is_raw_element() {
        let v = vec![0xde_u8, 0xad, 0xbe, 0xef];
        assert_eq!(v.index_key(), v.encode());
        let (back, _) = <Vec<u8>>::decode_from(&v.index_key()).unwrap();
        assert_eq!(back, v);
        // distinct bytes → distinct buckets
        assert_ne!(vec![0x01_u8].index_key(), vec![0x10_u8].index_key());
    }

    // A primitive buckets by its codec element — compact, not its decimal Display.
    #[test]
    fn primitive_index_key_is_codec_element() {
        assert_eq!(5u64.index_key(), 5u64.encode());
        assert_eq!(true.index_key(), true.encode());
        assert_ne!(1u64.index_key(), 2u64.index_key());
    }

    // An `Option` field and the `Presence` marker a lookup passes must produce the
    // same bucket key, or a write and its query would land in different buckets.
    #[test]
    fn option_and_presence_index_keys_agree() {
        assert_eq!(None::<u64>.index_key(), Presence::Absent.index_key());
        assert_eq!(Some(7u64).index_key(), Presence::Present.index_key());
        assert_eq!(None::<String>.index_key(), String::from("none").encode());
        assert_eq!(Some(7u64).index_key(), String::from("some").encode());
    }

    // SortedScan in isolation: yields K in sort order and bounds on the decoded
    // sort value `S` (no width/prefix arithmetic — the member is a typed tuple).
    #[test]
    fn sorted_scan_bounds_on_decoded_value() {
        let members = || {
            alloc::boxed::Box::new(
                alloc::vec![
                    (1u16, "a".to_string()),
                    (3u16, "b".to_string()),
                    (5u16, "c".to_string()),
                ]
                .into_iter(),
            ) as alloc::boxed::Box<dyn Iterator<Item = (u16, String)>>
        };
        let scan = || SortedScan::<String, u16>::new(members());

        assert_eq!(scan().collect::<Vec<_>>(), vec!["a", "b", "c"]);
        // up_to is inclusive and early-breaks past the bound.
        assert_eq!(scan().up_to(3u16).collect::<Vec<_>>(), vec!["a", "b"]);
        assert_eq!(scan().up_to(0u16).collect::<Vec<_>>(), Vec::<String>::new());
        // range is inclusive on both ends.
        assert_eq!(
            scan().range(3u16..=5u16).collect::<Vec<_>>(),
            vec!["b", "c"]
        );
        assert_eq!(
            scan().range(2u16..=2u16).collect::<Vec<_>>(),
            Vec::<String>::new()
        );
    }

    // End-to-end: a sorted index entry writes an `(sort, pk)` tuple member, and a
    // SortedScan over that bucket recovers the keys in value order regardless of
    // insertion order — the shape `where_<index>` builds.
    #[test]
    fn sorted_scan_over_bucket_recovers_keys_in_order() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        // Index "due", bucket "active", sorted by a u64 height (pre-encoded element).
        let entry = |height: u64| IndexEntry {
            name_id: nid("due"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: Some(height.encode()),
        };
        // Insert out of order.
        apply_index_diff(&ctx, &index, &kb("c".to_string()), &[], &[entry(30)]);
        apply_index_diff(&ctx, &index, &kb("a".to_string()), &[], &[entry(10)]);
        apply_index_diff(&ctx, &index, &kb("b".to_string()), &[], &[entry(20)]);

        let bucket = ix(&index, "due").push("active");
        let scan = || {
            SortedScan::<String, u64>::new(alloc::boxed::Box::new(
                ctx.__get_keys::<(u64, String)>(&bucket),
            ))
        };
        assert_eq!(scan().collect::<Vec<_>>(), vec!["a", "b", "c"]);
        assert_eq!(scan().up_to(20u64).collect::<Vec<_>>(), vec!["a", "b"]);
        assert_eq!(
            scan().range(20u64..=30u64).collect::<Vec<_>>(),
            vec!["b", "c"]
        );
    }
}
