//! Secondary-index infrastructure for [`StorageMap`](crate::StorageMap) — the one
//! `Map<K, V>`. When the value carries `#[index]` fields the map gains
//! framework-maintained secondary indexes, so filtered reads are prefix scans of a
//! declared index rather than a `keys()` scan-and-filter. A value with no `#[index]`
//! (or a primitive value) is a plain map: [`Indexed::HAS_INDEXES`] is `false` and all
//! of this const-folds out — there is no separate map type.
//!
//! Layout (all ordinary path-prefixed `contract_state` rows, so versioned,
//! reorg-safe, and folded into the checkpoint hash):
//! ```text
//!   <primary>/<key>                              -> V
//!   <primary>#idx/<index_name>/<index_key>/<member> -> () | projection
//! ```
//! A `<member>` is the primary key (unsorted) or a `(sort, pk)` tuple (sorted). A
//! plain index leaf is void (`()`); a COVERING index (`#[index(include = …)]`) stores
//! the covered fields' concatenated codec elements AS the leaf value, so a
//! `.values()`/`.iter()` read returns them without a per-member point read (see
//! [`IndexEntry::projection`] and the covering query types).
//!
//! `index_name(key)` scans `<primary>#idx/<name>/<key>/`, whose child
//! segments ARE the primary keys. A key's index memberships are derived from its
//! value via [`Indexed`] — there is no separate record of them, so the value
//! stays the one source of truth (same as every other generated model). On
//! update the prior entries are recomputed and diffed against the new ones via
//! [`apply_index_diff`]: delete `old − new`, write `new − old`, so an unchanged
//! index (or a no-op re-set) costs zero index ops.
//!
//! Storage-deposit cost: each index entry is an ordinary write (one `contract_state`
//! row), so it carries its own storage deposit (the row's path + value bytes × D) just
//! like the value row — there is no unmetered side channel. A value with N `#[index]`
//! fields therefore counts the value's deposit plus one per live index entry toward its
//! setter's storage-deposit floor; a hot, frequently-rewritten indexed field is the
//! costliest shape. This is intentional (index rows are real, collateralized state),
//! but authors should expect indexed maps to cost proportionally more deposit than
//! plain ones.
//!
//! COVERING (`include = …`) sharpens both edges: the leaf value is no longer empty, so
//! the covered fields' bytes add to that row's deposit (a void leaf is priced on its
//! path alone), AND any change to a covered field rewrites the leaf in place — a write.
//! So covering pays off for COLD / rarely-mutated projections read often through the
//! index (the point: skip a per-member point read), and is a poor trade for a HOT
//! field that churns the leaf on every update while inflating its deposit. Prefer
//! covering immutable-after-create or slowly-changing fields; leave hot fields to a
//! plain index + per-key `get`.
//!
//! The type a contract declares is the inert [`StorageMap`] placeholder; the real
//! per-key `get`/`set`/`remove`/index accessors are generated by the
//! `#[derive(Model)]` field model. The only logic carried here is (a)
//! [`apply_index_diff`], the single audited maintenance routine both the field model
//! and the bulk [`Store`] impl call, and (b) the [`Store`] impl below, which keeps a
//! *wholesale* write of the map (root init, or any nested struct set through
//! `Store`) index-consistent — the field model's per-key path can't catch that.

use alloc::rc::Rc;
use alloc::string::String;
use alloc::vec::Vec;

use crate::keycodec::{self, KeyElement};
use crate::{KeyPath, ReadStorage, Store, WriteStorage};

/// The codec element a value contributes as one index-bucket segment. The SINGLE
/// source every index path encodes through — a value's [`Indexed::index_entries`],
/// the read model's `__index_entries`, the in-place indexed-field setter, and the
/// generated typed index lookup — so the bucket a write lands in and the
/// bucket a lookup scans can never drift.
///
/// A bucket is an equality partition (order *within* it is irrelevant), so the
/// only requirement is a *distinct* element per value — no ordering, unlike a
/// [`KeyElement`] sort key. A [`KeyElement`] type encodes itself (a `u64` bucket
/// is a compact int element; a `Vec<u8>` its raw bytes — no hex). A storage enum
/// keys by its DISCRIMINANT (case name) as a string element, not its payload — so
/// `Failed(r)` always lands in the `"failed"` bucket and changing the payload is a
/// no-op for the index. The `Storage` derive supplies that impl (and a payload-free
/// `<E>Kind` marker for referencing a case without constructing one).
pub trait IndexKey {
    /// One complete, self-delimiting codec element (e.g. from [`KeyElement::encode`]).
    fn index_key(&self) -> Vec<u8>;
}

// A `KeyElement` type buckets by encoding itself — distinct per value, and far
// more compact than its `Display` for ints/bytes (a `u64` is ≤9 bytes vs up to 20
// decimal chars; `Vec<u8>` is raw, not 2× hex). No blanket `impl<T: KeyElement>`:
// it would collide with the discriminant impl the `Storage` derive emits for enums.
macro_rules! index_key_via_keyelement {
    ($($t:ty),*) => {
        $(
            impl IndexKey for $t {
                fn index_key(&self) -> Vec<u8> {
                    KeyElement::encode(self)
                }
            }
        )*
    };
}
index_key_via_keyelement!(bool, u8, u16, u32, u64, i8, i16, i32, i64, String, Vec<u8>);

/// An `Option<T>` indexes by its `none`/`some` **discriminant** (like an enum keys
/// by its case), ignoring the payload — so a composite index can partition on "is
/// this field set?" without a predicate DSL. The discriminant is a string element,
/// matching [`Presence`] (the payload-free marker a typed index lookup passes) and
/// storage enums, so the bucket a write lands in and a lookup scans agree. Blanket
/// over all `T`: `Option` is neither a keyed primitive nor a storage enum, so no
/// impl overlaps it.
impl<T> IndexKey for Option<T> {
    fn index_key(&self) -> Vec<u8> {
        let s = match self {
            None => "none",
            Some(_) => "some",
        };
        String::from(s).encode()
    }
}

/// The payload-free marker for bucketing an `Option` index field by presence —
/// the `Option` analogue of a storage enum's `<E>Kind`. Lets a lookup name the
/// bucket (`eligible(true, Presence::Absent)`) without constructing an
/// `Option` value or writing `None::<T>` with a turbofish. Its [`IndexKey`]
/// matches `Option`'s, so lookup and stored bucket can't drift.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Presence {
    Absent,
    Present,
}

impl IndexKey for Presence {
    fn index_key(&self) -> Vec<u8> {
        let s = match self {
            Presence::Absent => "none",
            Presence::Present => "some",
        };
        String::from(s).encode()
    }
}

/// One secondary-index membership of a value: which index, which bucket, and
/// (optionally) where it sorts within that bucket. The leaf it maps to is
/// `<index>/<bucket…>/<sort‖pk>` (see the `Map` module docs).
///
/// `bucket` is a vec so a composite index can partition on several fields (one
/// segment each, in declared order); a single-field index has one — each a
/// pre-encoded [`IndexKey`] codec element (distinct partitioning, order
/// irrelevant). `sort` is the sort field's pre-encoded codec element
/// (`KeyElement::encode`), which leads the `(sort, pk)` member tuple so the bucket
/// scans in value order. (A covering projection will be added here later as the
/// leaf *value*; the diff already keys on the leaf path so that stays additive.)
pub struct IndexEntry {
    /// The index's interned id (its declaration order within the value type), the
    /// structural `<index>` segment — a dict-ref, like every other structural name.
    /// Per value type; only ever used under that value's `#idx` root, so distinct
    /// value types' id spaces never meet.
    pub name_id: u8,
    pub bucket: Vec<Vec<u8>>,
    pub sort: Option<Vec<u8>>,
    /// The covering projection stored AS the leaf value: the `include=` fields'
    /// order-preserving codec elements, tuple-packed (`None` = a plain void leaf).
    /// It is NOT part of leaf identity (`same_leaf` ignores it) — a member whose
    /// covered value changed keeps the same leaf path, so the diff rewrites the value
    /// in place rather than moving the row.
    pub projection: Option<Vec<u8>>,
}

impl IndexEntry {
    /// The bucket-prefix path `<index>/<bucket…>` (where the count lives; members
    /// are its children). The index name is an interned structural segment; each
    /// bucket segment is a pre-encoded `IndexKey` element.
    fn bucket_path(&self, index_root: &KeyPath) -> KeyPath {
        index_root
            .push_interned(self.name_id)
            .push_raw_elements(&self.bucket)
    }

    /// The member element: the `(sort, pk)` nested tuple (so the bucket sorts by
    /// value, then key), or just the primary-key element when unsorted. `key` is
    /// the already-encoded primary-key element. Both inputs are full codec
    /// elements, so packing them is a tuple wrap.
    fn member_element(&self, key: &[u8]) -> Vec<u8> {
        match &self.sort {
            Some(sort) => keycodec::tuple_from_elements(&[sort, key]),
            None => key.to_vec(),
        }
    }

    /// Two entries share a leaf (same `<index>/<bucket…>/<member>`) iff they agree
    /// on name+bucket+sort. The diff keys on this; a future covering projection is
    /// the leaf *value*, updated in place when the path matches.
    fn same_leaf(&self, other: &IndexEntry) -> bool {
        self.name_id == other.name_id && self.bucket == other.bucket && self.sort == other.sort
    }
}

/// A value's secondary-index memberships. An empty result means "in no index" —
/// partial indexes fall out by omitting an entry when a predicate is false.
///
/// Every storage value implements this — structs/enums via `#[derive(Storage)]`,
/// primitives via the blanket-ish impls below — so one `Map<K, V>` covers both
/// plain and indexed values. `HAS_INDEXES` is a compile-time flag: the generated
/// `set`/`remove` skip all index maintenance when it's `false`, so a non-indexed
/// map compiles to exactly the plain path (verified: no read-before-write emitted).
pub trait Indexed {
    /// Whether this value declares any secondary indexes. Const so callers can
    /// `if <V as Indexed>::HAS_INDEXES { … }` and have the branch const-fold.
    const HAS_INDEXES: bool = false;
    fn index_entries(&self) -> Vec<IndexEntry> {
        Vec::new()
    }
}

// Primitive (leaf) storage values are never indexed. (WIT "primitives" like
// `Integer`/`Decimal`/`Holder` provide `Indexed` in built-in-types; these are the
// bare Rust types.)
macro_rules! impl_indexed_leaf {
    ($($t:ty),* $(,)?) => { $( impl Indexed for $t {} )* };
}
impl_indexed_leaf!(u8, u16, u32, u64, i32, i64, bool, String, Vec<u8>, ());

/// Reconcile one key's index rows from `old` to `new`: delete entries in `old`
/// that aren't in `new`, write entries in `new` that weren't in `old`. Unchanged
/// entries are left untouched (zero ops). Index roots are siblings of the
/// primary map.
///
/// `key` is the primary key's already-encoded codec element. Type-erased (raw
/// bytes, not generic `K`) so this stays the one audited routine every caller —
/// of differing key types — funnels through; the typed call sites encode. Because
/// every segment is now a self-delimiting codec element, a key may contain any
/// content (no delimiter to alias on — what the old `.`-join had to reject).
///
/// The caller computes `old`/`new`: the field model's `set`/`remove` load the
/// prior value and read its `Indexed::index_entries`; an in-place indexed-field
/// setter diffs just that field's entry; the bulk [`Store`] impl starts from
/// empty (a fresh wholesale write). Either way the maintenance logic lives only
/// here.
pub fn apply_index_diff<S: WriteStorage + ReadStorage + ?Sized>(
    ctx: &Rc<S>,
    index_root: &KeyPath,
    key: &[u8],
    old: &[IndexEntry],
    new: &[IndexEntry],
) {
    for entry in old {
        if !new.iter().any(|n| n.same_leaf(entry)) {
            let bucket = entry.bucket_path(index_root);
            // Decrement ONLY when the delete actually removed a live row.
            // `__delete` returns false for a no-op (the entry was already
            // tombstoned or never written — an index/count that drifted); counting
            // that as a removal would underflow the bucket count and trap. The
            // delete result is the authority on whether membership changed.
            if ctx.__delete(&bucket.push_raw_element(&entry.member_element(key))) {
                bump_bucket_count(ctx, &bucket, false);
            }
        }
    }
    for entry in new {
        if !old.iter().any(|o| o.same_leaf(entry)) {
            let bucket = entry.bucket_path(index_root);
            write_leaf(
                ctx,
                &bucket.push_raw_element(&entry.member_element(key)),
                entry,
            );
            bump_bucket_count(ctx, &bucket, true);
        }
    }
    // Covering only: a member whose LEAF (name+bucket+sort) is unchanged but whose
    // COVERED value changed keeps the same row — rewrite the leaf value in place, no
    // membership/count change. (`same_leaf` deliberately excludes the projection, so
    // this case is invisible to the delete/add passes above.)
    for entry in new {
        if let Some(prev) = old.iter().find(|o| o.same_leaf(entry))
            && prev.projection != entry.projection
        {
            let leaf = entry
                .bucket_path(index_root)
                .push_raw_element(&entry.member_element(key));
            write_leaf(ctx, &leaf, entry);
        }
    }
}

/// Write an index member's leaf: the covering projection as the value when present,
/// else a void (unit) leaf — the two shapes an index row can take.
fn write_leaf<S: WriteStorage + ?Sized>(ctx: &Rc<S>, leaf: &[u8], entry: &IndexEntry) {
    match &entry.projection {
        Some(projection) => ctx.__set_list_u8(leaf, projection.clone()),
        None => ctx.__set_void(leaf),
    }
}

/// Adjust a bucket's framework-maintained member count. The count lives AT the
/// bucket-prefix path (`<map>#idx/<name>/<key>`); the bucket's members are its
/// CHILDREN (`…/<key>/<primary_key>`), so this value is invisible to the
/// index child-scan and to `keys()`. Maintained only here — the one site
/// every index add/remove funnels through (field-model `set`/`remove`, in-place
/// setter, and the bulk `Store`) — so it can't drift from the membership it
/// counts. It's an ordinary height-versioned `contract_state` row, so it rolls
/// back with everything else on a reorg.
fn bump_bucket_count<S: WriteStorage + ReadStorage + ?Sized>(
    ctx: &Rc<S>,
    bucket: &KeyPath,
    up: bool,
) {
    let current = ctx.__get_u64(bucket).unwrap_or(0);
    // A decrement always follows a counted insert (reorgs roll the count row back
    // as versioned state, they don't decrement), so underflow can only mean a
    // framework bug. Trap loudly and deterministically rather than clamp and let a
    // wrong count drive wrong decisions — surfacing corruption, not masking it.
    let next = if up {
        current + 1
    } else {
        current
            .checked_sub(1)
            .expect("Map bucket count underflow — framework bug")
    };
    ctx.__set_u64(bucket, next);
}

// The write TARGET (`S2`) is decoupled from the map's phantom context
// parameter (`S1`): a `Map` field is declared with the contract-local alias
// (fixing `S1`), but the containing struct's `Store` derive is generic over
// the handle it writes through.
impl<K, V, S1, S2> Store<S2> for crate::StorageMap<K, V, S1>
where
    K: KeyElement + Clone,
    V: Store<S2> + Clone + Indexed,
    S2: WriteStorage + ReadStorage + ?Sized,
{
    /// Wholesale write: persist every entry's value, plus its index rows when the
    /// value type declares indexes, so a map populated before `init` (at the root
    /// or any nested level) lands index-consistent. The index root is the
    /// `<primary>#idx` sibling, derived from `base_path` the same way the field
    /// model builds it. An upsert from empty (adds rows; per-key updates that must
    /// diff go through the field model's `set`). For a non-indexed value
    /// `HAS_INDEXES` is `false`, so the index block const-folds out and this is the
    /// plain entry write.
    fn __set(ctx: &Rc<S2>, base_path: KeyPath, value: crate::StorageMap<K, V, S1>) {
        for (k, v) in value.entries.into_iter() {
            if V::HAS_INDEXES
                && let Some(index_root) = base_path.interned_index_sibling()
            {
                apply_index_diff(ctx, &index_root, &k.encode(), &[], &v.index_entries());
            }
            ctx.__set(base_path.push_element(&k), v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate as stdlib;
    use crate::keycodec::next_element;
    use crate::query::*;
    use crate::{HasNextRow, ReadStorage, ScalarStorage, make_storage_rows_iterator};
    use crate::{Model, Storage, StorageMap};
    use alloc::collections::BTreeMap;
    use alloc::string::ToString;
    use alloc::vec;
    use core::cell::RefCell;
    use core::ops::Bound;

    #[derive(Clone)]
    enum Cell {
        U64(u64),
        Void,
        Bytes(Vec<u8>),
    }

    struct MockRows<I>(RefCell<I>);

    impl<I: Iterator<Item = (Vec<u8>, Cell)>> HasNextRow for MockRows<I> {
        fn next_list_u8(&self) -> Option<(Vec<u8>, Vec<u8>)> {
            self.0.borrow_mut().next().map(|(key, cell)| match cell {
                Cell::Bytes(value) => (key, value),
                _ => panic!("expected byte slot"),
            })
        }
        fn next_u64(&self) -> Option<(Vec<u8>, u64)> {
            self.0.borrow_mut().next().map(|(key, cell)| match cell {
                Cell::U64(value) => (key, value),
                _ => panic!("expected u64 slot"),
            })
        }
        fn next_str(&self) -> Option<(Vec<u8>, String)> {
            unimplemented!()
        }
        fn next_s64(&self) -> Option<(Vec<u8>, i64)> {
            unimplemented!()
        }
        fn next_bool(&self) -> Option<(Vec<u8>, bool)> {
            unimplemented!()
        }
    }

    #[derive(Clone, Default)]
    struct Mock {
        map: Rc<RefCell<BTreeMap<Vec<u8>, Cell>>>,
        void_sets: RefCell<usize>,
        deletes: RefCell<usize>,
        key_scans: RefCell<usize>,
        row_scans: RefCell<usize>,
    }

    impl stdlib::HasViewStorage for Mock {
        type View = Self;
        fn view_storage(&self) -> Self {
            self.clone()
        }
    }

    impl ReadStorage for Mock {
        fn __get_u64(self: &Rc<Self>, path: &[u8]) -> Option<u64> {
            match self.map.borrow().get(path) {
                Some(Cell::U64(v)) => Some(*v),
                _ => None,
            }
        }
        fn __get_keys_range<T: KeyElement + Clone>(
            self: &Rc<Self>,
            path: &[u8],
            lo: Option<&[u8]>,
            hi: Option<&[u8]>,
            descending: bool,
        ) -> impl Iterator<Item = T> + use<T> {
            *self.key_scans.borrow_mut() += 1;
            // Distinct child elements: byte-prefix the path, take the next element
            // of the suffix (mirrors the host's `next_element` extraction).
            let mut elems: Vec<Vec<u8>> = self
                .map
                .borrow()
                .keys()
                .filter_map(|k| {
                    let rest = k.as_slice().strip_prefix(path)?;
                    if rest.is_empty() {
                        return None;
                    }
                    Some(next_element(rest).ok()?.0.to_vec())
                })
                .collect();
            elems.sort();
            elems.dedup();
            // Host-side `[lo, hi)` seek by raw byte order — inclusive `>= path ++ lo`,
            // exclusive `< path ++ hi` (see `path_prefix_filter_contract_state` /
            // `scan_bounds`). `descending` reverses only the iteration order.
            let lo = lo.map(<[u8]>::to_vec);
            let hi = hi.map(<[u8]>::to_vec);
            if descending {
                elems.reverse();
            }
            elems.into_iter().filter_map(move |e| {
                if lo.as_deref().is_some_and(|l| e.as_slice() < l) {
                    return None;
                }
                if hi.as_deref().is_some_and(|h| e.as_slice() >= h) {
                    return None;
                }
                let (v, _) = T::decode_from(&e).unwrap();
                Some(v)
            })
        }
        fn __get_storage_rows_range<V: ScalarStorage>(
            self: &Rc<Self>,
            path: &[u8],
            lo: Option<&[u8]>,
            hi: Option<&[u8]>,
            descending: bool,
        ) -> impl Iterator<Item = (Vec<u8>, V)> + use<V> {
            *self.row_scans.borrow_mut() += 1;
            // Direct-child leaves under `path`, as (member-element, leaf value bytes) —
            // the covering projection is stored as list_u8 (`Cell::Bytes`). Mirrors the
            // host's member extraction + `[lo, hi)` seek; the count row (at exactly
            // `path`) is excluded by the non-empty-suffix check.
            let mut rows: Vec<(Vec<u8>, Cell)> = self
                .map
                .borrow()
                .iter()
                .filter_map(|(k, cell)| {
                    let rest = k.as_slice().strip_prefix(path)?;
                    if rest.is_empty() {
                        return None;
                    }
                    let (elem, tail) = next_element(rest).ok()?;
                    if !tail.is_empty() {
                        return None; // not a direct leaf
                    }
                    match cell {
                        Cell::Bytes(_) | Cell::U64(_) => Some((elem.to_vec(), cell.clone())),
                        Cell::Void => None,
                    }
                })
                .collect();
            rows.sort_by(|a, b| a.0.cmp(&b.0));
            rows.dedup_by(|a, b| a.0 == b.0);
            let lo = lo.map(<[u8]>::to_vec);
            let hi = hi.map(<[u8]>::to_vec);
            if descending {
                rows.reverse();
            }
            let rows = rows.into_iter().filter(move |(m, _)| {
                lo.as_deref().is_none_or(|l| m.as_slice() >= l)
                    && hi.as_deref().is_none_or(|h| m.as_slice() < h)
            });
            make_storage_rows_iterator(MockRows(RefCell::new(rows)))
        }
        fn __get<T: crate::Retrieve<Self>>(self: &Rc<Self>, path: KeyPath) -> Option<T> {
            T::__get(self, path)
        }
        fn __get_str(self: &Rc<Self>, _: &[u8]) -> Option<String> {
            unimplemented!()
        }
        fn __get_s64(self: &Rc<Self>, _: &[u8]) -> Option<i64> {
            unimplemented!()
        }
        fn __get_bool(self: &Rc<Self>, _: &[u8]) -> Option<bool> {
            unimplemented!()
        }
        fn __get_list_u8(self: &Rc<Self>, path: &[u8]) -> Option<Vec<u8>> {
            match self.map.borrow().get(path) {
                Some(Cell::Bytes(v)) => Some(v.clone()),
                _ => None,
            }
        }
        fn __exists(self: &Rc<Self>, path: &[u8]) -> bool {
            self.map.borrow().keys().any(|key| key.starts_with(path))
        }
        fn __extend_path_with_match(
            self: &Rc<Self>,
            path: &[u8],
            candidates: &[Vec<u8>],
        ) -> Option<u32> {
            candidates
                .iter()
                .position(|candidate| {
                    let mut child = path.to_vec();
                    child.extend(candidate);
                    self.__exists(&child)
                })
                .map(|index| index as u32)
        }
    }

    impl WriteStorage for Mock {
        fn __set_u64(self: &Rc<Self>, path: &[u8], value: u64) {
            self.map
                .borrow_mut()
                .insert(path.to_vec(), Cell::U64(value));
        }
        fn __set_void(self: &Rc<Self>, path: &[u8]) {
            *self.void_sets.borrow_mut() += 1;
            self.map.borrow_mut().insert(path.to_vec(), Cell::Void);
        }
        fn __delete(self: &Rc<Self>, path: &[u8]) -> bool {
            *self.deletes.borrow_mut() += 1;
            let mut map = self.map.borrow_mut();
            let before = map.len();
            map.retain(|key, _| !key.starts_with(path));
            map.len() != before
        }
        fn __set<T: Store<Self>>(self: &Rc<Self>, path: KeyPath, value: T) {
            T::__set(self, path, value)
        }
        fn __set_str(self: &Rc<Self>, _: &[u8], _: &str) {
            unimplemented!()
        }
        fn __set_s64(self: &Rc<Self>, _: &[u8], _: i64) {
            unimplemented!()
        }
        fn __set_bool(self: &Rc<Self>, _: &[u8], _: bool) {
            unimplemented!()
        }
        fn __set_list_u8(self: &Rc<Self>, path: &[u8], value: Vec<u8>) {
            self.map
                .borrow_mut()
                .insert(path.to_vec(), Cell::Bytes(value));
        }
        fn __delete_matching_paths(self: &Rc<Self>, path: &[u8], candidates: &[Vec<u8>]) -> u64 {
            candidates
                .iter()
                .filter(|candidate| {
                    let mut child = path.to_vec();
                    child.extend(*candidate);
                    self.__delete(&child)
                })
                .count() as u64
        }
    }

    // A path from a dotted string (each piece a string-element segment) → codec bytes.
    fn p(s: &str) -> KeyPath {
        KeyPath::from(s)
    }

    // Codec bytes of a `KeyPath` (e.g. one ending in a typed key element).
    fn b(path: KeyPath) -> Vec<u8> {
        path.as_bytes().to_vec()
    }

    // The interned id a real contract's macro would assign a Map field
    // (its declaration index). Wholesale `Store` derives the `#idx` sibling from
    // this via `interned_index_sibling`, so the map-field segment MUST be interned
    // (not a string) for those tests to mirror production.
    const IM: u8 = 0;

    // A primary key encoded as its codec element (what `apply_index_diff` takes,
    // and the member segment of an unsorted index).
    fn kb(k: impl KeyElement) -> Vec<u8> {
        k.encode()
    }

    // A test index name's interned id. The real `Storage` derive assigns ids by
    // declaration order; these direct unit tests don't run the macro, so we map
    // names to stable ids here (distinct within a single `#idx` root: status≠owner).
    fn nid(name: &str) -> u8 {
        match name {
            "status" => 0,
            "owner" => 1,
            "name" => 0,
            "eligible" => 0,
            "due" => 0,
            "tag" => 0,
            other => panic!("unknown test index name `{other}`"),
        }
    }

    // The interned `<index>` segment under an `#idx` root — what `bucket_path`
    // builds. Lets assertions mirror the production (interned) index-name encoding.
    fn ix(root: &KeyPath, name: &str) -> KeyPath {
        root.push_interned(nid(name))
    }

    // A single-field index entry (one bucket segment, unsorted) — the shape the
    // shipped `#[index]` produces.
    fn e(name: &str, key: &str) -> IndexEntry {
        IndexEntry {
            name_id: nid(name),
            bucket: alloc::vec![key.to_string().encode()],
            sort: None,
            projection: None,
        }
    }

    #[derive(Clone, Storage)]
    #[index(live, by = owner, sort = score, include = amount, when = matches!(status, 1 | 2))]
    #[index(all, by = owner)]
    struct ConditionalItem {
        owner: u64,
        status: u64,
        score: u64,
        amount: u64,
    }

    type Map<K, V> = StorageMap<K, V, Mock>;

    #[derive(Model)]
    #[allow(dead_code)]
    struct ConditionalStore {
        items: Map<u64, ConditionalItem>,
    }

    #[test]
    fn conditional_indexes_follow_record_and_field_updates() {
        let ctx = Rc::new(Mock::default());
        let model = ConditionalStoreWriteModel::new(ctx.clone(), KeyPath::from("conditional"));
        let items = model.items();
        let first = ConditionalItem {
            owner: 7,
            status: 0,
            score: 10,
            amount: 20,
        };
        items.set(&1, first.clone());
        items.set(
            &2,
            ConditionalItem {
                status: 1,
                ..first.clone()
            },
        );
        assert_eq!(items.all(7).len(), 2);
        assert_eq!(items.live(7).keys().collect::<Vec<_>>(), vec![2]);
        let item = items.get(&1).unwrap();
        item.set_score(3);
        item.set_amount(8);
        item.set_owner(9);
        assert!(items.live(9).is_empty());
        assert!(item.try_update_status(|_| Err("rejected".into())).is_err());
        assert!(items.live(9).is_empty());
        item.update_status(|_| 1);
        assert_eq!(items.live(9).len(), 1);
        assert_eq!(items.live(9).values().next().unwrap().amount, 8);
        item.set_status(2);
        item.set_status(2);
        assert_eq!(items.live(9).len(), 1);
        item.set_score(12);
        item.set_amount(30);
        item.set_owner(7);
        assert!(items.live(9).is_empty());
        assert_eq!(items.live(7).keys().collect::<Vec<_>>(), vec![2, 1]);
        assert_eq!(
            items.live(7).range(..=10).keys().collect::<Vec<_>>(),
            vec![2]
        );
        assert_eq!(items.live(7).values().last().unwrap().amount, 30);
        item.set_status(0);
        assert_eq!(items.live(7).len(), 1);
        assert_eq!(items.all(7).len(), 2);
        items.set(
            &1,
            ConditionalItem {
                status: 2,
                ..first.clone()
            },
        );
        assert_eq!(items.live(7).len(), 2);
        items.set(&1, first);
        assert_eq!(items.live(7).len(), 1);
        assert!(items.remove(&1));
        assert_eq!(items.live(7).len(), 1);
        assert!(items.remove(&2));
        assert!(items.live(7).is_empty());
        assert!(items.all(7).is_empty());
        assert!(!items.remove(&2));
    }

    #[derive(Clone, Storage)]
    enum OptionalStatus {
        Active,
        Closed,
    }

    #[derive(Clone, Storage)]
    #[index(live, by = owner, include = amount,
        when = matches!(status, Option::Some(OptionalStatus::Active)))]
    struct OptionalRecord {
        owner: u64,
        amount: u64,
        status: Option<OptionalStatus>,
    }

    #[derive(Model)]
    #[allow(dead_code)]
    struct OptionalStore {
        records: Map<u64, OptionalRecord>,
    }

    #[test]
    fn optional_enum_predicates_materialize_values_on_every_write_path() {
        let ctx = Rc::new(Mock::default());
        let model = OptionalStoreWriteModel::new(ctx, KeyPath::from("optional"));
        let records = model.records();
        records.set(
            &1,
            OptionalRecord {
                owner: 7,
                amount: 10,
                status: None,
            },
        );
        records.set(
            &2,
            OptionalRecord {
                owner: 7,
                amount: 20,
                status: Some(OptionalStatus::Active),
            },
        );
        assert_eq!(records.live(7).keys().collect::<Vec<_>>(), vec![2]);
        let record = records.get(&1).unwrap();
        record.set_status(Some(OptionalStatus::Active));
        record.set_amount(30);
        record.set_owner(9);
        assert_eq!(records.live(9).values().next().unwrap().amount, 30);
        record.set_status(Some(OptionalStatus::Closed));
        assert!(records.live(9).is_empty());
        record.set_status(Some(OptionalStatus::Active));
        record.set_status(None);
        assert!(records.live(9).is_empty());
        records.set(
            &2,
            OptionalRecord {
                owner: 7,
                amount: 40,
                status: Some(OptionalStatus::Closed),
            },
        );
        assert!(records.live(7).is_empty());
        records.set(
            &2,
            OptionalRecord {
                owner: 7,
                amount: 50,
                status: Some(OptionalStatus::Active),
            },
        );
        assert!(records.remove(&2));
        assert!(records.live(7).is_empty());
    }

    #[derive(Clone, Storage)]
    struct Details {
        amount: u64,
    }

    #[derive(Clone, Storage)]
    enum PayloadStatus {
        Closed,
        Ready,
        Details(Details),
        Step(u64),
    }

    #[derive(Clone, Storage)]
    #[index(live, by = owner, include = amount,
        when = matches!(status, PayloadStatus::Ready | PayloadStatus::Details(_)))]
    #[index(details, by = owner, when = matches!(status, PayloadStatus::Details(..)))]
    #[index(optional, by = owner,
        when = matches!(extra, Option::Some(PayloadStatus::Details(_))))]
    #[index(present, by = owner, when = matches!(extra, Option::Some(_)))]
    #[index(first_step, by = owner, when = matches!(status, PayloadStatus::Step(1)))]
    struct PayloadRecord {
        owner: u64,
        amount: u64,
        status: PayloadStatus,
        extra: Option<PayloadStatus>,
    }

    #[derive(Model)]
    #[allow(dead_code)]
    struct PayloadStore {
        records: Map<u64, PayloadRecord>,
    }

    #[test]
    fn tag_predicates_survive_descendant_edits_and_reconcile_parent_updates() {
        let ctx = Rc::new(Mock::default());
        let model = PayloadStoreWriteModel::new(ctx, KeyPath::from("payload"));
        let records = model.records();
        records.set(
            &1,
            PayloadRecord {
                owner: 7,
                amount: 10,
                status: PayloadStatus::Details(Details { amount: 1 }),
                extra: Some(PayloadStatus::Details(Details { amount: 2 })),
            },
        );
        let record = records.get(&1).unwrap();
        let PayloadStatusWriteModel::Details(details) = record.status() else {
            panic!("expected details");
        };
        details.set_amount(99);
        let Some(PayloadStatusWriteModel::Details(extra)) = record.extra() else {
            panic!("expected optional details");
        };
        extra.set_amount(100);
        assert!(matches!(
            record.load().status,
            PayloadStatus::Details(Details { amount: 99 })
        ));
        assert!(matches!(
            record.load().extra,
            Some(PayloadStatus::Details(Details { amount: 100 }))
        ));
        assert_eq!(records.live(7).keys().collect::<Vec<_>>(), vec![1]);
        assert_eq!(records.live(7).values().next().unwrap().amount, 10);
        assert_eq!(records.details(7).len(), 1);
        assert_eq!(records.optional(7).len(), 1);
        assert_eq!(records.present(7).len(), 1);

        record.set_owner(9);
        record.set_amount(20);
        assert!(records.live(7).is_empty());
        assert!(records.details(7).is_empty());
        assert!(records.optional(7).is_empty());
        assert_eq!(records.live(9).values().next().unwrap().amount, 20);
        assert_eq!(records.details(9).len(), 1);
        assert_eq!(records.optional(9).len(), 1);
        record.set_status(PayloadStatus::Ready);
        assert_eq!(records.live(9).len(), 1);
        assert!(records.details(9).is_empty());
        record.set_extra(Some(PayloadStatus::Step(3)));
        assert!(records.optional(9).is_empty());
        assert_eq!(records.present(9).len(), 1);
        record.set_extra(None);
        assert!(records.present(9).is_empty());
        record.set_status(PayloadStatus::Closed);
        assert!(records.live(9).is_empty());
        record.set_status(PayloadStatus::Step(1));
        assert_eq!(records.first_step(9).len(), 1);
        record.set_status(PayloadStatus::Step(2));
        assert!(records.first_step(9).is_empty());

        records.set(
            &1,
            PayloadRecord {
                owner: 7,
                amount: 30,
                status: PayloadStatus::Details(Details { amount: 3 }),
                extra: None,
            },
        );
        assert_eq!(records.live(7).len(), 1);
        assert_eq!(records.details(7).len(), 1);
        assert!(records.remove(&1));
        assert!(records.live(7).is_empty());
        assert!(records.details(7).is_empty());
    }

    // A struct value with one indexed field — the shape a Map holds.
    #[derive(Clone)]
    struct Position {
        status: u64,
    }

    impl Store<Mock> for Position {
        fn __set(ctx: &Rc<Mock>, base_path: KeyPath, value: Position) {
            ctx.__set(base_path.push("status"), value.status);
        }
    }

    impl Indexed for Position {
        const HAS_INDEXES: bool = true;
        fn index_entries(&self) -> Vec<IndexEntry> {
            alloc::vec![e("status", &self.status.to_string())]
        }
    }

    // Drive `apply_index_diff` directly — the routine both the field model and
    // the bulk Store impl delegate to.
    #[test]
    fn apply_index_diff_reconciles_entries() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // From nothing -> {status:active, owner:1}: two writes.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[],
            &[e("status", "active"), e("owner", "1")],
        );
        assert_eq!(*ctx.void_sets.borrow(), 2);
        assert_eq!(*ctx.deletes.borrow(), 0);

        // {active,1} -> {proven,1}: only status moves (1 delete + 1 write); owner
        // is unchanged and untouched.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[e("status", "active"), e("owner", "1")],
            &[e("status", "proven"), e("owner", "1")],
        );
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(*ctx.void_sets.borrow(), 3); // 2 + 1

        // A no-op re-set (old == new) touches nothing.
        *ctx.void_sets.borrow_mut() = 0;
        *ctx.deletes.borrow_mut() = 0;
        let same = [e("status", "proven"), e("owner", "1")];
        apply_index_diff(&ctx, &index, &kb("k".to_string()), &same, &same);
        assert_eq!(*ctx.deletes.borrow(), 0);
        assert_eq!(*ctx.void_sets.borrow(), 0);

        // The status entry moved buckets; the owner entry is still in place. The
        // `<index>` name segment is interned (`ix`); the bucket value + member stay
        // string elements (what `e`/`kb` produce).
        assert!(ctx.__exists(&b(ix(&index, "status").push("proven").push("k"))));
        assert!(!ctx.__exists(&b(ix(&index, "status").push("active").push("k"))));
        assert!(ctx.__exists(&b(ix(&index, "owner").push("1").push("k"))));

        // Framework-maintained bucket counts track the membership: status moved
        // active(0) -> proven(1); owner.1 stayed at 1.
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "status").push("proven"))),
            Some(1)
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "status").push("active"))),
            Some(0)
        );
        assert_eq!(ctx.__get_u64(&b(ix(&index, "owner").push("1"))), Some(1));
    }

    // A removal whose index row isn't live (already tombstoned / never written —
    // a count that drifted) must be a no-op for the count, NOT a decrement: the
    // `__delete` returns false, and decrementing anyway would underflow the bucket
    // count and trap mid-update. Regression for "index diff ignores delete result".
    #[test]
    fn apply_index_diff_noop_delete_does_not_decrement() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");

        // `old` claims `k` is in the `status.active` bucket, but no void row was
        // ever written there and the count is unset (0). Removing it is a no-op
        // delete; an unconditional decrement would `checked_sub(0)` → trap.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[e("status", "active")],
            &[],
        );

        // Reaching here means no trap. The delete was attempted but removed
        // nothing, so the (absent) count was left untouched.
        assert_eq!(*ctx.deletes.borrow(), 1);
        assert_eq!(ctx.__get_u64(&b(ix(&index, "status").push("active"))), None);
    }

    // The bulk `Store` path: a map populated before a wholesale write must land
    // with both its primary values and its index rows.
    #[test]
    fn bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let m = StorageMap::<u64, Position, Mock>::new(&[
            (1, Position { status: 2 }),
            (2, Position { status: 2 }),
            (3, Position { status: 5 }),
        ]);

        let base = KeyPath::new().push_interned(IM); // the interned `positions` field
        Store::__set(&ctx, base.clone(), m);

        // Primary values (stored under the value's own field path; the u64 map key
        // is a native int element, not a stringified segment).
        assert_eq!(
            ctx.__get_u64(&b(base.push_element(&1u64).push("status"))),
            Some(2)
        );
        assert_eq!(
            ctx.__get_u64(&b(base.push_element(&3u64).push("status"))),
            Some(5)
        );

        // Index rows, in the `#idx` sibling (derived the same way production does).
        // The member is the u64 primary key.
        let idx = base.interned_index_sibling().unwrap();
        assert!(ctx.__exists(&b(ix(&idx, "status").push("2").push_element(&1u64))));
        assert!(ctx.__exists(&b(ix(&idx, "status").push("2").push_element(&2u64))));
        assert!(ctx.__exists(&b(ix(&idx, "status").push("5").push_element(&3u64))));

        // Index members resolve to primary keys.
        let bucket = ix(&idx, "status").push("2");
        let mut keys: Vec<u64> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, vec![1, 2]);

        // The bulk path maintains bucket counts too (it funnels through
        // apply_index_diff): status 2 has {1,2}, status 5 has {3}.
        assert_eq!(ctx.__get_u64(&b(ix(&idx, "status").push("2"))), Some(2));
        assert_eq!(ctx.__get_u64(&b(ix(&idx, "status").push("5"))), Some(1));
        // The count lives AT the bucket path, NOT as a child — so it never leaks
        // into an index scan of that bucket's members.
        assert_eq!(ctx.__get_keys::<u64>(&bucket).count(), 2);
    }

    // An Map nested inside a struct. Its `Store::__set` writes the field
    // wholesale, the way a derived struct `Store` does — this is the recursive
    // bulk path that the field model's per-key writes can't see.
    #[derive(Clone, Default)]
    struct Account {
        positions: StorageMap<u64, Position, Mock>,
    }

    impl Store<Mock> for Account {
        fn __set(ctx: &Rc<Mock>, base_path: KeyPath, value: Account) {
            // `positions` is an interned field name (as the macro would emit).
            ctx.__set(base_path.push_interned(IM), value.positions);
        }
    }

    // Account itself has no indexes; it only nests an indexed map.
    impl Indexed for Account {}

    // The recursive case: writing a struct wholesale must keep a *nested*
    // Map index-consistent, with the index sibling derived at the right
    // depth (`account.positions#idx`, not `positions#idx`).
    #[test]
    fn nested_bulk_store_set_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let account = Account {
            positions: StorageMap::new(&[(1, Position { status: 2 }), (2, Position { status: 5 })]),
        };

        Store::__set(&ctx, p("account"), account);

        // The nested `positions` field, interned under `account`.
        let base = p("account").push_interned(IM);

        // Primary values land under the nested path.
        assert_eq!(
            ctx.__get_u64(&b(base.push_element(&1u64).push("status"))),
            Some(2)
        );

        // Index rows are the `#idx` sibling *at depth* — same path the field
        // model would build (parent `account` + `positions#idx`).
        let idx = base.interned_index_sibling().unwrap();
        assert!(ctx.__exists(&b(ix(&idx, "status").push("2").push_element(&1u64))));
        assert!(ctx.__exists(&b(ix(&idx, "status").push("5").push_element(&2u64))));

        let bucket = ix(&idx, "status").push("2");
        assert_eq!(ctx.__get_keys::<u64>(&bucket).collect::<Vec<_>>(), vec![1]);
    }

    // An Map reached through a plain `Map` *value*. Bulk-writing a
    // `Map<K, Account>` flows through the UNMODIFIED `StorageMap::__set`, which
    // dispatches each value to `Account::__set`, which reaches the nested
    // Map's index-aware `Store`. The index must still be maintained.
    #[test]
    fn indexed_map_in_map_value_maintains_indexes() {
        let ctx = Rc::new(Mock::default());
        let accounts = crate::StorageMap::<u64, Account, Mock>::new(&[
            (
                7,
                Account {
                    positions: StorageMap::new(&[(1, Position { status: 2 })]),
                },
            ),
            (
                8,
                Account {
                    positions: StorageMap::new(&[(1, Position { status: 5 })]),
                },
            ),
        ]);

        Store::__set(&ctx, p("accounts"), accounts);

        // Inner index rows land at the nested depth for each map entry (outer and
        // inner keys are u64 elements; `positions`/`#idx` are interned, the bucket
        // name/value segments are strings).
        let pos7 = p("accounts").push_element(&7u64).push_interned(IM);
        let pos8 = p("accounts").push_element(&8u64).push_interned(IM);
        assert!(
            ctx.__exists(&b(ix(&pos7.interned_index_sibling().unwrap(), "status")
                .push("2")
                .push_element(&1u64)))
        );
        assert!(
            ctx.__exists(&b(ix(&pos8.interned_index_sibling().unwrap(), "status")
                .push("5")
                .push_element(&1u64)))
        );
        assert_eq!(
            ctx.__get_u64(&b(pos7.push_element(&1u64).push("status"))),
            Some(2)
        );
    }

    // A plain `Map` nested inside a Map *value*. The outer index is keyed
    // off the value (`tag`); the inner map is just data. Both must persist.
    #[derive(Clone, Default)]
    struct Bag {
        tag: u64,
        items: crate::StorageMap<u64, u64, Mock>,
    }

    impl Store<Mock> for Bag {
        fn __set(ctx: &Rc<Mock>, base_path: KeyPath, value: Bag) {
            ctx.__set(base_path.push("tag"), value.tag);
            ctx.__set(base_path.push("items"), value.items);
        }
    }

    impl Indexed for Bag {
        const HAS_INDEXES: bool = true;
        fn index_entries(&self) -> Vec<IndexEntry> {
            alloc::vec![e("tag", &self.tag.to_string())]
        }
    }

    #[test]
    fn map_in_indexed_map_value() {
        let ctx = Rc::new(Mock::default());
        let bags = StorageMap::<u64, Bag, Mock>::new(&[(
            1,
            Bag {
                tag: 9,
                items: crate::StorageMap::new(&[(100, 1), (200, 2)]),
            },
        )]);

        let base = KeyPath::new().push_interned(IM); // the interned `bags` field
        Store::__set(&ctx, base.clone(), bags);

        // Outer index maintained by the value's `tag` (member is the u64 key 1).
        let idx = base.interned_index_sibling().unwrap();
        assert!(ctx.__exists(&b(ix(&idx, "tag").push("9").push_element(&1u64))));
        // Inner map data persisted under the value's path (u64 key + u64 item keys).
        assert_eq!(
            ctx.__get_u64(&b(base
                .push_element(&1u64)
                .push("items")
                .push_element(&100u64))),
            Some(1)
        );
        assert_eq!(
            ctx.__get_u64(&b(base
                .push_element(&1u64)
                .push("items")
                .push_element(&200u64))),
            Some(2)
        );
    }

    // A primary key may now contain the old path delimiter `.`: every segment is a
    // self-delimiting codec element, so a `.` is just content — distinct, recoverable
    // bytes — not a separator that aliases (what the old `.`-join had to reject).
    #[test]
    fn dotted_keys_are_just_content() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        apply_index_diff(&ctx, &index, &kb("a.b".to_string()), &[], &[e("name", "x")]);
        apply_index_diff(&ctx, &index, &kb("a".to_string()), &[], &[e("name", "x")]);
        // Distinct members despite the `.` — both live under the same bucket.
        let bucket = ix(&index, "name").push("x");
        let mut keys: Vec<String> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["a".to_string(), "a.b".to_string()]);
        assert_eq!(ctx.__get_u64(&b(ix(&index, "name").push("x"))), Some(2));
    }

    // A covering index entry stores its projection AS the leaf value (not a void
    // leaf), and a change to the covered value — same bucket/sort, so the SAME leaf
    // path — rewrites that value in place: no delete/add, no count change.
    #[test]
    fn covering_projection_written_and_rewritten_in_place() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let entry = |proj: &[u8]| IndexEntry {
            name_id: nid("status"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: None,
            projection: Some(proj.to_vec()),
        };
        let leaf = b(ix(&index, "status").push("active").push("k"));

        // Create: the leaf holds the projection VALUE, and the count bumps.
        apply_index_diff(&ctx, &index, &kb("k".to_string()), &[], &[entry(b"v1")]);
        assert_eq!(ctx.__get_list_u8(&leaf), Some(b"v1".to_vec()));
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "status").push("active"))),
            Some(1)
        );

        // Same leaf, changed projection → in-place value rewrite (no delete, count 1).
        *ctx.deletes.borrow_mut() = 0;
        apply_index_diff(
            &ctx,
            &index,
            &kb("k".to_string()),
            &[entry(b"v1")],
            &[entry(b"v2")],
        );
        assert_eq!(ctx.__get_list_u8(&leaf), Some(b"v2".to_vec()));
        assert_eq!(
            *ctx.deletes.borrow(),
            0,
            "a same-leaf projection change must not delete the row"
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "status").push("active"))),
            Some(1)
        );
    }

    // Deposit relevance: a plain index leaf is void (no value bytes → priced on its
    // path alone), while a covering leaf stores the projection (its bytes add to that
    // row's storage deposit, since the host meters every write as (path + value) × D).
    // The host deposit path is generic — this asserts the one covering-specific input
    // to it: the leaf value is non-empty exactly when the index covers.
    #[test]
    fn covering_leaf_carries_value_bytes_unlike_void_plain_leaf() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let plain = IndexEntry {
            name_id: nid("status"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: None,
            projection: None,
        };
        let covering = IndexEntry {
            name_id: nid("status"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: None,
            projection: Some(b"payload".to_vec()),
        };
        apply_index_diff(&ctx, &index, &kb("plain".to_string()), &[], &[plain]);
        apply_index_diff(&ctx, &index, &kb("cover".to_string()), &[], &[covering]);

        let plain_leaf = b(ix(&index, "status").push("active").push("plain"));
        let cover_leaf = b(ix(&index, "status").push("active").push("cover"));
        // Void leaf → no value bytes; covering leaf → the projection bytes (priced).
        assert_eq!(ctx.__get_list_u8(&plain_leaf), None);
        assert_eq!(ctx.__get_list_u8(&cover_leaf), Some(b"payload".to_vec()));
    }

    // A bucket segment is the field's TYPED codec element (not its decimal string):
    // a `u64` bucket is an int element, so the path is compact and a lookup that
    // encodes the same value finds the members — while the old string form ("5")
    // is NOT where the rows live.
    #[test]
    fn bucket_is_typed_codec_element() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let entry = |status: u64| IndexEntry {
            name_id: nid("status"),
            bucket: alloc::vec![status.index_key()], // int element, not "5"
            sort: None,
            projection: None,
        };
        apply_index_diff(&ctx, &index, &kb("k1".to_string()), &[], &[entry(5)]);
        apply_index_diff(&ctx, &index, &kb("k2".to_string()), &[], &[entry(5)]);

        // Rows live under the int-element bucket, NOT the string "5" bucket.
        let int_bucket = ix(&index, "status").push_element(&5u64);
        assert_eq!(ctx.__get_u64(&int_bucket), Some(2));
        assert_eq!(ctx.__get_u64(&ix(&index, "status").push("5")), None);
        let mut keys: Vec<String> = ctx.__get_keys(&int_bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["k1".to_string(), "k2".to_string()]);
    }

    // A composite index buckets on more than one segment (`<a>/<b>`). The member
    // rows, the count, and a scan all live under the multi-segment bucket path, and
    // a field change moves the member between buckets.
    #[test]
    fn composite_bucket_two_segments() {
        let ctx = Rc::new(Mock::default());
        let index = p("a#idx");
        // eligible index: bucket = [active, presence].
        let entry = |active: &str, presence: &str| IndexEntry {
            name_id: nid("eligible"),
            bucket: alloc::vec![active.to_string().encode(), presence.to_string().encode()],
            sort: None,
            projection: None,
        };
        apply_index_diff(
            &ctx,
            &index,
            &kb("k1".to_string()),
            &[],
            &[entry("true", "none")],
        );
        apply_index_diff(
            &ctx,
            &index,
            &kb("k2".to_string()),
            &[],
            &[entry("true", "none")],
        );
        apply_index_diff(
            &ctx,
            &index,
            &kb("k3".to_string()),
            &[],
            &[entry("true", "some")],
        );

        assert!(ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("none").push("k1")
        )));
        assert!(ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("some").push("k3")
        )));
        // Count lives AT the two-segment bucket path.
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("none"))),
            Some(2)
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("some"))),
            Some(1)
        );
        // Scan of the (true, none) bucket yields just its members.
        let bucket = ix(&index, "eligible").push("true").push("none");
        let mut keys: Vec<String> = ctx.__get_keys(&bucket).collect();
        keys.sort();
        assert_eq!(keys, alloc::vec!["k1".to_string(), "k2".to_string()]);

        // Flip k1's presence none -> some: one delete + one write, counts follow.
        apply_index_diff(
            &ctx,
            &index,
            &kb("k1".to_string()),
            &[entry("true", "none")],
            &[entry("true", "some")],
        );
        assert!(!ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("none").push("k1")
        )));
        assert!(ctx.__exists(&b(
            ix(&index, "eligible").push("true").push("some").push("k1")
        )));
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("none"))),
            Some(1)
        );
        assert_eq!(
            ctx.__get_u64(&b(ix(&index, "eligible").push("true").push("some"))),
            Some(2)
        );
    }

    // A byte field buckets by its raw codec bytes element (not hex) — distinct per
    // value, and decodable back to the bytes.
    #[test]
    fn bytes_index_key_is_raw_element() {
        let v = vec![0xde_u8, 0xad, 0xbe, 0xef];
        assert_eq!(v.index_key(), v.encode());
        let (back, _) = <Vec<u8>>::decode_from(&v.index_key()).unwrap();
        assert_eq!(back, v);
        // distinct bytes → distinct buckets
        assert_ne!(vec![0x01_u8].index_key(), vec![0x10_u8].index_key());
    }

    // A primitive buckets by its codec element — compact, not its decimal Display.
    #[test]
    fn primitive_index_key_is_codec_element() {
        assert_eq!(5u64.index_key(), 5u64.encode());
        assert_eq!(true.index_key(), true.encode());
        assert_ne!(1u64.index_key(), 2u64.index_key());
    }

    // An `Option` field and the `Presence` marker a lookup passes must produce the
    // same bucket key, or a write and its query would land in different buckets.
    #[test]
    fn option_and_presence_index_keys_agree() {
        assert_eq!(None::<u64>.index_key(), Presence::Absent.index_key());
        assert_eq!(Some(7u64).index_key(), Presence::Present.index_key());
        assert_eq!(None::<String>.index_key(), String::from("none").encode());
        assert_eq!(Some(7u64).index_key(), String::from("some").encode());
    }

    // A minimal `IndexScan` over the `Mock` so the query types can be exercised
    // end-to-end: it builds the same bucket path the field model does and delegates
    // to the mock's `__get_keys_range` / `__get_u64`, so the host-side `[lo, hi)`
    // seek and `descending` order are exercised for real.
    struct MockIndex {
        ctx: Rc<Mock>,
        root: KeyPath,
    }

    impl IndexScan<String> for MockIndex {
        type Storage = Mock;

        fn __index_bucket(&self, index_id: u8, bucket: &[&[u8]]) -> KeyRange<String, Mock> {
            let path = self.root.push_interned(index_id).push_raw_elements(bucket);
            KeyRange::new(self.ctx.clone(), path, ..)
        }
    }

    // Seed the `due`/`active` sorted bucket (sorted by a u64 height) out of order.
    fn seed_sorted_bucket() -> MockIndex {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let entry = |height: u64| IndexEntry {
            name_id: nid("due"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: Some(height.encode()),
            projection: None,
        };
        apply_index_diff(&ctx, &index, &kb("c".to_string()), &[], &[entry(30)]);
        apply_index_diff(&ctx, &index, &kb("a".to_string()), &[], &[entry(10)]);
        apply_index_diff(&ctx, &index, &kb("b".to_string()), &[], &[entry(20)]);
        MockIndex { ctx, root: index }
    }

    // A sorted query walks the bucket in value order and exposes keys/values/(k,s)
    // regardless of insertion order — the map-like shape the generated method builds.
    #[test]
    fn sorted_query_keys_values_iter_in_order() {
        let idx = seed_sorted_bucket();
        let q = || {
            SortedIndexQuery::<String, u64, _>::new(
                &idx,
                nid("due"),
                alloc::vec!["active".to_string().encode()],
            )
        };

        assert_eq!(q().keys().collect::<Vec<_>>(), vec!["a", "b", "c"]);
        assert_eq!(q().values().collect::<Vec<_>>(), vec![10u64, 20, 30]);
        assert_eq!(
            q().iter().collect::<Vec<_>>(),
            vec![
                ("a".to_string(), 10u64),
                ("b".to_string(), 20),
                ("c".to_string(), 30)
            ]
        );
        // IntoIterator yields (K, S).
        assert_eq!(q().into_iter().count(), 3);
        // len is the framework bucket count (O(1)); is_empty follows.
        assert_eq!(q().len(), 3);
        assert!(!q().is_empty());
    }

    // `.range(..)` bounds on the decoded sort value: inclusive/exclusive lo (a
    // host-side seek) and inclusive/exclusive hi (early-break), all bound kinds.
    #[test]
    fn sorted_query_range_bounds() {
        let idx = seed_sorted_bucket();
        let q = || {
            SortedIndexQuery::<String, u64, _>::new(
                &idx,
                nid("due"),
                alloc::vec!["active".to_string().encode()],
            )
        };

        // Inclusive both ends.
        assert_eq!(
            q().range(20u64..=30).keys().collect::<Vec<_>>(),
            vec!["b", "c"]
        );
        // Half-open upper (Excluded hi).
        assert_eq!(
            q().range(10u64..30).keys().collect::<Vec<_>>(),
            vec!["a", "b"]
        );
        // Exclusive lower bound drops the `== lo` member (seek then skip `sort == 10`).
        assert_eq!(
            q().range((Bound::Excluded(10u64), Bound::Unbounded))
                .keys()
                .collect::<Vec<_>>(),
            vec!["b", "c"]
        );
        // Unbounded lower, inclusive upper.
        assert_eq!(
            q().range(..=20u64).keys().collect::<Vec<_>>(),
            vec!["a", "b"]
        );
        // Fully unbounded == the whole bucket.
        assert_eq!(
            q().range(..).keys().collect::<Vec<_>>(),
            vec!["a", "b", "c"]
        );
        // Empty window.
        assert_eq!(
            q().range(21u64..=29).keys().collect::<Vec<_>>(),
            Vec::<String>::new()
        );
        // A range also exposes values / (k, s).
        assert_eq!(
            q().range(20u64..=30).values().collect::<Vec<_>>(),
            vec![20u64, 30]
        );
    }

    // `.rev()` flips the iteration order without changing membership, and composes
    // with `.range(..)` in either order (the range is direction-independent).
    #[test]
    fn sorted_query_rev_descending() {
        let idx = seed_sorted_bucket();
        let q = || {
            SortedIndexQuery::<String, u64, _>::new(
                &idx,
                nid("due"),
                alloc::vec!["active".to_string().encode()],
            )
        };

        // Whole bucket, highest-first.
        assert_eq!(q().rev().keys().collect::<Vec<_>>(), vec!["c", "b", "a"]);
        assert_eq!(q().rev().values().collect::<Vec<_>>(), vec![30u64, 20, 10]);
        // Double `.rev()` is ascending again.
        assert_eq!(
            q().rev().rev().keys().collect::<Vec<_>>(),
            vec!["a", "b", "c"]
        );
        // `.range(..).rev()` — bound first, then reverse.
        assert_eq!(
            q().range(10u64..=20).rev().keys().collect::<Vec<_>>(),
            vec!["b", "a"]
        );
        // `.rev().range(..)` — direction set first, carried into the range: same result.
        assert_eq!(
            q().rev().range(10u64..=20).keys().collect::<Vec<_>>(),
            vec!["b", "a"]
        );
        // Half-open upper still excludes `hi` under reversal.
        assert_eq!(
            q().range(10u64..30).rev().keys().collect::<Vec<_>>(),
            vec!["b", "a"]
        );
    }

    // The set-like query over an unsorted bucket: keys and the O(1) len/is_empty.
    #[test]
    fn plain_query_keys_and_len() {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        apply_index_diff(
            &ctx,
            &index,
            &kb("k1".to_string()),
            &[],
            &[e("status", "active")],
        );
        apply_index_diff(
            &ctx,
            &index,
            &kb("k2".to_string()),
            &[],
            &[e("status", "active")],
        );
        let idx = MockIndex { ctx, root: index };

        let q = || {
            IndexQuery::<String, _>::new(
                &idx,
                nid("status"),
                alloc::vec!["active".to_string().encode()],
            )
        };
        let mut keys = q().keys().collect::<Vec<_>>();
        keys.sort();
        assert_eq!(keys, vec!["k1".to_string(), "k2".to_string()]);
        assert_eq!(q().len(), 2);
        assert!(!q().is_empty());
        assert_eq!(q().into_iter().count(), 2);
    }

    // Assemble the covered projection `V` from a leaf's raw bytes — what the generated
    // per-index `build` fn does. Unsorted: V is just the included field(s). Sorted: the
    // sort value arrives separately (it's free in the member), plus the includes.
    fn build_name(proj: &[u8]) -> String {
        String::decode_from(proj)
            .expect("covering projection decodes")
            .0
    }
    fn build_due(sort: &u64, proj: &[u8]) -> (u64, String) {
        (
            *sort,
            String::decode_from(proj)
                .expect("covering projection decodes")
                .0,
        )
    }

    // Seed an UNSORTED covering bucket (`status` index covering a `name` field): the
    // leaf holds the name as its projection value.
    fn seed_covering_bucket() -> MockIndex {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let entry = |name: &str| IndexEntry {
            name_id: nid("status"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: None,
            projection: Some(name.to_string().encode()),
        };
        apply_index_diff(&ctx, &index, &kb("k1".to_string()), &[], &[entry("alice")]);
        apply_index_diff(&ctx, &index, &kb("k2".to_string()), &[], &[entry("bob")]);
        MockIndex { ctx, root: index }
    }

    // The unsorted covering query: keys() is the members, values() the covered
    // projection read straight from the leaf, iter() the (key, value) pairs.
    #[test]
    fn covering_query_keys_values_iter() {
        let idx = seed_covering_bucket();
        let q = || {
            CoveringQuery::<String, String, _>::new(
                &idx,
                nid("status"),
                alloc::vec!["active".to_string().encode()],
                build_name,
            )
        };

        let mut keys = q().keys().collect::<Vec<_>>();
        keys.sort();
        assert_eq!(keys, vec!["k1".to_string(), "k2".to_string()]);
        let mut values = q().values().collect::<Vec<_>>();
        values.sort();
        assert_eq!(values, vec!["alice".to_string(), "bob".to_string()]);
        let mut pairs = q().iter().collect::<Vec<_>>();
        pairs.sort();
        assert_eq!(
            pairs,
            vec![
                ("k1".to_string(), "alice".to_string()),
                ("k2".to_string(), "bob".to_string())
            ]
        );
        assert_eq!(q().len(), 2);
        assert!(!q().is_empty());
        assert_eq!(q().into_iter().count(), 2);
    }

    // Seed a SORTED covering bucket (`due` index sorted by a u64 height, covering
    // `name`) out of order: member is `(height, pk)`, value is the name.
    fn seed_sorted_covering_bucket() -> MockIndex {
        let ctx = Rc::new(Mock::default());
        let index = p("t#idx");
        let entry = |height: u64, name: &str| IndexEntry {
            name_id: nid("due"),
            bucket: alloc::vec!["active".to_string().encode()],
            sort: Some(height.encode()),
            projection: Some(name.to_string().encode()),
        };
        apply_index_diff(
            &ctx,
            &index,
            &kb("c".to_string()),
            &[],
            &[entry(30, "cara")],
        );
        apply_index_diff(&ctx, &index, &kb("a".to_string()), &[], &[entry(10, "ann")]);
        apply_index_diff(&ctx, &index, &kb("b".to_string()), &[], &[entry(20, "bob")]);
        MockIndex { ctx, root: index }
    }

    // The sorted covering query walks in value order and exposes keys (ZRANGE),
    // with_scores (ZRANGE WITHSCORES), values (covered V), and iter (K, V).
    #[test]
    fn sorted_covering_query_finishers_in_order() {
        let idx = seed_sorted_covering_bucket();
        let q = || {
            SortedCoveringQuery::<String, u64, (u64, String), _>::new(
                &idx,
                nid("due"),
                alloc::vec!["active".to_string().encode()],
                build_due,
            )
        };

        assert_eq!(q().keys().collect::<Vec<_>>(), vec!["a", "b", "c"]);
        assert_eq!(
            q().with_scores().collect::<Vec<_>>(),
            vec![
                ("a".to_string(), 10u64),
                ("b".to_string(), 20),
                ("c".to_string(), 30)
            ]
        );
        assert_eq!(
            q().values().collect::<Vec<_>>(),
            vec![
                (10u64, "ann".to_string()),
                (20, "bob".to_string()),
                (30, "cara".to_string())
            ]
        );
        assert_eq!(
            q().iter().collect::<Vec<_>>(),
            vec![
                ("a".to_string(), (10u64, "ann".to_string())),
                ("b".to_string(), (20, "bob".to_string())),
                ("c".to_string(), (30, "cara".to_string())),
            ]
        );
        assert_eq!(q().len(), 3);
        assert_eq!(q().into_iter().count(), 3);
    }

    // The sorted covering range: an inclusive/exclusive lower bound is a host-side
    // seek, the upper early-breaks — over all four finishers.
    #[test]
    fn sorted_covering_query_range_bounds() {
        let idx = seed_sorted_covering_bucket();
        let q = || {
            SortedCoveringQuery::<String, u64, (u64, String), _>::new(
                &idx,
                nid("due"),
                alloc::vec!["active".to_string().encode()],
                build_due,
            )
        };

        assert_eq!(
            q().range(20u64..=30).keys().collect::<Vec<_>>(),
            vec!["b", "c"]
        );
        assert_eq!(
            q().range(20u64..=30).values().collect::<Vec<_>>(),
            vec![(20u64, "bob".to_string()), (30, "cara".to_string())]
        );
        // Exclusive lower bound drops the `== lo` member (seek then skip `sort == 10`).
        assert_eq!(
            q().range((Bound::Excluded(10u64), Bound::Unbounded))
                .with_scores()
                .collect::<Vec<_>>(),
            vec![("b".to_string(), 20u64), ("c".to_string(), 30)]
        );
        // Half-open upper.
        assert_eq!(
            q().range(10u64..30).iter().collect::<Vec<_>>(),
            vec![
                ("a".to_string(), (10u64, "ann".to_string())),
                ("b".to_string(), (20, "bob".to_string()))
            ]
        );
    }

    // `.rev()` on the sorted covering query: descending over the covered finishers, and
    // composing with `.range(..)` either order round.
    #[test]
    fn sorted_covering_query_rev_descending() {
        let idx = seed_sorted_covering_bucket();
        let q = || {
            SortedCoveringQuery::<String, u64, (u64, String), _>::new(
                &idx,
                nid("due"),
                alloc::vec!["active".to_string().encode()],
                build_due,
            )
        };

        // Whole bucket, highest-first — covered values still assemble correctly.
        assert_eq!(q().rev().keys().collect::<Vec<_>>(), vec!["c", "b", "a"]);
        assert_eq!(
            q().rev().values().collect::<Vec<_>>(),
            vec![
                (30u64, "cara".to_string()),
                (20, "bob".to_string()),
                (10, "ann".to_string())
            ]
        );
        // `.range(..).rev()` and `.rev().range(..)` agree.
        assert_eq!(
            q().range(20u64..=30).rev().keys().collect::<Vec<_>>(),
            vec!["c", "b"]
        );
        assert_eq!(
            q().rev()
                .range(20u64..=30)
                .with_scores()
                .collect::<Vec<_>>(),
            vec![("c".to_string(), 30u64), ("b".to_string(), 20)]
        );
    }
    #[test]
    fn primary_key_ranges_cover_bounds_prefixes_and_reverse_scans() {
        let ctx = Rc::new(Mock::default());
        let path = KeyPath::new().push_interned(1);
        let keys: Vec<String> = ["a", "a\0", "a\0x", "aa", "b", "z"]
            .into_iter()
            .map(String::from)
            .collect();
        for key in &keys {
            // Two fields under each key exercise the whole-child boundary rule.
            ctx.__set_u64(&path.push_element(key).push_interned(0), 1);
            ctx.__set_u64(&path.push_element(key).push_interned(1), 2);
        }
        let bounds = [
            Bound::Unbounded,
            Bound::Included("a".to_string()),
            Bound::Excluded("a".to_string()),
            Bound::Included("b".to_string()),
            Bound::Excluded("b".to_string()),
        ];
        for lo in &bounds {
            for hi in &bounds {
                let expected: Vec<_> = keys
                    .iter()
                    .filter(|key| {
                        let lower = match lo {
                            Bound::Unbounded => true,
                            Bound::Included(v) => *key >= v,
                            Bound::Excluded(v) => *key > v,
                        };
                        let upper = match hi {
                            Bound::Unbounded => true,
                            Bound::Included(v) => *key <= v,
                            Bound::Excluded(v) => *key < v,
                        };
                        lower && upper
                    })
                    .cloned()
                    .collect();
                let query = || {
                    KeyRange::<String, _>::new(ctx.clone(), path.clone(), (lo.clone(), hi.clone()))
                };
                assert_eq!(query().keys().collect::<Vec<_>>(), expected);
                assert_eq!(
                    query().rev().keys().collect::<Vec<_>>(),
                    expected.into_iter().rev().collect::<Vec<_>>()
                );
            }
        }
        let after = KeyRange::<String, _>::new(
            ctx.clone(),
            path,
            (Bound::Excluded("ab".to_string()), Bound::Unbounded),
        );
        assert_eq!(after.keys().collect::<Vec<_>>(), ["b", "z"]);
    }

    #[test]
    fn compound_key_ranges_resume_after_removed_members_and_include_maximum() {
        let ctx = Rc::new(Mock::default());
        let path = KeyPath::new().push_interned(1);
        let keys = [
            ("file".to_string(), 1u64),
            ("file".to_string(), 2),
            ("file".to_string(), u64::MAX),
            ("next".to_string(), 1),
        ];
        for key in &keys {
            ctx.__set_u64(&path.push_element(key), 1);
        }
        ctx.__delete(&path.push_element(&keys[1]));
        let range = KeyRange::<_, _, ()>::new(
            ctx,
            path,
            (
                Bound::Excluded(keys[1].clone()),
                Bound::Included(keys[2].clone()),
            ),
        );
        assert_eq!(range.keys().collect::<Vec<_>>(), [keys[2].clone()]);
    }

    #[test]
    fn covering_key_ranges_do_not_fetch_projections_or_return_bucket_counts() {
        let ctx = Rc::new(Mock::default());
        let root = KeyPath::new().push_interned(2);
        let bucket_value = true.encode();
        let path = root.push_interned(0).push_raw_element(&bucket_value);
        ctx.__set_u64(&path.clone(), 3);
        for key in ["a", "aa", "b"] {
            ctx.__set_list_u8(
                &path.push_element(&key.to_string()),
                key.to_string().encode(),
            );
        }
        let index = MockIndex {
            ctx: ctx.clone(),
            root,
        };
        let query = || {
            CoveringQuery::new(&index, 0, vec![bucket_value.clone()], |bytes| {
                String::decode_from(bytes).unwrap().0
            })
        };
        assert_eq!(query().len(), 3);
        assert_eq!(
            query()
                .range((Bound::Excluded("a".to_string()), Bound::Unbounded))
                .keys()
                .collect::<Vec<_>>(),
            ["aa", "b"]
        );
        assert_eq!(*ctx.key_scans.borrow(), 1);
        assert_eq!(*ctx.row_scans.borrow(), 0);
        assert_eq!(
            query()
                .range("a".to_string()..="aa".to_string())
                .rev()
                .iter()
                .collect::<Vec<_>>(),
            [
                ("aa".to_string(), "aa".to_string()),
                ("a".to_string(), "a".to_string())
            ]
        );
        assert_eq!(*ctx.row_scans.borrow(), 1);
        assert_eq!(
            IndexQuery::new(&index, 0, vec![bucket_value])
                .range("b".to_string()..)
                .keys()
                .collect::<Vec<_>>(),
            ["b"]
        );
    }
}
