// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregateInfo = {
  /**
   * One entry per op in `Insts.ops`, in parallel order. Binds each
   * co-signer claim (existing `signer_id` or fresh x-only `PubKey`)
   * to its nonce (replay protection) and to a `sponsored` flag (whether
   * the publisher pays the op's gas).
   */
  signers: Array<AggregateSigner>;
  signature: Array<number>;
};

export type AggregateSigner = {
  identity: SignerRef;
  nonce: number;
  /**
   * `true` → this op's gas is paid by the publisher (the input's
   * signer) up to `Inst.gas_limit`. `false` → co-signer self-pays up
   * to `Inst.gas_limit`. The publisher commits by signing the bulk;
   * the co-signer commits via their BLS signature contribution.
   */
  sponsored: boolean;
};

export type Block = {
  height: number;
  hash: string;
  prev_hash: string;
  transactions: Array<Transaction>;
};

export type BlockRow = { height: number; hash: string; relevant: boolean };

/**
 * Request body for `POST /api/transactions/broadcast`: raw Bitcoin tx
 * hex in dependency order (e.g. `[commit, reveal]`), relayed to bitcoind
 * as a single `submitpackage`.
 */
export type BroadcastQuery = { transactions: Array<string> };

/**
 * Response from `POST /api/transactions/broadcast`: the txid of the last
 * transaction in the package — the reveal, which carries the Kontor op
 * and is what callers wait on for results.
 */
export type BroadcastResult = { txid: string };

export type CommitOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_inputs: RevealInputs;
};

export type ComposeOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_transaction: string;
  reveal_transaction_hex: string;
  reveal_psbt_hex: string;
  per_participant: Array<ParticipantScripts>;
};

export type ComposeQuery = {
  instructions: Array<InstructionQuery>;
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  envelope: number | null;
};

/**
 * Whether this node participates in consensus voting.
 *
 * Surfaced in the `Info` response so operators monitoring the cluster
 * externally can confirm a pod's actual mode rather than just trusting
 * the config they passed in.
 */
export type ConsensusMode = "validator" | "follower";

export type ContractListRow = {
  id: number;
  name: string;
  height: number;
  tx_index: number;
  size: number;
  signer_id: number | null;
};

export type ContractResponse = { wit: string };

export type ErrorResponse = { error: string };

export type Fees = {
  /**
   * Recommended fee rate (sat/vB) to land in the next ~1 block.
   */
  fastest: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 3 blocks.
   */
  half_hour: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 6 blocks.
   */
  hour: number;
};

export type HolderRef =
  | { "XOnlyPubkey": string }
  | { "SignerId": bigint }
  | "Core"
  | "Burner"
  | { "Utxo": OutPoint };

export type Info = {
  version: string;
  target: string;
  network: string;
  available: boolean;
  consensus_mode: ConsensusMode;
  height: number;
  checkpoint: string | null;
  consensus_height: number | null;
  /**
   * Highest `contract_results.id` — the SDK's forward cursor for
   * draining `/api/results`. 0 when no results exist yet.
   */
  last_result_id: number;
  /**
   * The last 10 indexed blocks, height-descending. The SDK compares
   * these against its local block-hash cache for reorg detection.
   */
  recent_blocks: Array<RecentBlock>;
  /**
   * Hash of `last_result_id` + `recent_blocks`. Pass back as
   * `?since=` to the long-poll endpoint; the request blocks until
   * this value changes.
   */
  signature: string;
};

export type Input = {
  previous_output: string;
  input_index: number;
  x_only_pubkey: string;
  insts: Insts;
};

export type Inst = {
  /**
   * Gas cap for this op. Self-pay default — the input's signer is
   * charged up to this amount.
   *
   * Overridden in two cases:
   * - Direct context with a previous-input `Sponsor` Inst → the
   *   Sponsor's own `gas_limit` is the cap and its signer is the payer.
   * - BLS aggregate with `AggregateSigner.sponsored = true` → the
   *   publisher (the input's signer) is the payer; `gas_limit` here is
   *   the cap they signed off on by signing the bulk.
   *
   * Otherwise: input signer is payer; `gas_limit` is the cap.
   *
   * Sentinel `0` is used for ops the runtime pays for (currently only
   * `InstKind::Issuance`, which bypasses gas accounting via `Signer::Core`).
   */
  gas_limit: number;
  kind: InstKind;
};

export type InstKind =
  | { "Publish": { name: string; bytes: Array<number> } }
  | { "Call": { contract: string; expr: string } }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  }
  | "Sponsor";

export type InstructionQuery = {
  address: string;
  x_only_public_key: string;
  funding_utxo_ids: string;
  insts: Insts;
  chained_insts: Insts | null;
};

export type Insts = { ops: Array<Inst>; aggregate: AggregateInfo | null };

export type Op = { metadata: OpMetadata; kind: OpKind };

export type OpKind =
  | { "Publish": { name: string; bytes: Array<number> } }
  | { "Call": { contract: string; expr: string } }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  }
  | "Sponsor";

export type OpMetadata = {
  previous_output: string;
  input_index: number;
  op_index: number;
  signer_id: number;
  payment: Payment;
};

/**
 * One OP_RETURN directive bound to the reveal input it applies to:
 * where the asset detached by that input's op should land. A
 * transaction's OP_RETURN payload is a `Vec<OpReturnEntry>` — the
 * per-input binding kept as a plain list (not a map) so it is fully
 * expressible in WIT — `list<op-return-entry>`.
 */
export type OpReturnEntry = { input_index: number; recipient: SignerRef };

/**
 * What happened when this op ran. Persisted per row in `contract_results`.
 *
 * - `Ok`: the contract function returned successfully.
 * - `ContractErr`: the function returned `result<_, error>::Err` — its state
 *   mutations were rolled back, but the call itself completed cleanly.
 * - `OutOfFuel`: the call ran out of fuel mid-execution (either a host
 *   import couldn't be charged, or wasmtime trapped on a fuel decrement).
 * - `Trap`: any non-fuel wasmtime trap — panic, unreachable, memory error.
 * - `Other`: a deterministic failure that doesn't fit the above (currently
 *   uncommon for rows that get inserted — pre-execution rejections like
 *   parse errors / contract-not-found don't reach `handle_procedure`).
 */
export type OpStatus = "Ok" | "ContractErr" | "OutOfFuel" | "Trap" | "Other";

/**
 * One entry per `Inst` in the input. `Materialized` means the op was
 * successfully materialized (had a runnable `Op`) and reached the runtime;
 * `Rejected` means materialization itself failed (currently only orphan
 * `Sponsored` ops with no publisher offer). Both variants carry an optional
 * `error_message` populated only on the `/transactions/simulate` endpoint;
 * `/inspect` always leaves it `None` since error strings aren't persisted.
 */
export type OpWithResult = {
  "kind": "Materialized";
  op: Op;
  result: ResultRow | null;
  error_message: string | null;
} | {
  "kind": "Rejected";
  input_index: number;
  op_index: number;
  error_message: string | null;
};

export type OutPoint = { txid: string; vout: bigint };

export type PaginatedResponse<T> = {
  results: Array<T>;
  pagination: PaginationMeta;
};

export type PaginationMeta = {
  next_cursor?: string;
  next_offset: number | null;
  has_more: boolean;
  total_count: number;
};

export type ParticipantScripts = {
  address: string;
  x_only_public_key: string;
  commit_tap_leaf_script: TapLeafScript;
  chained_tap_leaf_script: TapLeafScript | null;
};

/**
 * Resolved per-op execution payment, lives on `OpMetadata`.
 *
 * `signer_id` is who funds this op's gas; `gas_limit` is the cap.
 *
 * Derived from:
 * - Direct input, no `Sponsor`: `signer_id` = input signer, `gas_limit` = `Inst.gas_limit`.
 * - Direct input, prev-input `Sponsor` active: `signer_id` = sponsor's signer,
 *   `gas_limit` = sponsor's cap (overrides `Inst.gas_limit`).
 * - Aggregate input, `AggregateSigner.sponsored = false`: `signer_id` =
 *   co-signer, `gas_limit` = `Inst.gas_limit`.
 * - Aggregate input, `AggregateSigner.sponsored = true`: `signer_id` =
 *   publisher (the input's signer), `gas_limit` = `Inst.gas_limit`.
 *
 * `Issuance` carries a sentinel `Payment { signer_id: CORE_SIGNER_ID,
 * gas_limit: 0 }` since it's system-paid via the `Signer::Core` bypass
 * — the field exists for shape uniformity, not because Issuance funds
 * itself.
 */
export type Payment = { signer_id: number; gas_limit: number };

/**
 * One entry in `Info::recent_blocks` — a `BlockRow` trimmed to the
 * fields the SDK needs for reorg detection (no `relevant` flag).
 */
export type RecentBlock = { height: number; hash: string };

export type ResultResponse<T> = { result: T };

export type ResultRow = {
  id: number;
  height: number;
  tx_index: number | null;
  input_index: number | null;
  op_index: number | null;
  result_index: number;
  func: string;
  gas: number;
  /**
   * Outcome category for this op. `Ok` for successful calls (regardless
   * of whether the contract returned `ok(...)` or just a value); the
   * failure variants distinguish what went wrong.
   */
  status: OpStatus;
  value: string | null;
  contract: string;
  txid: string | null;
  signer_id: number;
  /**
   * Who funded gas for this op. Equals `signer_id` for self-pay ops;
   * for BLS-aggregate sponsored ops it's the publisher's signer_id.
   * `null` for ops that don't go through user-side gas accounting.
   */
  payer_signer_id: number | null;
};

export type RevealInputs = {
  fee_rate: number;
  participants: Array<RevealParticipantInputs>;
  op_return_data: Array<number> | null;
  envelope: number;
};

export type RevealOutputs = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  participants: Array<ParticipantScripts>;
};

export type RevealParticipantInputs = {
  address: string;
  x_only_public_key: string;
  commit_outpoint: string;
  commit_prevout: TxOutSchema;
  commit_tap_leaf_script: TapLeafScript;
  chained_instruction: Array<number> | null;
};

/**
 * One participant in a reveal: the outpoint they will script-spend in
 * the reveal tx, the prevout of that outpoint, and the leaf-script data
 * committed in its tap tree.
 *
 * `commit_*` here refers to the *tap-tree commitment* — the leaf script
 * that was committed to the spent output's tap tree — not the
 * commit-reveal pattern. The spent tx may itself be a commit tx (the
 * usual case) or a prior reveal tx whose output carried a chained leaf
 * (e.g. the seller's attach reveal whose output 0 carries the detach
 * leaf, then script-spent again in a swap).
 *
 * Each participant supplies its own `commit_outpoint`/`commit_prevout`,
 * so a single reveal can spend from multiple unrelated prior txs
 * (e.g. a swap that spends both a buyer's Sponsor commit and a seller's
 * attach reveal).
 */
export type RevealParticipantQuery = {
  address: string;
  x_only_public_key: string;
  commit_outpoint: string;
  commit_prevout: TxOutSchema;
  commit_script_data: Array<number>;
  chained_instruction: Array<number> | null;
};

export type RevealQuery = {
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  participants: Array<RevealParticipantQuery>;
  op_return_data: Array<number> | null;
  envelope: number | null;
};

/**
 * How a co-signer identifies themselves in an aggregate bulk.
 *
 * - `Id(u64)` is compact (8 bytes) for users who already have a
 *   `signer_id` from prior on-chain activity.
 * - `PubKey(XOnlyPublicKey)` is 32 bytes; used for first-time signers
 *   who don't yet have a `signer_id`. The reactor resolves it via
 *   `get_or_create_identity` during aggregate verification.
 *
 * Identity binding comes from the BLS signature verification, not from
 * which variant is chosen — the variant only controls how to *index*
 * the verification key, not which key.
 */
export type SignerRef = { "SignerId": number } | { "XOnlyPubkey": string };

export type SignerResponse = {
  signer_id: number;
  x_only_pubkey: string | null;
  bls_pubkey: Array<number> | null;
  next_nonce: number | null;
};

export type TapLeafScript = {
  leafVersion: number;
  script: string;
  controlBlock: string;
};

export type Transaction = {
  txid: string;
  index: number;
  inputs: Array<Input>;
  /**
   * OP_RETURN directives, one entry per reveal input that carries one.
   */
  op_return_data: Array<OpReturnEntry>;
};

export type TransactionHex = { hex: string };

export type TransactionRow = {
  id: number;
  txid: string;
  height: number;
  confirmed_height: number | null;
  tx_index: number | null;
  batch_height: number | null;
};

export type TxOutSchema = { value: number; script_pubkey: string };

export type ViewExpr = { expr: string };

export type ViewResult = { "type": "Ok"; value: string } | {
  "type": "Err";
  message: string;
};
