// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit transaction built by `compose_commit` / `compose`. There's
 * one entry per `CommitSource::Build` participant in the input `Reveal`,
 * in participant order.
 */
export type CommitTx = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
};

export type ComposeOutputs = {
  commits: Array<CommitTx>;
  reveal: RevealOutputs;
};

/**
 * Per-output annotation describing what kind of output occupies each
 * position in the reveal tx. Mirrors the input `RevealOutput` enum.
 * The wire shape includes only what the SDK can't derive from the tx
 * itself; in particular `ChainedEnvelope` carries the tap leaf script
 * that the chained tap output committed to.
 */
export type RevealOutputInfo = "Fixed" | "Change" | {
  "ChainedEnvelope": { tap_leaf_script: TapLeafScript };
} | "OpReturn";

export type RevealOutputs = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  /**
   * Per-participant tap leaf script + control block, parallel to the
   * reveal tx's inputs. Callers need these to assemble the script-path
   * witness when signing their input.
   */
  commit_tap_leaf_scripts: Array<TapLeafScript>;
  /**
   * Per-output kind + any extra info, in tx output order (same
   * length as `transaction.output`). Mirrors the input `RevealOutput`
   * enum and surfaces info derivable from compose-time state but not
   * from the tx alone — notably the tap leaf script + control block
   * for `ChainedEnvelope` outputs, which the caller needs to
   * script-spend that output in a follow-up tx.
   */
  output_info: Array<RevealOutputInfo>;
};

export type TapLeafScript = {
  leafVersion: number;
  script: string;
  controlBlock: string;
};
