// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AggregateInfo = {
  /**
   * One entry per op in `Insts.ops`, in parallel order. Binds each
   * co-signer claim (existing `signer_id` or fresh x-only `PubKey`)
   * to its nonce (replay protection) and to a `sponsored` flag (whether
   * the publisher pays the op's gas).
   */
  signers: Array<AggregateSigner>;
  signature: Array<number>;
};

export type AggregateSigner = {
  identity: SignerRef;
  nonce: number;
  /**
   * `true` → this op's gas is paid by the publisher (the input's
   * signer) up to `Inst.gas_limit`. `false` → co-signer self-pays up
   * to `Inst.gas_limit`. The publisher commits by signing the bulk;
   * the co-signer commits via their BLS signature contribution.
   */
  sponsored: boolean;
};

export type Block = {
  height: number;
  hash: string;
  prev_hash: string;
  transactions: Array<Transaction>;
};

export type BlockRow = { height: number; hash: string; relevant: boolean };

/**
 * Request body for `POST /api/transactions/broadcast`: raw Bitcoin tx
 * hex in dependency order (e.g. `[commit, reveal]`), relayed to bitcoind
 * as a single `submitpackage`.
 */
export type BroadcastQuery = { transactions: Array<string> };

/**
 * Response from `POST /api/transactions/broadcast`: the txid of the last
 * transaction in the package — the reveal, which carries the Kontor op
 * and is what callers wait on for results.
 */
export type BroadcastResult = { txid: string };

/**
 * Response from `compose_commit`: one `CommitTx` per Build participant,
 * plus the input `Reveal` with each Build participant's `CommitSource`
 * converted to `Existing` (outpoint + prevout filled in from the built
 * commit). The caller signs + broadcasts the commits, then later passes
 * the returned `reveal` to `compose_reveal` to build the reveal PSBT.
 */
export type CommitOutputs = { commits: Array<CommitTx>; reveal: Reveal };

/**
 * Whether this participant's commit already exists on chain or needs
 * to be built by this call.
 */
export type CommitSource = {
  "Existing": { outpoint: string; prevout: TxOutSchema };
} | { "Build": { address: string; funding_utxo_ids: Array<string> } };

/**
 * One commit transaction built by `compose_commit` / `compose`. There's
 * one entry per `CommitSource::Build` participant in the input `Reveal`,
 * in participant order.
 */
export type CommitTx = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  /**
   * Display-order txid — taproot witness data is segregated, so this
   * equals the txid of the signed tx too. Provided so the SDK can
   * reference this commit as a UTXO source without parsing the hex.
   */
  txid: string;
  /**
   * Value (sats) of the commit's change output at vout 1, or `None`
   * when the leftover was sub-dust and silently dropped to fee.
   * Compose computes this exactly (`selected_sum - tap_output_value
   * - commit_fee`), so the SDK gets it for free without parsing the
   * signed commit hex.
   */
  change_value: number | null;
};

/**
 * Response from `compose`: built commits (one per Build participant)
 * plus the built reveal PSBT. The caller signs each commit's input,
 * signs the reveal's tap-script-spend inputs (using
 * `RevealOutputs.commit_tap_leaf_scripts`), and broadcasts the package.
 */
export type ComposeOutputs = {
  commits: Array<CommitTx>;
  reveal: RevealOutputs;
};

/**
 * Whether this node participates in consensus voting.
 *
 * Surfaced in the `Info` response so operators monitoring the cluster
 * externally can confirm a pod's actual mode rather than just trusting
 * the config they passed in.
 */
export type ConsensusMode = "validator" | "follower";

export type ContractListRow = {
  id: number;
  name: string;
  height: number;
  tx_index: number;
  size: number;
  signer_id: number | null;
};

export type ContractResponse = { wit: string };

export type ErrorResponse = { error: string };

/**
 * A non-Kontor input (key-path spend) bringing extra value into the
 * reveal — beyond what the tap-leaf participants contribute.
 */
export type ExtraInput = { outpoint: string; prevout: TxOutSchema };

export type Fees = {
  /**
   * Recommended fee rate (sat/vB) to land in the next ~1 block.
   */
  fastest: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 3 blocks.
   */
  half_hour: number;
  /**
   * Recommended fee rate (sat/vB) to land in roughly the next 6 blocks.
   */
  hour: number;
};

export type HolderRef =
  | { "XOnlyPubkey": string }
  | { "SignerId": bigint }
  | "Core"
  | "Burner"
  | { "Utxo": OutPoint };

export type Info = {
  version: string;
  target: string;
  network: string;
  available: boolean;
  consensus_mode: ConsensusMode;
  height: number;
  checkpoint: string | null;
  consensus_height: number | null;
  /**
   * Highest `contract_results.id` — the SDK's forward cursor for
   * draining `/api/results`. 0 when no results exist yet.
   */
  last_result_id: number;
  /**
   * The last 10 indexed blocks, height-descending. The SDK compares
   * these against its local block-hash cache for reorg detection.
   */
  recent_blocks: Array<RecentBlock>;
  /**
   * Hash of `last_result_id` + `recent_blocks`. Pass back as
   * `?since=` to the long-poll endpoint; the request blocks until
   * this value changes.
   */
  signature: string;
};

export type Input = {
  previous_output: string;
  input_index: number;
  x_only_pubkey: string;
  insts: Insts;
};

export type Inst = {
  /**
   * Gas cap for this op. Self-pay default — the input's signer is
   * charged up to this amount.
   *
   * Overridden in two cases:
   * - Direct context with a previous-input `Sponsor` Inst → the
   *   Sponsor's own `gas_limit` is the cap and its signer is the payer.
   * - BLS aggregate with `AggregateSigner.sponsored = true` → the
   *   publisher (the input's signer) is the payer; `gas_limit` here is
   *   the cap they signed off on by signing the bulk.
   *
   * Otherwise: input signer is payer; `gas_limit` is the cap.
   *
   * Sentinel `0` is used for ops the runtime pays for (currently only
   * `InstKind::Issuance`, which bypasses gas accounting via `Signer::Core`).
   */
  gas_limit: number;
  kind: InstKind;
};

export type InstKind =
  | { "Publish": { name: string; bytes: Array<number> } }
  | { "Call": { contract: string; expr: string } }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  }
  | "Sponsor";

export type Insts = { ops: Array<Inst>; aggregate: AggregateInfo | null };

export type Op = { metadata: OpMetadata; kind: OpKind };

export type OpKind =
  | { "Publish": { name: string; bytes: Array<number> } }
  | { "Call": { contract: string; expr: string } }
  | "Issuance"
  | {
    "RegisterBlsKey": {
      bls_pubkey: Array<number>;
      schnorr_sig: Array<number>;
      bls_sig: Array<number>;
    };
  }
  | "Sponsor";

export type OpMetadata = {
  previous_output: string;
  input_index: number;
  op_index: number;
  signer_id: number;
  payment: Payment;
};

/**
 * One OP_RETURN directive bound to the reveal input it applies to:
 * where the asset detached by that input's op should land. A
 * transaction's OP_RETURN payload is a `Vec<OpReturnEntry>` — the
 * per-input binding kept as a plain list (not a map) so it is fully
 * expressible in WIT — `list<op-return-entry>`.
 */
export type OpReturnEntry = { input_index: number; recipient: SignerRef };

/**
 * What happened when this op ran. Persisted per row in `contract_results`.
 *
 * - `Ok`: the contract function returned successfully.
 * - `ContractErr`: the function returned `result<_, error>::Err` — its state
 *   mutations were rolled back, but the call itself completed cleanly.
 * - `OutOfFuel`: the call ran out of fuel mid-execution (either a host
 *   import couldn't be charged, or wasmtime trapped on a fuel decrement).
 * - `Trap`: any non-fuel wasmtime trap — panic, unreachable, memory error.
 * - `Other`: a deterministic failure that doesn't fit the above (currently
 *   uncommon for rows that get inserted — pre-execution rejections like
 *   parse errors / contract-not-found don't reach `handle_procedure`).
 */
export type OpStatus = "Ok" | "ContractErr" | "OutOfFuel" | "Trap" | "Other";

/**
 * One entry per `Inst` in the input. `Materialized` means the op was
 * successfully materialized (had a runnable `Op`) and reached the runtime;
 * `Rejected` means materialization itself failed (currently only orphan
 * `Sponsored` ops with no publisher offer). Both variants carry an optional
 * `error_message` populated only on the `/transactions/simulate` endpoint;
 * `/inspect` always leaves it `None` since error strings aren't persisted.
 */
export type OpWithResult = {
  "kind": "Materialized";
  op: Op;
  result: ResultRow | null;
  error_message: string | null;
} | {
  "kind": "Rejected";
  input_index: number;
  op_index: number;
  error_message: string | null;
};

export type OutPoint = { txid: string; vout: bigint };

export type PaginatedResponse<T> = {
  results: Array<T>;
  pagination: PaginationMeta;
};

export type PaginationMeta = {
  next_cursor?: string;
  next_offset: number | null;
  has_more: boolean;
  total_count: number;
};

/**
 * Resolved per-op execution payment, lives on `OpMetadata`.
 *
 * `signer_id` is who funds this op's gas; `gas_limit` is the cap.
 *
 * Derived from:
 * - Direct input, no `Sponsor`: `signer_id` = input signer, `gas_limit` = `Inst.gas_limit`.
 * - Direct input, prev-input `Sponsor` active: `signer_id` = sponsor's signer,
 *   `gas_limit` = sponsor's cap (overrides `Inst.gas_limit`).
 * - Aggregate input, `AggregateSigner.sponsored = false`: `signer_id` =
 *   co-signer, `gas_limit` = `Inst.gas_limit`.
 * - Aggregate input, `AggregateSigner.sponsored = true`: `signer_id` =
 *   publisher (the input's signer), `gas_limit` = `Inst.gas_limit`.
 *
 * `Issuance` carries a sentinel `Payment { signer_id: CORE_SIGNER_ID,
 * gas_limit: 0 }` since it's system-paid via the `Signer::Core` bypass
 * — the field exists for shape uniformity, not because Issuance funds
 * itself.
 */
export type Payment = { signer_id: number; gas_limit: number };

/**
 * One entry in `Info::recent_blocks` — a `BlockRow` trimmed to the
 * fields the SDK needs for reorg detection (no `relevant` flag).
 */
export type RecentBlock = { height: number; hash: string };

export type ResultResponse<T> = { result: T };

export type ResultRow = {
  id: number;
  height: number;
  tx_index: number | null;
  input_index: number | null;
  op_index: number | null;
  result_index: number;
  func: string;
  gas: number;
  /**
   * Outcome category for this op. `Ok` for successful calls (regardless
   * of whether the contract returned `ok(...)` or just a value); the
   * failure variants distinguish what went wrong.
   */
  status: OpStatus;
  value: string | null;
  contract: string;
  txid: string | null;
  signer_id: number;
  /**
   * Who funded gas for this op. Equals `signer_id` for self-pay ops;
   * for BLS-aggregate sponsored ops it's the publisher's signer_id.
   * `null` for ops that don't go through user-side gas accounting.
   */
  payer_signer_id: number | null;
};

/**
 * A complete description of a Kontor reveal tx. Used by `compose`,
 * `compose_commit`, and `compose_reveal`.
 */
export type Reveal = {
  /**
   * Optional: when omitted, the server falls back to its currently
   * published `fastest_fee` (sat/vB) from `/api/fees`.
   */
  sat_per_vbyte: number | null;
  participants: Array<RevealParticipant>;
  extra_inputs: Array<ExtraInput>;
  extra_outputs: Array<RevealOutput>;
};

/**
 * One output kind in a reveal tx. Appears either on a participant
 * (paired with that input's index, for SACP alignment) or in
 * `extra_outputs` (appended after all participant outputs in order).
 *
 * `Change` is the only variant whose value is computed by the
 * indexer (= leftover after fees + fixed outputs). It may only appear
 * at the tx's *last* output position; the indexer errors if a non-last
 * Change would be sub-dust (skipping it would shift later outputs and
 * break SACP positioning).
 */
export type RevealOutput =
  | { "Fixed": { script_pubkey: string; value: bigint } }
  | { "Change": { script_pubkey: string } }
  | { "ChainedEnvelope": { insts: Insts; value: bigint; internal_key: string } }
  | { "OpReturn": { data: Array<number> } };

/**
 * Per-output annotation describing what kind of output occupies each
 * position in the reveal tx. Mirrors the input `RevealOutput` enum.
 * Each variant carries the output's value in sats so the SDK can
 * extract change UTXOs / read fixed payouts without re-parsing the tx
 * hex; `ChainedEnvelope` additionally carries the tap leaf script the
 * chained output commits to (the future spender needs it).
 */
export type RevealOutputInfo =
  | { "Fixed": { value: number } }
  | { "Change": { value: number } }
  | { "ChainedEnvelope": { value: number; tap_leaf_script: TapLeafScript } }
  | "OpReturn";

export type RevealOutputs = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  /**
   * Display-order txid. Taproot witness data is segregated, so the
   * txid of the unsigned reveal here equals the signed-tx txid the
   * SDK eventually broadcasts. Lets the SDK reference reveal
   * outputs as UTXOs without parsing the hex.
   */
  txid: string;
  /**
   * Per-output kind + any extra info, in tx output order (same
   * length as `transaction.output`). Each variant carries the
   * output's value in sats — derivable from the tx but exposed
   * here so the SDK can extract change UTXOs / inspect output
   * values without parsing the raw hex.
   */
  output_info: Array<RevealOutputInfo>;
};

/**
 * One participant in the reveal: the tap-leaf script-spend input plus
 * the output paired with it (placed at the same index, which BIP-341
 * SIGHASH_SINGLE pre-signed signatures commit to).
 */
export type RevealParticipant = {
  x_only_public_key: string;
  commit_insts: Insts;
  /**
   * Optional. The common seller-offer pattern (chained envelope +
   * change in extras) leaves this unset; the marketplace swap sets
   * it to the SACP-paired output (Change for buyer, Fixed for seller).
   */
  output: RevealOutput | null;
  commit_source: CommitSource;
};

/**
 * How a co-signer identifies themselves in an aggregate bulk.
 *
 * - `Id(u64)` is compact (8 bytes) for users who already have a
 *   `signer_id` from prior on-chain activity.
 * - `PubKey(XOnlyPublicKey)` is 32 bytes; used for first-time signers
 *   who don't yet have a `signer_id`. The reactor resolves it via
 *   `get_or_create_identity` during aggregate verification.
 *
 * Identity binding comes from the BLS signature verification, not from
 * which variant is chosen — the variant only controls how to *index*
 * the verification key, not which key.
 */
export type SignerRef = { "SignerId": number } | { "XOnlyPubkey": string };

export type SignerResponse = {
  signer_id: number;
  x_only_pubkey: string | null;
  bls_pubkey: Array<number> | null;
  next_nonce: number | null;
};

export type TapLeafScript = {
  leafVersion: number;
  script: string;
  controlBlock: string;
};

export type Transaction = {
  txid: string;
  index: number;
  inputs: Array<Input>;
  /**
   * OP_RETURN directives, one entry per reveal input that carries one.
   */
  op_return_data: Array<OpReturnEntry>;
};

export type TransactionHex = { hex: string };

export type TransactionRow = {
  id: number;
  txid: string;
  height: number;
  confirmed_height: number | null;
  tx_index: number | null;
  batch_height: number | null;
};

export type TxOutSchema = { value: number; script_pubkey: string };

export type ViewExpr = { expr: string };

export type ViewResult = { "type": "Ok"; value: string } | {
  "type": "Err";
  message: string;
};
