extern crate proc_macro;

use proc_macro::TokenStream;
use quote::quote;
use syn::{DeriveInput, parse_macro_input};

#[proc_macro_derive(HelloWorld)]
pub fn hello_world_derive(input: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(input as DeriveInput);
    let name = &ast.ident;

    quote! {
        impl #name {
            pub fn hello_world() {
                println!("Hello, World! from {} generated by HelloWorld macro!", stringify!(#name));
            }
        }
    }
    .into()
}
