// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include <fbjni/fbjni.h>
#include "kontor-sdk-native.h"

namespace jsi = facebook::jsi;
namespace jni = facebook::jni;
namespace react = facebook::react;

// Automated testing checks Java_com_kontor_sdknative_KontorSdkNativeModule and kontormobile
// by comparing the whole line here.
/*
Java_com_kontor_sdknative_KontorSdkNativeModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return kontormobile::multiply(a, b);
}
*/

// Installer coming from KontorSdkNativeModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_kontor_sdknative_KontorSdkNativeModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    // React Native's CallInvokerHolder (CallInvokerHolderImpl on the Java side)
    // is an fbjni HybridClass: a Java object that wraps a C++ instance. Unwrap it
    // the way RN itself does in TurboModuleManager.cpp — wrap the incoming jobject
    // in an fbjni alias_ref and pull the C++ instance out with cthis().
    //
    // Do NOT reflect on fbjni's private fields (the old realm-js snippet here read
    // an mHybridData field off the holder): RN 0.83 / New Arch moved
    // CallInvokerHolderImpl onto com.facebook.jni.HybridClassBase and dropped that
    // field, so the reflection path throws NoSuchFieldError and aborts the process
    // on the first Kontor call. cthis() depends only on fbjni's public HybridClass
    // contract, so it is version-agnostic across that change.
    auto callInvokerHolder = jni::alias_ref<react::CallInvokerHolder::javaobject>{
        reinterpret_cast<react::CallInvokerHolder::javaobject>(callInvokerHolderJavaObj)};
    auto jsCallInvoker = callInvokerHolder->cthis()->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return kontormobile::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_kontor_sdknative_KontorSdkNativeModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return kontormobile::cleanupRustCrate(*runtime);
}